add new regions
livepeer/livepeer-monorepo pull request #1018
Opened 2021-08-27 16:19 UTC by adamsoffer

This PR adds 4 additional regions to the performance leaderboard:

NYC -> New York City
LAX -> Los Angeles
LON -> London
PRG -> Prague

Closes #1013

2021-08-27 18:19 UTC, yondonfu commented
Looks like there is a problem with sorting for a few regions.

For Singapore:

![Screen Shot 2021-08-27 at 2 18 42 PM](https://user-images.githubusercontent.com/5933273/131171765-c3971deb-2fb3-4787-9312-8c69712b5f9e.png)

![Screen Shot 2021-08-27 at 2 18 34 PM](https://user-images.githubusercontent.com/5933273/131171767-b843ed12-0d72-4be7-b6d6-5cc911853bc3.png)

2021-08-27 19:16 UTC, adamsoffer commented
@yondonfu just pushed up a UI fix.

2021-08-27 19:36 UTC, yondonfu commented
NYC shows all zero scores:

![Screen Shot 2021-08-27 at 3 35 20 PM](https://user-images.githubusercontent.com/5933273/131179878-8a792f3f-45bf-486b-9d0d-b63d5e809f26.png)

But, when I curl the leaderboard API directly, I see non-zero scores:

```
curl https://leaderboard-serverless.vercel.app/api/aggregated_stats\?region\=NYC\&since\=1630006475 | jq .
```

```
{
  "0x00803b76dc924ceabf4380a6f9edc2ddd3c90f38": {
    "NYC": {
      "success_rate": 0,
      "round_trip_score": 0,
      "score": 0
    }
  },
  "0x02b6aac33a397aaadee5227c70c69bb97f2cc529": {
    "NYC": {
      "success_rate": 1,
      "round_trip_score": 0.9855847303730806,
      "score": 0.9855847303730806
    }
  },
  "0x04c670b89907d9740c2f8683e397096d040b0682": {
    "NYC": {
      "success_rate": 0,
      "round_trip_score": 0,
      "score": 0
    }
  },
  "0x088fe56a58c11f86d63037552f0fe7f191d3aa1b": {
    "NYC": {
      "success_rate": 0,
      "round_trip_score": 0,
      "score": 0
    }
  },
  "0x0eed95c0a5d78c83033fe8a28dde67e5daac62db": {
    "NYC": {
      "success_rate": 0,
      "round_trip_score": 0,
      "score": 0
    }
  },
  "0x0fc80afb7876f579f1fb1c4d1c37cf1339038658": {
    "NYC": {
      "success_rate": 0,
      "round_trip_score": 0,
      "score": 0
    }
  },
  "0x10742714f33f3d804e3fa489618b5c3ca12a6df7": {
    "NYC": {
      "success_rate": 1,
      "round_trip_score": 0.7540124315455368,
      "score": 0.7540124315455368
    }
  },
  "0x10b21af759129f32c6064adfb85d3ea2a8c0209c": {
    "NYC": {
      "success_rate": 1,
      "round_trip_score": 0.7365042868801648,
      "score": 0.7365042868801648
    }
},

...
```

2021-08-27 19:41 UTC, yondonfu requested changes

2021-08-27 19:41 UTC, yondonfu commented on packages/explorer-2.0/components/Orchestrators/index.tsx
> +  lax: "Los Angelos",
```suggestion
  lax: "Los Angeles",
```

2021-08-27 19:41 UTC, yondonfu commented on packages/explorer-2.0/components/Orchestrators/index.tsx
> +                    <MenuItemRadio value="lax" label="Los Angelos" />
```suggestion
                    <MenuItemRadio value="lax" label="Los Angeles" />
```

2021-08-27 19:45 UTC, yondonfu commented
Noticed that the explorer queries `https://leaderboard-serverless.livepeerorg.vercel.app` [here](https://github.com/livepeer/livepeerjs/blob/834d035911c23fb29e981ed472fe3a32db739702/packages/explorer-2.0/apollo/createSchema.ts#L354), but my curl request in [this comment](https://github.com/livepeer/livepeerjs/pull/1018#issuecomment-907432046) drops the "livepeerorg" from the URL.

2021-08-27 20:35 UTC, yondonfu commented on packages/explorer-2.0/apollo/createSchema.ts
> +            `https://leaderboard-serverless.vercel.app/api/api/aggregated_stats?since=${ctx.since}`
```suggestion
            `https://leaderboard-serverless.vercel.app/api/aggregated_stats?since=${ctx.since}`
```

2021-08-27 20:38 UTC, adamsoffer commented on packages/explorer-2.0/apollo/createSchema.ts
> +            `https://leaderboard-serverless.vercel.app/api/api/aggregated_stats?since=${ctx.since}`
doh

2021-08-27 20:45 UTC, adamsoffer commented
@yondonfu I'm seeing scores in all the regions now.

2021-08-28 16:53 UTC, yondonfu approved these changes
LGTM. Let's merge & deploy first thing Monday once we make sure that https://top-performers.vercel.app/ is updated with the new regions as well.

Also, any idea why we were using that other leaderboard API URL before and not the one that was added in the latest commit?

2021-08-28 18:02 UTC, adamsoffer commented
> Also, any idea why we were using that other leaderboard API URL before and not the one that was added in the latest commit?

 I think I just wasn't aware of the cleaner URL at the time. Both of those domains should technically point to the same Vercel deployment so a bit odd they're returning different results 🤔

<img width="744" alt="Screen Shot 2021-08-28 at 12 55 19 PM" src="https://user-images.githubusercontent.com/555740/131226723-ad472525-5737-4eaf-853b-4a5c4152408f.png">

2021-08-28 18:08 UTC, adamsoffer commented
Ah I think I know why. `https://leaderboard-serverless.livepeerorg.vercel.app` and `https://leaderboard-serverless.vercel.app` points to the latest production deployment. `https://leaderboard-serverless-livepeerorg.vercel.app` used to point to the latest production deployment, but Vercel changed their autogenerated url structure.

2021-08-30 15:03 UTC, merged