134 protocol status WIP Closes #134
livepeer/livepeer-monorepo pull request #139
Opened 2018-06-28 22:16 UTC by palevoo

**What does this pull request do? Explain your changes. (required)**

Added Protocol Status Modal Component with data about Round
**Specific updates (required)**

- Added new route to modal in App.js
- New component Protocol Status
- 

**How did you test each of these updates (required)**

No testing
**Does this pull request close any open issues?**

#134 
**Screenshots (optional):**

<img width="1115" alt="screen shot 2018-06-29 at 00 16 10" src="https://user-images.githubusercontent.com/21197100/42063376-ab1c165e-7b31-11e8-89c1-8380dfdec106.png">

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2018-06-29 07:02 UTC, jozanza commented
Hey @palevoo thanks for working on this -- just curious about one thing:
This PR title says "WIP". Is it still work-in-progress? Or is it actually ready for review?

2018-06-29 07:37 UTC, palevoo commented
Everything, but the testing is ready for the review, ain't sure about the testing format.

2018-06-29 17:06 UTC, ericxtang commented
Hi @palevoo great work.  My only feedback is about following the layout specified in the original design.  You can leave the values cells empty (just fill out "# Blocks Until Round N").
![image](https://user-images.githubusercontent.com/345743/42105133-41cabcac-7b9d-11e8-9c23-95c8ef64aedc.png)

2018-06-29 17:09 UTC, jozanza requested changes
Good work! Just a few changes required @palevoo

2018-06-29 17:09 UTC, jozanza commented on packages/explorer/src/views/ProtocolStatus/index.js
> +              Number(currentRound.data.id) + Number(currentRound.data.length)
Issue #134 is asking for `# blocks until next round` rather than the next round starting block. So you'll need to make three updates:

1. Get the current block from GraphQL
2. Update the input label
3. Change the math used to derive the value

I believe you need to subtract the round start block from the sum of round start block and round length:

```js
/* packages/explorer/src/views/ProtocolStatus/enhance.js */
import { compose } from 'recompose'
import { connectCurrentBlockQuery, connectCurrentRoundQuery } from '../../enhancers'
export default compose(
  connectCurrentBlockQuery,
  connectCurrentRoundQuery
)

/* packages/explorer/src/views/ProtocolStatus/index.js */
// Use the MathBN util for safe operations on these strings since they represent uint256 values
import { MathBN } from '../../utils'
...
// This is the math you probably want to use:
const { id: currentBlock } = currentBlock.data
const { startBlock, length } = currentRound.data
const nextRoundStartBlock = MathBN.add(startBlock, length)
const blocksUntilNextRound = MathBN.sub(nextRoundStartBlock - currentBlock)
```

Only problem is `currentBlock` does not exist in our GraphQL schema at the moment. But I'll at it momentarily, and you can rebase to pull it into your branch 👍

2018-06-29 17:23 UTC, jozanza commented on packages/explorer/src/views/ProtocolStatus/index.js
> +              Number(currentRound.data.id) + Number(currentRound.data.length)
Okay just landed on `master`: https://github.com/livepeer/livepeerjs/commit/6ade586b8f3d100464bd3821e5a99e7c91376f78

Go ahead and rebase so you can get these changes @palevoo

2018-07-11 01:55 UTC, Randy1Burrell commented on packages/explorer/src/components/BasicNavbar.js
> +            style={{
Great work @jozanza, I have a few thoughts.
- Can we use classes instead of inline css?
- Can we factor the code so that there are no repetition? Ex. Line 70 - 92 is a repeat of most of this inline styling.

2018-07-14 04:25 UTC, merged

2018-07-14 04:25 UTC, Randy1Burrell commented
@jozanza and @palevoo thanks for your contribution.