work on #136 Add LPT to GraphQL
livepeer/livepeer-monorepo pull request #141
Opened 2018-06-29 18:26 UTC by mkpdev

@ericxtang I am done with #136 please review PR, and let me know suggestion/changes if required.

**What does this pull request do? Explain your changes. (required)**
It content work of issue #136 Add LPT to GraphQL

**Specific updates (required)**

- I have added `totalTokenSupply`,  `totalBondedToken`,   `targetBondingRate`,    `transcoderPoolMaxSize` attributes in protocol
- I have added `getTotalBonded`, `getTargetBondingRate`, `getTranscoderPoolMaxSize`, and `getProtocol` methods in `sdk/src/index.js`
- Modify `protocol` resolvers, fragement, types in `graphql-sdk`
- Modify `mock-sdk` with method `getProtocol`.
- Modify `Query.js` for `protocol`.
- Write test cases in `graphql-sdk` and `sdk`.

**How did you test each of these updates (required)**
I tested updates by writing test cases.

**Does this pull request close any open issues?**
It is related to #136 

**Checklist:**

- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

2018-06-29 21:33 UTC, jozanza requested changes
@mkpdev great job! I think you may have done a little too much though 😅 . I left some comments for review. Mostly, you just have to delete code now lol

2018-06-29 21:33 UTC, jozanza commented on packages/graphql-sdk/src/index.test.js
> +  ProtocolsQuery,
@mkpdev I can't think of a reason we need a "ProtocolsQuery" since this is just overview information about the Livepeer protocol itself. There is only 1 protocol, so we should remove any code related to this query.

2018-06-29 21:33 UTC, jozanza commented on packages/graphql-sdk/src/queries.js
> -  protocol {
You can revert the changes in this file. The protocol query does not need an id as a parameter, and there should not be any sort of `ProtocolsQuery`

2018-06-29 21:33 UTC, jozanza commented on packages/graphql-sdk/src/types/Query.js
> -  protocol: Protocol!
we should revert this as well.

2018-06-29 21:33 UTC, jozanza commented on packages/graphql-sdk/src/resolvers/Query.js
> +  const protocol = await ctx.livepeer.rpc.getProtocol(id)
@mkpdev There is no `getProtocol()` method in the sdk currently. You will have to add this one yourself (and it shouldn't need any arguments).

2018-06-29 21:33 UTC, jozanza commented on packages/graphql-sdk/src/resolvers/Query.js
> +export async function protocols(
We can remove this resolver

2018-06-29 21:33 UTC, jozanza commented on packages/graphql-sdk/src/resolvers/Protocol.js
> -  return 'protocol'
This can remain hard-coded to "protocol"; This field is only really required since Apollo relies on the `id` field for caching.

2018-06-29 21:33 UTC, jozanza commented on packages/graphql-sdk/src/queries.js
> +export const ProtocolsQuery = `
we can remove this query

2018-06-29 21:33 UTC, jozanza commented on packages/graphql-sdk/src/mock-sdk.js
> +const ALL_PROTOCOLS = [
We can remove  `ALL_PROTOCOLS` here -- just one `PROTOCOL` object.

2018-06-29 21:33 UTC, jozanza commented on packages/graphql-sdk/src/mock-sdk.js
> +    getProtocols: async () => ALL_PROTOCOLS,
We can remove this

2018-06-29 21:33 UTC, jozanza commented on packages/graphql-sdk/src/index.test.js
> -  // console.log(JSON.stringify(res, null, 2))
We can revert this test (no args required here)

2018-06-29 21:33 UTC, jozanza commented on packages/graphql-sdk/src/index.test.js
> +test('ProtocolsQuery', async t => {
Since we don't need to query for multiple Protocols (there is only one singleton), we can kill this test

2018-06-29 21:34 UTC, jozanza commented
Oh and @mkpdev please update your initial comment on this thread to reflect to format specified in https://raw.githubusercontent.com/livepeer/livepeerjs/master/PULL_REQUEST_TEMPLATE.md

2018-07-02 06:31 UTC, mkpdev commented
okay @jozanza will do mentioned changes. Thanks!

2018-07-03 15:21 UTC, ericxtang commented on packages/graphql-sdk/schema.json
> +                  "kind": "LIST",
@mkpdev I think in this case, the protocol is a "singleton", since we will only have a single protocol to refer to.  For example, we won't have to look up a protocol by its ID.

2018-07-04 07:28 UTC, mkpdev commented on packages/graphql-sdk/schema.json
> +                  "kind": "LIST",
@ericxtang I fixed it. Please check.

2018-07-11 03:09 UTC, Randy1Burrell commented on packages/graphql-sdk/src/resolvers/Query.js
> +  args: QueryProtocolArgs,
@mkpdev Thanks for a great work. Quick question about this part of the code. It seems to be giving an code quality error, and I have been looking at it a little. Just wondering, why are these params (obj and args) needed?

2018-07-16 10:23 UTC, mkpdev commented on packages/graphql-sdk/src/resolvers/Query.js
> +  args: QueryProtocolArgs,
@Randy1Burrell This function was already written I just change args from `QueryCurrentRoundArgs` to `QueryProtocolArgs` both have blank hash `{}`.

Also each function of this file accept 3 arguments `obj, args, ctx`.

2018-07-16 20:44 UTC, ericxtang commented on packages/sdk/src/index.js
> +  const {>>>>>>> master
@Randy1Burrell looks like a typo here.

2018-07-17 14:56 UTC, Randy1Burrell commented on packages/sdk/src/index.js
> +  const {>>>>>>> master
Hmmm, seems this happened because I didn't remove the git conflict tags. I will schedule time to deal with these soon.

2018-08-03 20:02 UTC, merged

2018-08-03 20:03 UTC, Randy1Burrell commented
@mkpdev Thanks for your contribution.