Add transcoder address to job info
livepeer/livepeer-monorepo pull request #209
Opened 2018-09-15 04:48 UTC by Randy1Burrell

**What does this pull request do? Explain your changes. (required)**

The SDK function getJob() currently will not return a transcoder address in the result object if the transcoder did not already submit an on-chain claim to store the transcoder address on-chain. This PR calls the contract function [electActiveTranscoder](https://github.com/livepeer/protocol/blob/master/contracts/bonding/BondingManager.sol#L651) in order to compute the assigned transcoder address to be returned with the result object.

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**

Fixes #190 
**Screenshots (optional):**

**Checklist:**

- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2018-09-17 18:53 UTC, yondonfu reviewed
Change looks good. Should we add a test in `index.test.js` to check that the shape of the return object from `getJob()` matches the expected schema?

2018-09-17 21:35 UTC, Randy1Burrell commented
@yondonfu good suggestion. I just added the test.

2018-09-21 20:04 UTC, yondonfu requested changes

2018-09-21 20:04 UTC, yondonfu commented on packages/sdk/src/index.js
> +      if (!x.transcoderAddress) {
If the job does not yet have a transcoder address attached to it `x.transcoderAddress` will actually be the null/empty address 0x0000000000000000000000000000000000000000

So we could change this check to `x.transcoderAddress === EMPTY_ADDRESS` (where EMPTY_ADDRESS is a constant already defined within the SDK)

2018-09-21 20:24 UTC, Randy1Burrell commented on packages/sdk/src/index.js
> +      if (!x.transcoderAddress) {
@yondonfu I made the change.

2018-09-21 20:48 UTC, yondonfu approved these changes
🚢

2018-09-21 20:52 UTC, merged