[Ready] player /channel/local mode
livepeer/livepeer-monorepo pull request #243
Opened 2018-10-12 17:53 UTC by ya7ya

**What does this pull request do? Explain your changes. (required)**
this checks for special `/local` instead of a broadcaster address to grab the local broadcasting. this works along with `current.m3u8` and allows devs to test their broadcast without needing a blockchain lookup

**Specific updates (required)**
- checks for route `/channel/local`
- override blockchain lookup if it's running in local mode.

**How did you test each of these updates (required)**
It works just like the production player, but will check the local broadcast if instructed. so this shouldn't break anything.

**Does this pull request close any open issues?**
No, but it was a feature request.

**Checklist:**
- [x] I have read the **CONTRIBUTING** document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

2018-10-23 02:22 UTC, Randy1Burrell reviewed
Hey @ya7ya, great work. I added some comment about possible changes. Let me know what you think.

2018-10-23 02:22 UTC, Randy1Burrell commented on packages/player/src/views/Channel/index.js
> +          rootUrl = 'http://localhost:8935/stream'
No break statement here? Won't `case 'local'` fall through to `default`?

2018-10-23 02:22 UTC, Randy1Burrell commented on packages/player/src/views/Channel/index.js
> +          return rootUrl
Why not put the `return` statement outside of the switch statement? This seems like it will only run on two conditions `local` and `default`.

2018-10-23 02:22 UTC, Randy1Burrell commented on packages/player/src/views/Channel/index.js
> +      const manifestId = latestJob.streamId.substr(0, 68 + 64)
Can we try/catch this? I think a try catch might fix #248 or maybe another solution for checking if stream exists. Please let me know what you think.

2018-10-23 11:01 UTC, ya7ya commented on packages/player/src/views/Channel/index.js
> +      const manifestId = latestJob.streamId.substr(0, 68 + 64)
I have changed this part to run the check for `latestJob` first.

```suggestion
      const [latestJob] = data.broadcaster.jobs

      if (!latestJob) {
        if (nextProps.loading === false) this.setState({ live: false })
        return
      }

      const manifestId = latestJob.streamId.substr(0, 68 + 64)
```

2018-10-23 11:02 UTC, ya7ya commented
hey @Randy1Burrell , Thanks for the review, I've made the changes, take a look and let me know if this works for ya :)

2018-10-23 16:15 UTC, Randy1Burrell requested changes
@ya7ya I found another issue I'd like to change before merging.

2018-10-23 16:15 UTC, Randy1Burrell commented on packages/player/src/views/Channel/index.js
> +  getRootUrl(location, address) {
@ya7ya Great job and thanks for fixing so quickly. Could we define this as a function just for good measure. Maybe `getRootUrl = (location, address) => {` or anything else you feel is necessary. Sorry for not mentioning this earlier.

2018-10-24 09:39 UTC, ya7ya commented on packages/player/src/views/Channel/index.js
> +  getRootUrl(location, address) {
@Randy1Burrell I'm not sure I follow, it is a function within `Channel` class, or do you mean `getRootUrl` should be defined outside the scope of `Channel` ??

2018-10-24 12:22 UTC, Randy1Burrell commented on packages/player/src/views/Channel/index.js
> +  getRootUrl(location, address) {
@ya7ya no I'm not saying you should define the method out of scope of `channel`. What I'm trying to say is that when I use a class method that begins with the word "get" then I'm usually returning a class variable. Otherwise, I think it's safer to use a function rather than an instance method.
Ex. 
```
getRootUrl() {
   return this.rootUrl
}
```
or

```
getRootUrl = (location, address) => {
    let rootUrl = location + address
    return rootUrl
}
```
Let me know what you think.

2018-10-24 14:24 UTC, ya7ya commented on packages/player/src/views/Channel/index.js
> +  getRootUrl(location, address) {
cool. I made the required change to the second option. 👍

2018-10-24 14:33 UTC, Randy1Burrell approved these changes
@ya7ya thanks man. Changes looks great!!

2018-10-24 14:34 UTC, merged