feat: 🎸Integrate Livepeer Subgraph
livepeer/livepeer-monorepo pull request #251
Opened 2018-10-27 02:31 UTC by adamsoffer

**What does this pull request do? Explain your changes. (required)**
This pull request reduces the Explorer's load time and incorporates aggregate data (missed reward calls over last 30 rounds to start) using [The Graph](https://thegraph.com/)'s self hosted data indexer ([Graph Node](https://github.com/graphprotocol/graph-node/)).

Note: The Explorer currently points to a Graph Node running on a staging server set up on a Google Cloud instance. I'm working (with the help of The Graph team) on setting up a production grade hosting environment and will update this pull request to point to the new server when ready.

**Specific updates (required)**
- Adds a brand new package to the mono repo called `subgraph`. This package contains the source code for the Livepeer Subgraph, a project that defines what Livepeer events we want our Graph Node to source and what transformations we'd like to make on the data in those events before storing it in a PostgreSQL database and serving it over a GraphQL endpoint. Instructions for running a Graph Node locally and deploying our subgraph are included in the `README`.
- Combines multiple GraphQL APIs (the remote subgraph api and the local graph-sdk api) into a single GraphQL API endpoint using [schema stitching](https://www.apollographql.com/docs/graphql-tools/schema-stitching.html) inside the `apollo` package.
  - Before stitching the two schemas together, we first check the network conditions of our remote indexer. If it's down, we don't stitch, otherwise we do. This check ensures a resilient UI in the event that the indexer goes down.
  - The `transcoders` query in the `subgraph` api purposefully overrides the `transcoders` query in the `graphql-sdk` when stitched. This allows us to keep changes to the Explorer codebase to a minimum. For example, we don't have to conditionally check which GraphQL query to use based on network conditions.  
-  Adds a column to the Explorer transcoder card for missed reward calls over last 30 rounds. (We're able to display this data because the indexer creates a unique "reward" entry in our PostgreSQL database for each eligible/active transcoder on every round. If a transcoder calls `reward` for a given round, we store its reward tokens inside this entry in a field called `rewardTokens`. In our GraphQL query, if `rewardTokens` returns `null` for a given transcoder and round then we know the transcoder failed to call `reward`.)
- Makes a slight modification to the `graph-sdk` transcoders query. I had to rename one of the argument to match the query signature in our subgraph schema. This also required me to run the script that auto generates our graphql-sdk docs hence all the generated doc changes.
- Adds an environment variable, `REACT_APP_LIVEPEER_SUBGRAPH`, for setting the subgraph's graphql endpoint. This currently points to the staging server I set up.       

**How did you test each of these updates (required)**
Ran all tests to see how updates affected other areas of code. All tests pass.

**Does this pull request close any open issues?**
Fixes #199, #192 

**Checklist:**
- [x] I have read the **CONTRIBUTING** document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2018-11-07 21:09 UTC, Randy1Burrell requested changes
@adamsoffer great work. I have some minor requests. Let me know what you think.

2018-11-07 21:09 UTC, Randy1Burrell commented on packages/explorer/.env.development
> +REACT_APP_LIVEPEER_SUBGRAPH=http://35.237.114.197:8000/by-name/livepeer/graphql
@adamsoffer I think we should remove the dependency on http://35.237.114.197:8000/by-name/livepeer/graphql and just leave a comment in this file saying that anyone can use this link for development purposes if they don't have their own dev box.
That way dev won't depend directly on you keeping this server running.
Example 
```
## Use http://35.237.114.197:8000/by-name/livepeer/graphql or set up your own development environment with a subgraph
REACT_APP_LIVEPEER_SUBGRAPH=
```

2018-11-07 21:09 UTC, Randy1Burrell commented on packages/explorer/src/components/TranscoderCard/index.js
> +        .slice(-30).length
Why do we limit missedCalls to the last 30?

2018-11-07 21:09 UTC, Randy1Burrell commented on packages/explorer/src/components/TranscoderCard/index.js
> +              help="Missed calls over last 30 eligible rounds."
Why do we limit missed calls to the last 30 rounds? What if more rounds are missed?

2018-11-07 21:09 UTC, Randy1Burrell commented on packages/explorer/src/views/Transcoders/index.js
> +              by checking out their social campaign on the Livepeer forum.
Can we put a link to the forum here?

2018-11-07 21:09 UTC, Randy1Burrell commented on packages/graphql-sdk/README.md
> +<td valign="top"><a href="#string">String</a></td>
This is not required anymore?

2018-11-07 21:09 UTC, Randy1Burrell commented on packages/explorer/.env.development
> +REACT_APP_LIVEPEER_SUBGRAPH=http://35.237.114.197:8000/by-name/livepeer/graphql
@adamsoffer Let's remove this value and make a comment that they can use your subgraph for testing.

```
## COMMENTS ABOUT USING YOUR SUBGRAPH HERE
￼ REACT_APP_LIVEPEER_SUBGRAPH=
```

That way default dev doesn't depend on your subgraph

2018-11-07 21:09 UTC, Randy1Burrell commented on packages/explorer/src/components/TranscoderCard/index.js
> +        .slice(-30).length
Why limit missedCalls to 30? What is missedCalls is more than 30?

2018-11-07 21:09 UTC, Randy1Burrell commented on packages/explorer/src/components/TranscoderCard/index.js
> +              help="Missed calls over last 30 eligible rounds."
Why limit missed calls to 30? What if missedCalls is more than 30? Can we make this more dynamic? 
Maybe `help="Missed calls over the last ${missedCalls} eligible rounds."`

2018-11-07 21:09 UTC, Randy1Burrell commented on packages/graphql-sdk/README.md
> +<td valign="top"><a href="#string">String</a></td>
Is this no longer required in graphql queries?

2018-11-07 21:09 UTC, Randy1Burrell commented on packages/subgraph/mappings/bondingManager.ts
> +import "allocator/arena";
@adamsoffer Can we include some more comments in the .ts files? Going forward I want to make it standard to have well documented/commented PRs.

2018-11-10 18:07 UTC, adamsoffer commented on packages/graphql-sdk/README.md
> +<td valign="top"><a href="#string">String</a></td>
@Randy1Burrell looks like this require was removed in a [commit](https://github.com/livepeer/livepeerjs/pull/113/files#diff-d945db54f3909cf2d4ff2b54cdc06e6b) back in June and the docs were just never regenerated.

Seems like it should be required though, so perhaps it wasn't intentional. If that's the case I can make that field required again and regenerate. cc: @yondonfu

2018-11-10 18:08 UTC, adamsoffer commented on packages/explorer/.env.development
> +REACT_APP_LIVEPEER_SUBGRAPH=http://35.237.114.197:8000/by-name/livepeer/graphql
Good call 👍

2018-11-10 18:30 UTC, adamsoffer commented on packages/explorer/src/components/TranscoderCard/index.js
> +        .slice(-30).length
Good question. I went along with the number suggested in [this issue](https://github.com/livepeer/livepeerjs/issues/192). It's like that saying "you're only as good as your last [fill in the blank]". If a transcoder missed a few calls over the course of one month (30 rounds) but then didn't miss a single round the following month, knowing the transcoder recently got its act together is valuable information that's otherwise lost if we display all. I'm open to suggestions though if we want to increase that time frame. cc: @ericxtang

2018-11-10 18:42 UTC, adamsoffer commented on packages/explorer/src/components/TranscoderCard/index.js
> +              help="Missed calls over last 30 eligible rounds."
Yeah ideally the user is able to select the number of past rounds. The transcoder detail view is probably a good candidate for this feature.

2018-11-10 18:44 UTC, adamsoffer commented on packages/subgraph/mappings/bondingManager.ts
> +import "allocator/arena";
Absolutely 👍

2018-11-10 18:44 UTC, adamsoffer commented on packages/explorer/src/views/Transcoders/index.js
> +              by checking out their social campaign on the Livepeer forum.
Sure 👍

2018-11-15 21:17 UTC, Randy1Burrell commented
@adamsoffer any updates?

2018-11-15 21:27 UTC, adamsoffer commented
@Randy1Burrell Plan on pushing up update with your feedback EOD tomorrow. Been working on provisioning production server past week.

2018-11-16 04:13 UTC, adamsoffer commented
@Randy1Burrell I pushed up some updates based on your feedback. You'll notice lots more comments! I'll have this production server provisioned along with instructions very soon. Collaborating w/ Eric on that.

2018-11-16 04:36 UTC, Randy1Burrell commented
@adamsoffer thanks man. I will review this soon. I'm excited to deploy this!!

2018-11-16 23:44 UTC, Randy1Burrell approved these changes
@adamsoffer great work. Thanks!!

2018-11-16 23:44 UTC, merged

2018-11-17 00:18 UTC, adamsoffer commented
Woohoo! Thanks @Randy1Burrell