[WIP] Unbonding locks
livepeer/livepeer-monorepo pull request #303
Opened 2018-12-25 00:08 UTC by samparsky

**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

- 
- 
- 

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**

#300 
#296 
#297 
**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2018-12-26 16:08 UTC, RaffiSapire commented
I have some comments on this issue. Do not change the text of the status and delegate at stake. 1) Status: if its just a partial unbond, the status should still be Bonded. 2) Delegate : should show the transcoder that the rest of the LPT is bonded to. 3) Stake: should show the 704. this is the 734-30 that were unbonded before the transaction, so it should show 704. Please review the breakdown I posted last week in this channel for a better understanding of how stake, pending Lpt, current stake are all impacted. 4) Unbonding transactions: please use the text I use in the mockup. Specifically, under 30 LPT it should say "You will be able to unbond on approximately Date, Month, Year." Under 20 LPT it should say "The unbonding period has completed. You may withdraw your LPT."


IF Complete Unbonding:
1) Status: Unbonded. 2) Delegate: N/A 3) Stake: 0 LPT

2019-01-03 09:52 UTC, Randy1Burrell requested changes
Nice work @samparsky, I left to comments.

2019-01-03 09:52 UTC, Randy1Burrell commented on packages/explorer/src/components/RebondForm/index.js
> +  amount,
Can we remove some of these unused params?

2019-01-03 09:52 UTC, Randy1Burrell commented on packages/explorer/src/components/RebondForm/index.js
> +          Sucess! {`${amount} LPT are now bonded back to ${delegateAddress}`}
Success

2019-01-03 09:52 UTC, Randy1Burrell commented on packages/explorer/src/components/UnbondTx.js
> +    e.preventDefault()
Do we need to preventDefault here, since the button is not a part of a form element?

2019-01-03 09:52 UTC, Randy1Burrell commented on packages/explorer/src/components/UnbondTx.js
> +                            withdrawRound - currentRound,
This function only take 1 param, can we remove the comma?

2019-01-03 09:52 UTC, Randy1Burrell commented on packages/explorer/src/components/WithdrawForm/index.js
> +  amount,
Can we remove the unused params?

2019-01-03 09:52 UTC, Randy1Burrell commented on packages/explorer/src/components/index.js
> +export { default as UnbondTx } from './UnbondTx'
Why is the name of UnbondTxComponent changed so many times? First it is exported as default, then as UnbondTx and then imported as UnbondTxComponent.

2019-01-03 09:52 UTC, Randy1Burrell commented on packages/explorer/src/views/AccountDelegating/enhance.js
> +    pollInterval: 60 * 1000,
Maybe it would be better to hard code `60000` rather than `60 * 1000`.

2019-01-03 09:52 UTC, Randy1Burrell commented on packages/explorer/src/views/AccountDelegating/index.js
> +  UnbondTx as UnbondTxComponent,
Why is the name of UnbondTxComponent changed so many times? See previous statement about this.

2019-01-03 09:52 UTC, Randy1Burrell commented on packages/explorer/src/views/AccountDelegating/index.js
> +      <MetricBox
Let's make this entire section hide/show based on whether you have previously unbonded.

2019-01-03 09:52 UTC, Randy1Burrell commented on packages/explorer/src/views/Rebond/enhance.js
> +      if (MathBN.gt(unclaimedRounds, '20')) {
We're no longer using hard coded value for unclaimedRounds. See #233 for details about our current solution.

2019-01-03 09:52 UTC, Randy1Burrell commented on packages/explorer/src/enhancers/index.js
> +    pollInterval: 10 * 1000,
Probably best to hard code `10000` rather than multiplying every time.

2019-01-04 18:57 UTC, samparsky commented on packages/explorer/src/components/index.js
> +export { default as UnbondTx } from './UnbondTx'
@Randy1Burrell

2019-01-04 19:33 UTC, samparsky commented on packages/explorer/src/views/AccountDelegating/index.js
> +      <MetricBox
done

2019-01-11 08:24 UTC, Randy1Burrell commented on packages/explorer/src/components/UnbondTx.js
> +          <h3>
Here can be refactored.

```JavaScript
<h3> 
  <strong>{formatBalance(amount)} LPT</strong> <br />{' '}
   {withdrawRound <= currentRound ? (
     <span style={{ fontSize: 12 }}>
       The unbonding period has completed and you can withdraw your LPT.
     </span>
     ) : (
      <span style={{ fontSize: 12, marginTop: '-10px' }}>
          You will be able to unbond approximately on{' '}
          {formatRoundsToDate(withdrawRound - currentRound)}.
        </span> 
      ) 
</h3>
```

2019-01-11 09:36 UTC, Randy1Burrell requested changes
Great work @samparsky, can we add some tests for the SDK methods.

2019-01-11 09:36 UTC, Randy1Burrell commented on packages/sdk/src/index.js
> +      while (unbondingLockId > 0) {
unbondingLockId starts at 0 so this should be 
```JavaScript
while (unbondingLockId >= 0) {
```

2019-01-11 09:36 UTC, Randy1Burrell commented on packages/sdk/src/index.js
> +      } else if (amount === '0') {
What happens if `amount < 0`?

2019-01-11 09:43 UTC, samparsky commented on packages/sdk/src/index.js
> +      } else if (amount === '0') {
can amount be < 0? I don't think so

2019-01-11 09:47 UTC, Randy1Burrell commented on packages/sdk/src/index.js
> +      } else if (amount === '0') {
We're not the only ones using the SDK. Let's say I wanted to be malicious and see what happens when I pass amount as a negative value. What happens then?

2019-01-11 14:45 UTC, Randy1Burrell approved these changes
Nice work @samparsky. LGTM! 💯

2019-01-11 14:45 UTC, merged