fix(packages/explorer/graphql-sdk/src/resolvers/Mutations.js): Fix un…
livepeer/livepeer-monorepo pull request #310
Opened 2019-01-11 15:07 UTC by Randy1Burrell

…defined defaultTX err

**What does this pull request do? Explain your changes. (required)**

Fixes a a bug that causes undefined defaultTx err when unbonding.

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**

**Screenshots (optional):**

**Checklist:**

- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2019-02-04 20:12 UTC, yondonfu requested changes

2019-02-04 20:12 UTC, yondonfu commented on packages/graphql-sdk/src/resolvers/Mutation.js
> +    console.log(err)
I think that if `estimateGas()` throws an error we will continue and try submitting a transaction with 0 gas which would always fail - perhaps we should prevent transaction submission in this case.

2019-02-04 20:12 UTC, yondonfu commented on packages/explorer/src/components/ClaimEarningsForm/index.js
> +          #{endRound}. You now have {Math.abs(remaining)} rounds of earnings
Has it ever been the case where `remaining` is negative? If so, I think something somewhere else is going wrong i.e. allowing someone to try to claim earnings for more rounds than should be possible and that the problem should be resolved there. Otherwise, if `remaining` is indeed negative here, then the user is still shown inaccurate information i.e. taking the absolute value of a negative # of rounds claimed which wouldn't make sense.

2019-02-04 20:12 UTC, yondonfu commented on packages/explorer/src/components/ClaimEarningsForm/index.js
> +            <strong>Note:</strong> You may claim up to {maxEarningsClaimsRounds}{' '}
Out of curiosity what does `{' ' }` do? Is it not sufficient to just have `{maxEarningsClaimsRounds} rounds`?

2019-02-04 20:12 UTC, yondonfu commented on packages/explorer/src/components/UnbondTx.js
> +              ? `You will be able to unbond approximately on
Should this be "You will be able to withdraw approximately on..."?

2019-02-04 20:12 UTC, yondonfu commented on packages/explorer/src/components/UnbondTx.js
> +              : `This amount of LPT can be unbonded on
Should this be "This amount of LPT can be withdraw on..."?

2019-02-04 20:12 UTC, yondonfu commented on packages/explorer/src/components/UnbondingForm/index.js
>            It will take 7 days (the unbonding period) in order to be able to
Just noting that ideally the unbonding period would be fetched from the contract instead of using a hardcoded number of days since technically the unbonding period could be changed in the future. This can probably be resolved outside of this PR though.

2019-02-04 20:12 UTC, yondonfu commented on packages/explorer/src/enhancers/index.js
> +    withdrawAmount
I don't think we need `withdrawAmount` and `withdrawRound` in this query anymore since we can also query for unbonding locks now? These fields were originally included to hide unbonding locks from the user (since a UI for unbonding locks was not available yet)

2019-02-04 20:12 UTC, yondonfu commented on packages/explorer/src/views/AccountOverview/index.js
> +    unbondlocks = unbondlocks.reduce(reducer, 0)
This is a little confusing to me as `unbondlocks` initially is an array and then after this reduction it stores a single value - perhaps track the accumulated value in a separate variable for clarity

2019-02-04 20:12 UTC, yondonfu commented on packages/explorer/src/views/AccountOverview/index.js
> +          help={`The amount of Livepeer Token (LPT) owned  owned by this
"(LPT) owned  owned" -> "(LPT) owned by"?

2019-02-04 20:12 UTC, yondonfu commented on packages/explorer/src/views/ClaimEarnings/index.js
> +        maxEarningsClaimsRounds={maxEarningsClaimsRounds}
Are the brackets around `maxEarningsClaimsRounds` necessary?

2019-02-04 21:22 UTC, iameli requested changes

2019-02-04 21:22 UTC, iameli commented on packages/explorer/src/views/AccountDelegating/index.js
> +        {console.log(withdrawRound)}
This is a bit noisy

2019-02-04 21:22 UTC, iameli commented on packages/explorer/src/components/ClaimEarningsForm/index.js
> +            <strong>Note:</strong> You may claim up to {maxEarningsClaimsRounds}{' '}
Usually these are introduced by Prettier being overzealous in maintaining the input formatting

2019-02-04 21:22 UTC, iameli commented on packages/explorer/src/utils.js
> +    window.web3 = new window.Web3(window.ethereum)
I'm not yet familiar with these, but might it ever be the case that `window.Web3` is defined but `window.ethereum` is not? `if (window.Web3 && window.ethereum)`, perhaps?

2019-02-04 21:22 UTC, iameli commented on packages/explorer/src/views/AccountOverview/index.js
> +          value={
I also fixed this in my branch; I'll take that commit out of my PR.

2019-02-04 21:22 UTC, iameli commented on packages/graphql-sdk/src/resolvers/Mutation.js
> +    console.log(err)
Could just take out the try/catch entirely and bubble up the error.

2019-02-04 21:22 UTC, iameli commented on packages/explorer/src/components/BondForm/index.js
> +              min={noZero ? Math.pow(10, -18).toString() : '0'}
Does this field take a string? It looks like every other field takes a number.

2019-02-04 21:22 UTC, iameli commented on packages/explorer/src/views/AccountOverview/index.js
> +  unbondlocks: GraphQLProps<UnbondLock>,
Perhaps camelcase'd `unbondLocks` for consistency?

2019-02-04 21:22 UTC, iameli commented on packages/explorer/src/views/AccountOverview/index.js
> +      (accumulator = MathBN.add(accumulator, itemNext.amount))
I don't believe the `accumulator =` assignment is necessary here, `MathBN.add` is already returning the value you want

2019-02-04 21:22 UTC, iameli commented on packages/explorer/src/components/MetricBox.js
> +              fontSize: valueSize || '1.17em',
Another way to handle this would be to pass a `textStyle` prop to `MetricBox` and deconstruct it at the end of this `style`:

```
<strong
  style={{
    fontWeight: 400,
    textOverflow: 'ellipsis',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    fontSize: '1.17em',
    ...(textStyle || {})
  }}
>
```

And invoke with:
```
<MetricBox textStyle={{fontSize: "100px"}} />
```

That'll allow for more customization in the future without adding more props

2019-02-04 21:22 UTC, iameli commented on packages/explorer/src/components/UnbondTx.js
> +            justifyContent: 'flex-start',
I don't believe this will have an effect unless there's a `display: flex` on the box (I know this wasn't your change though)

2019-02-04 21:22 UTC, iameli commented on packages/explorer/src/views/ClaimEarnings/index.js
> +        maxEarningsClaimsRounds={maxEarningsClaimsRounds}
Yeah, it'd put that name in there as a string otherwise

2019-02-05 01:57 UTC, Randy1Burrell commented on packages/explorer/src/components/ClaimEarningsForm/index.js
> +          #{endRound}. You now have {Math.abs(remaining)} rounds of earnings
Yes it has been a case where remaining is negative, and sure there is something wrong somewhere. I have found it to say I have -30 unclaimed rounds when I actually have 30 unclaimed rounds. This Math.abs I'll remove until someone is able to find the actual bug.

2019-02-05 01:59 UTC, Randy1Burrell commented on packages/explorer/src/components/UnbondingForm/index.js
>            It will take 7 days (the unbonding period) in order to be able to
Sure let's resolve this in another PR.

2019-02-05 02:02 UTC, Randy1Burrell commented on packages/explorer/src/views/AccountDelegating/index.js
> +        {console.log(withdrawRound)}
My mistake. I should have removed this when I was cleaning up the code. I guess I missed it, removing it now.

2019-02-05 03:45 UTC, Randy1Burrell commented on packages/explorer/src/utils.js
> +    window.web3 = new window.Web3(window.ethereum)
@iameli thanks. I've add this in for good measure in case someone screws up and forget to inject ethereum along with web3, but to answer your question MetaMask usually injects both Web3 and etheream into the window object.

2019-02-05 03:55 UTC, Randy1Burrell commented on packages/explorer/src/views/AccountOverview/index.js
> +  unbondlocks: GraphQLProps<UnbondLock>,
@iameli UnbondLock is Pascal Cased for consistency with the rest of the src files in the explorer. Notice how line 35 `Transaction` is Pascal case.

2019-02-05 04:16 UTC, Randy1Burrell commented on packages/explorer/src/views/AccountOverview/index.js
> +  unbondlocks: GraphQLProps<UnbondLock>,
@iameli My bad, I thought you meant camel casing the `UnbondLock` prop for GraphQL. Changing it in this area means I will have to change other areas that have already been merged. It's probably best not to touch any other area yet, being that I'm on a tight deadline.

2019-02-05 04:30 UTC, Randy1Burrell commented on packages/explorer/src/components/MetricBox.js
> +              fontSize: valueSize || '1.17em',
Great suggestion! I have implemented this.

2019-02-05 04:36 UTC, Randy1Burrell commented on packages/explorer/src/components/UnbondTx.js
> +            justifyContent: 'flex-start',
@iameli Thanks for the review. Implemented!

2019-02-05 04:37 UTC, Randy1Burrell commented
@yondonfu and @iameli changes have been implemented.

2019-02-05 17:42 UTC, iameli commented
LGTM! 🚢

2019-02-05 19:04 UTC, yondonfu approved these changes
LGTM

2019-02-05 21:55 UTC, merged