[WIP, needs some dead code removal] Remove ethereum addresses from @livepeer/player
livepeer/livepeer-monorepo pull request #320
Opened 2019-02-01 19:35 UTC by iameli

Most of the refactor is done but there's still a lot of dead code to be torn out — everything relating to jobs and GraphQL.

**What does this pull request do? Explain your changes. (required)**
`@livepeer/player` shan't use Ethereum addresses going forward. This PR removes them and has all pertinent logic utilize HLS manifest URLs directly instead.

**Specific updates (required)**
- Lots of GraphQL/Apollo/Web3 removal
- A new container class, `<QueryHandler>`, that allows for shared logic between `<Channel>` (which is kinda poorly named now) and `<Embed>`.
- Some routing tweaks to implement the above
- Misc polish all over; added `<form>` tags for searching where appropriate

**How did you test each of these updates (required)**
- Ran through the Landing, Channel, and Embed views, attempting to utilize every feature
- Checked to make sure video still played on each view, 

**Does this pull request close any open issues?**

**Screenshots (optional):**
![image](https://user-images.githubusercontent.com/257909/52144967-9acf7780-2614-11e9-8e9f-b0717eb5aa15.png)
![image](https://user-images.githubusercontent.com/257909/52145222-45479a80-2615-11e9-9e8a-56918710c714.png)
![image](https://user-images.githubusercontent.com/257909/52145253-58f30100-2615-11e9-8d7b-2cbd12b6b724.png)
![image](https://user-images.githubusercontent.com/257909/52145302-76c06600-2615-11e9-8574-d7b91274ce98.png)

2019-02-01 23:33 UTC, iameli commented
Hmm, the remaining test failure is codeclimate complaining about files in `explorer` that I didn't touch. I'm happy to refactor, but presumably that wouldn't block this merge?

2019-02-02 00:22 UTC, iameli commented
And upon a second glance, both things flagged by codeclimate are destructuring assignments that would be difficult to refactor away in any case.

2019-02-02 02:49 UTC, Randy1Burrell commented
@iameli In response to your question, no that would not block this merge once everything is good with your PR otherwise. I will review this PR tomorrow.

2019-02-03 00:38 UTC, Randy1Burrell commented
@iameli great work so far. I am getting this error whenever I test the explorer on small screen and try to type in the search bar that appears in the dropdown menu.

```JavaScript
Unhandled Rejection (TypeError): Cannot read property 'item' of undefined
_callee$
src/components/BasicNavbar.js:197
  194 |   </Btn>
  195 | }
  196 | onSelect={async ({ detail }) => {
> 197 |   const { action } = detail.item.dataset
      | ^  198 |   switch (action) {
  199 |     case 'feedback':
  200 |       return window.open(
View compiled
▶ 7 stack frames were collapsed.
(anonymous function)
src/components/BasicNavbar.js:196
  193 |     <Icon use="more_vert" />
  194 |   </Btn>
  195 | }
> 196 | onSelect={async ({ detail }) => {
      | ^  197 |   const { action } = detail.item.dataset
  198 |   switch (action) {
  199 |     case 'feedback':
View compiled
▼ 18 stack frames were expanded.
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js:147
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:196
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:250
invokeGuardedCallbackAndCatchFirstError
node_modules/react-dom/cjs/react-dom.development.js:265
executeDispatch
node_modules/react-dom/cjs/react-dom.development.js:571
executeDispatchesInOrder
node_modules/react-dom/cjs/react-dom.development.js:596
executeDispatchesAndRelease
node_modules/react-dom/cjs/react-dom.development.js:695
executeDispatchesAndReleaseTopLevel
node_modules/react-dom/cjs/react-dom.development.js:704
forEachAccumulated
node_modules/react-dom/cjs/react-dom.development.js:674
runEventsInBatch
node_modules/react-dom/cjs/react-dom.development.js:844
runExtractedEventsInBatch
node_modules/react-dom/cjs/react-dom.development.js:852
handleTopLevel
node_modules/react-dom/cjs/react-dom.development.js:5025
batchedUpdates$1
node_modules/react-dom/cjs/react-dom.development.js:19916
batchedUpdates
node_modules/react-dom/cjs/react-dom.development.js:2246
dispatchEvent
node_modules/react-dom/cjs/react-dom.development.js:5105
interactiveUpdates$1
node_modules/react-dom/cjs/react-dom.development.js:19978
interactiveUpdates
node_modules/react-dom/cjs/react-dom.development.js:2267
dispatchInteractiveEvent
node_modules/react-dom/cjs/react-dom.development.js:5081
▲ 18 stack frames were expanded.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
```

![image](https://user-images.githubusercontent.com/10135939/52170945-d60b9c80-2721-11e9-9f5b-0bc7ba356925.png)

![image](https://user-images.githubusercontent.com/10135939/52170954-f76c8880-2721-11e9-9831-c1a5c284bdd1.png)

2019-02-04 20:32 UTC, iameli commented
@Randy1Burrell Thanks for the review — addressed in e482f8c32ce276e85bdfb9feb0abcef65ddae7e5

2019-02-04 22:33 UTC, iameli commented
Rebased to clean up some excessive commits and incorporate removing `iconOptions`, which React was complaining about.

2019-02-05 21:50 UTC, Randy1Burrell requested changes

2019-02-05 21:50 UTC, Randy1Burrell commented on packages/player/src/containers/App.js
> +// https://player.livepeer.org/play?url=https://abc123.cloudflare.net/something/current
Can we remove this if it's not being used anymore?

2019-02-05 21:50 UTC, Randy1Burrell commented on packages/player/src/containers/App.js
> +      {/* <Route exact path="/channels/:channel" component={Channel} />
Remove these too.

2019-02-05 21:50 UTC, Randy1Burrell commented on packages/player/src/services/index.js
> +// import { fork } from 'redux-saga/effects'
This can be removed too.

2019-02-05 21:50 UTC, Randy1Burrell commented on packages/player/src/services/index.js
>  export function* rootSaga() {
This function doesn't make sense having, because it does nothing anymore.

2019-02-05 21:51 UTC, Randy1Burrell commented
The banner at the bottom is being cut off.
![image](https://user-images.githubusercontent.com/10135939/52306510-3428c180-2966-11e9-9570-958a3babde09.png)

2019-02-07 19:19 UTC, Randy1Burrell approved these changes
LGTM!

2019-02-07 20:07 UTC, merged