Integrate staking alerts
livepeer/livepeer-monorepo pull request #370
Opened 2019-03-27 02:15 UTC by adamsoffer

**What does this pull request do? Explain your changes. (required)**
This PR integrates the [Livepeer Studio](https://livepeer.studio/staking-alerts) staking alerts into the Explorer. 

**Specific updates (required)**
- Adds a call to action to sign up for staking alerts after a user successfully bonds their token
- Adds a call to action  to sign up for staking alerts underneath the "staking" tab
- Introduces a form for signing up for staking alerts
- Cleans up the `BasicModal` styles a bit

Note while reviewing: after clicking confirm in the verification email, it brings the user to the explorer and lets the user know they've been successfully subscribed inside a modal. When reviewing this PR locally you won't see this modal unless you replace `explorer.livepeer.org` with `localhost:3000`.

**How did you test each of these updates (required)**
- Signed up using the form and confirmed receipt of emails

**Screenshots:**

Call to action after bonding:
<img width="648" alt="Screen Shot 2019-03-26 at 9 57 01 PM" src="https://user-images.githubusercontent.com/555740/55044919-73909780-5012-11e9-88e7-2ba4baad5af9.png">

Call to action on staking tab:
<img width="399" alt="Screen Shot 2019-03-26 at 9 56 23 PM" src="https://user-images.githubusercontent.com/555740/55044930-7ab7a580-5012-11e9-91b0-a602982f1180.png">

Sign up form:
<img width="771" alt="Screen Shot 2019-03-26 at 8 45 41 PM" src="https://user-images.githubusercontent.com/555740/55044943-85723a80-5012-11e9-83af-0daf4d030ec6.png">

Copy after submitting form:
<img width="679" alt="Screen Shot 2019-03-26 at 9 43 02 PM" src="https://user-images.githubusercontent.com/555740/55044963-94f18380-5012-11e9-808d-8b92fc508ea0.png">

Copy after clicking confirm in email:
<img width="663" alt="Screen Shot 2019-03-26 at 9 40 47 PM" src="https://user-images.githubusercontent.com/555740/55044974-a0dd4580-5012-11e9-916c-f259ad0f4bb9.png">

Copy after unsubscribing:
<img width="672" alt="Screen Shot 2019-03-26 at 9 41 20 PM" src="https://user-images.githubusercontent.com/555740/55045014-c702e580-5012-11e9-9078-a7db4932e1dc.png">

**Checklist:**
- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2019-03-27 14:06 UTC, dob commented
Cool! Quick mention of a typo in the Unsubscribe confirmation dialog header.

2019-03-27 15:30 UTC, adamsoffer commented
> Cool! Quick mention of a typo in the Unsubscribe confirmation dialog header.

@dob ah thanks! Just fixed.

2019-03-29 22:42 UTC, iameli requested changes

2019-03-29 22:42 UTC, iameli commented on packages/explorer/src/components/StakingAlertsForm/index.js
> +    recaptchaRef.current.execute()
I don't follow how this works... isn't any kind of CAPTCHA rate-limiting going to require that the Livepeer.studio server only accepts requests with some kind of ReCAPTCHA token? Couldn't I just comment out this line and spam your server?

2019-03-29 22:42 UTC, iameli commented on packages/explorer/src/components/StakingAlertsForm/index.js
> +    console.log(e)
Should have some kind of user-facing error handling here - minimally an `alert()` just so they don't keep spamming  the button.

2019-03-29 22:42 UTC, iameli commented on packages/explorer/src/views/StakingAlerts/index.js
> +  const accountId = window.location.pathname.split('/')[2]
There's a better - thought still not great - way to handle this - use the `getAccountParam` function in `src/util.js`

2019-03-29 22:42 UTC, iameli commented on packages/explorer/src/components/StakingAlertsForm/index.js
> +  const regex = /^0x[a-fA-F0-9]{40}$/g
Could you add this and the `regex.test` logic to a `checkEthereumAddress` function in `util.js`? This is really something we should be doing, like, everywhere.

2019-03-29 22:42 UTC, iameli commented on packages/explorer/src/index.js
> +    .grecaptcha-badge {
Let's put this in another `injectGlobal` in the email notification form itself, I'll 100% forget what this is for otherwise 😃

2019-04-01 03:14 UTC, adamsoffer commented on packages/explorer/src/components/StakingAlertsForm/index.js
> +    recaptchaRef.current.execute()
You could, but this is really just aimed at preventing automated software/crawlers from filling out and submitting the form, not necessarily a malicious actor.

2019-04-01 03:14 UTC, adamsoffer commented on packages/explorer/src/components/StakingAlertsForm/index.js
> +    console.log(e)
👍

2019-04-01 03:14 UTC, adamsoffer commented on packages/explorer/src/views/StakingAlerts/index.js
> +  const accountId = window.location.pathname.split('/')[2]
👍

2019-04-01 03:15 UTC, adamsoffer commented on packages/explorer/src/components/StakingAlertsForm/index.js
> +  const regex = /^0x[a-fA-F0-9]{40}$/g
👍

2019-04-01 03:15 UTC, adamsoffer commented on packages/explorer/src/index.js
> +    .grecaptcha-badge {
👍

2019-04-01 03:18 UTC, adamsoffer commented
@iameli Thanks v much for the feedback. Just pushed up your suggestions.

2019-04-01 03:45 UTC, adamsoffer commented on packages/explorer/src/components/StakingAlertsForm/index.js
> +    recaptchaRef.current.execute()
(It's admittedly naive spam prevention as it's only implemented client side.)

2019-04-01 15:04 UTC, adamsoffer commented on packages/explorer/src/components/StakingAlertsForm/index.js
> +    recaptchaRef.current.execute()
Actually, now that I think about this some more, you're right, this invisible recatpcha is pretty useless the way it's currently implemented lol. I'm going to remove it for now and just rely on an API rate limiter on the livepeer studio server endpoint.

2019-04-01 15:19 UTC, adamsoffer commented on packages/explorer/src/components/StakingAlertsForm/index.js
> +    recaptchaRef.current.execute()
I've also added a hidden honeypot field. If a spambot fills it out, I can ignore the submission server side.

2019-04-02 21:16 UTC, iameli commented on packages/explorer/src/components/StakingAlertsForm/index.js
> +    recaptchaRef.current.execute()
Nice, sounds solid

2019-04-02 21:18 UTC, iameli commented on packages/explorer/src/components/StakingAlertsForm/index.js
> +              My email address is*
Intentional asterisk here?

2019-04-02 21:18 UTC, iameli commented on packages/explorer/src/components/StakingAlertsForm/index.js
> +              My email address is*
Oh, to denote "required." Cool.

2019-04-02 21:22 UTC, iameli approved these changes

2019-04-02 21:22 UTC, merged