[Dont Merge] feat: http bearer token authentation middleware
livepeer/livepeer-monorepo pull request #450
Opened 2019-09-04 17:27 UTC by ya7ya

**What does this pull request do? Explain your changes. (required)**
allows the API to create and verify http tokens

**Specific updates (required)**
- 
- 
- 

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**
closes #449 

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2019-09-09 21:57 UTC, iameli commented on packages/api/src/middleware/auth.js
> +const router = Router()
Somehow it never occurred to me to use a router for middleware like this. Nice!

2019-09-09 22:05 UTC, iameli requested changes
Solid start, `express-bearer-token` seems very useful. Proposed one change to the structure and one change to the token validation logic.

2019-09-09 22:05 UTC, iameli commented on packages/api/src/middleware/auth.js
> +router.use(bearerToken())
Somehow it never occurred to me to use a router for a middleware function like this. Nice! Seems to work well.

2019-09-09 22:05 UTC, iameli commented on packages/api/src/middleware/auth.js
> +async function generateToken(req, res, next) {
I don't think at this point we ever want to generate a new token - we want all existing users to have a token already. Two scenarios:

1. The user doesn't provide a token — `req.token` is undefined. In this case, we should return `401`, and throw out the request (by not calling `next()`)
2. The user provides a token. In this case, we should check to make sure it's in our database — and if it's not, we should do a `req.store.create` with the `id` as the id they provided.

Once we've added all the existing API tokens to the database, we can then push a new update that sends `403`s if they don't send a valid token.

2019-09-09 22:05 UTC, iameli commented on packages/api/src/index.js
> +  app.use(authMiddleware)
I think using the same `authMiddleware` for every single request will quickly become limiting. We'll want some endpoints to be public, some to require valid API tokens (Wowza client), and some to require some other form of administrator access (Livepeer admin client). So let's leave it off here.

The other thing we can do — and I should have done this with all of our other middlewares — is put the middleware in a factory function so that we can pass various parameters to the middleware. That way we can eventually have:

```
router.get("/extremely-secret-secrets", authMiddleware({adminsOnly: true}), (req, res) => {})
```

For now, all that'll be necessary is wrapping `authMiddleware` in a big factory function so we can call it like 

```
app.use(authMiddleware())
```

All that'll be necessary for now is wrapping all of `authMiddleware` in a `function

2019-09-16 19:11 UTC, iameli requested changes
Good improvements, added a few more comments regarding how we'll utilize this middleware on a per-endpoint basis

2019-09-16 19:11 UTC, iameli commented on packages/api/src/middleware/auth.js
> +    } catch (e) {
Let's make sure this still throws an error if it's anything other than a `NotFoundError` so we don't accidentally create new tokens if the database is down or something.

```
if (e.type !== "NotFoundError") {
  throw e;
}
```

2019-09-16 19:11 UTC, iameli commented on packages/api/src/middleware/auth.js
> +    otherdata: 1,
This can be removed

2019-09-16 19:11 UTC, iameli commented on packages/api/src/middleware/auth.js
> +  const id = uuid()
For the autogen case, we want the token in the database to match up with what they provided in the `token` field, so `id` should be `req.token`.

2019-09-16 19:11 UTC, iameli commented on packages/api/src/middleware/auth.js
> +async function generateToken(req, res, next) {
I think all of this has been addressed except the very end of 2: "with the id as the id they provided."

2019-09-16 19:11 UTC, iameli commented on packages/api/src/index.js
> +  if (authEnabled) {
Good example, but maybe comment this stuff for now? Don't think we'll implement this as a CLI parameter.

2019-09-16 19:11 UTC, iameli commented on packages/api/src/middleware/auth.js
> +  return router.use(async (req, res, next) => {
This shouldn't reference the `router`, as it's middleware intended to be used elsewhere. Here, we can just have

```
function authFactory(params) {
  return async (req, res, next) => {
``` 

And then we'll utilize it on a per-endpoint basis - something like this should be added to `POST /stream` over in that controller:

```
router.post("/", authMiddleware(), (req, res, next) => {
```

That way we can use the same middleware with slightly different parameters for each function.

2019-09-16 19:11 UTC, iameli commented on packages/api/src/middleware/auth.js
> +async function verifyToken(req, res, next) {
Looks like this is duplicated logic from what's in the `authFactory`

2019-09-23 19:36 UTC, ya7ya commented on packages/api/src/index.js
> +  if (authEnabled) {
how would we toggle this on and off ?  or is the auth middleware is always on ?

2019-09-23 20:03 UTC, iameli commented on packages/api/src/index.js
> +  if (authEnabled) {
Yep, it'll always be on.

2019-09-23 21:03 UTC, ya7ya commented on packages/api/src/index.js
> +  if (authEnabled) {
got it , done.

2019-09-23 22:59 UTC, iameli approved these changes
LGTM!

2019-09-23 23:01 UTC, merged