Feat: API pagination for the streams endpoint
livepeer/livepeer-monorepo pull request #451
Opened 2019-09-06 16:53 UTC by ya7ya

**What does this pull request do? Explain your changes. (required)**
adds `limit` and `offset` capabilities to the API so it won't list the entire list of streams every time. and it can be used for pagination

**Specific updates (required)**
- updates to `leveldb` to use `limit` 
- updates to the `postgresql` to use `limit` and `offset`
- 

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2019-09-09 22:10 UTC, iameli requested changes
Looks solid if you can rebase out the auth commits. I'll file a separate issue for a "continuation token" kind of design.

2019-09-09 22:10 UTC, iameli commented on packages/api/src/store/level-store.js
> +  async list(prefix = '', limit = DEFAULT_LIMIT, offset = 0) {
This is fine for now; it's hard for me to imagine a LevelDB API user with thousands of thousands of streams. We will eventually need a more sophisticated way to handle query continuations but I can file that as a separate enhancement.

2019-09-09 22:10 UTC, iameli commented on packages/api/package.json
> +    "express-bearer-token": "^2.4.0",
Mind doing a `git rebase -i eli/api-node-prototype` and taking out the auth commits so this can merge separately?

2019-09-10 14:17 UTC, ya7ya commented on packages/api/src/store/level-store.js
> +  async list(prefix = '', limit = DEFAULT_LIMIT, offset = 0) {
yeah, I'll figure out a more efficient way then 👍

2019-09-16 19:01 UTC, iameli approved these changes

2019-09-16 19:01 UTC, iameli commented
LGTM! I'll merge to bypass the failing CI, hopefully fixing that today.

2019-09-16 19:01 UTC, merged