Introduce Livepeer UI
livepeer/livepeer-monorepo pull request #467
Opened 2019-09-24 03:15 UTC by adamsoffer

**What does this pull request do? Explain your changes. (required)**
This PR introduces the `livepeer-ui` package, a set of primitive react components built with [theme-ui](https://theme-ui.com).

The goal is for this package to be used by all Livepeer products in an effort to unify our brand and product design around a shared visual language, promote constraint-based design principles, promote consistency in how we use patterns and UI elements, and to ship products faster and more efficiently.

**Specific updates (required)**

This package includes the following:
- An initial set of components (`Button`, `Chip`, `Card`, `List`, `ListItem`, `Spinner`, `Logo`). More to come.
- A theme object adhering to the [system-ui spec](https://system-ui.com/).
- A [storybook](https://storybook.js.org/) for viewing and interacting with components in isolation.

**Does this pull request close any open issues?**
Addresses #459 

**Screenshots (optional):**

**Checklist:**
- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2019-09-24 19:27 UTC, iameli commented
Looking great! Remind me the difference between `<div sx={...}>` and `<Styled.div sx={...}>`? I think that's the one part I don't really follow so far

2019-09-24 19:45 UTC, adamsoffer commented
:)

Sure. `<Styled.div>`, `<Styled.h1>`, etc inherit styles defined inside our theme object. So if we have, for example, the following styles assigned to `h1` in our theme object then `<Styled.h1>` will inherit those styles:

```javascript
{
  fonts: {
    body: 'system-ui, sans-serif',
    heading: 'Georgia, serif',
  },
  styles: {
    h1: {
      fontSize: 32,
      fontFamily: 'heading',
      fontWeight: 'heading',
      color: 'primary',
      mt: 4,
      mb: 2,
    },
  }
}
```

I don't actually define any global style to a `div` in our theme object so I should actually remove any instances of `Styled.div`.

2019-09-24 22:07 UTC, iameli requested changes
Bumping `explorer` and `player`'s `react-scripts` to `^3.1.2` seems to unbreak the CI build - looks great other than that! Feel free to merge when that's in :shipit:

2019-09-24 22:07 UTC, iameli commented on packages/livepeer-ui/package.json
> +    "dev:babel": "babel --ignore node_modules,src/**/*.stories.tsx --out-dir dist -x '.tsx' --watch .",
Can we add a `dev:storybook` that runs `start-storybook`? Would be nice to run that app alongside everything else when hacking on it.

(I'm thinkin' let's just rename all the existing `start` scripts to `dev` to line up with Now's conventions but still have a nice `yarn run dev` command that starts everything. But that doesn't need to happen in this PR.)

2019-09-24 22:07 UTC, iameli commented on packages/livepeer-ui/package.json
> +  "license": "ISC",
We're MIT-licensed everywhere else, probably no reason to switch that up

2019-09-25 14:23 UTC, adamsoffer commented on packages/livepeer-ui/package.json
> +    "dev:babel": "babel --ignore node_modules,src/**/*.stories.tsx --out-dir dist -x '.tsx' --watch .",
Yeah good call.

2019-09-25 14:24 UTC, adamsoffer commented on packages/livepeer-ui/package.json
> +  "license": "ISC",
oops! Was unintended, I'll switch to MIT.

2019-09-26 03:35 UTC, merged