WIP cursor based pagination
livepeer/livepeer-monorepo pull request #473
Opened 2019-09-27 18:47 UTC by ya7ya

**What does this pull request do? Explain your changes. (required)**
adds cursor based pagination to the api , [details](https://github.com/livepeer/livepeerjs/issues/456)

**Specific updates (required)**

- 
- 
- 

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**
Fixes #456 

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2019-09-27 21:29 UTC, iameli commented
Looks like a good start! A few things we'll want in here...

1. The cursor will need to be returned from any `list` queries. Probably the easiest way to implement this would be to change `store.list()` to return a `[docs, cursor]` tuple, something like:

```
const [output, cursor] = await req.store.list(`stream/`, cursor, limit, offset)
```
2. That cursor will have to be communicated back to the user somehow. In the past I've seen this handled with an HTTP header: [I like the way Mixer handles it with the "link" header.](https://dev.mixer.com/guides/core/continuationtokens)

3. I kind of think this mechanism should replace "offset", which is unsupported by both LevelDB and Cloudflare Worker KV.

2019-10-04 18:45 UTC, iameli commented on packages/api/src/controllers/stream.js
> +  const output = await req.store.list(`stream/`, cursor, limit)
Hmm, I think that it's probably both possible that a user could provide a cursor and no limit (to just get page 2 with the default limit) and also a limit and no cursor (page 1, just give me limit number of results please). So either one of these could be undefined, so let's probably just put them in an options object? ` const output = await req.store.list(`stream/`, {cursor, limit})`

2019-10-04 18:53 UTC, iameli requested changes
I'm still inclined to return the cursor in the `Link` header unless we can think of other stuff that we'd want to return in the context, I think

2019-10-04 18:53 UTC, iameli commented on packages/api/src/controllers/stream.js
> +    context.cursor = output[output.length - 1].id
This might work in both of our existing cases but it won't work with other stores, including Cloudflare Worker KV. So this logic should live in the stores themselves, and we return the cursor along with the content in `req.store.list` - that's that tuple technique that I mentioned before.

2019-10-04 18:53 UTC, iameli commented on packages/api/src/controllers/stream.js
> +  res.json({ payload: output, context })
Hmm, I see what you meant by returning an object now. I still kind of like the idea of returning the next page in the `link` header [like Mixer does](https://dev.mixer.com/guides/core/continuationtokens), allowing end users not to have to look at the `.payload` property all over the place, unless you can think of some other stuff we might want to return in the context? If it's just going to be this, I think I kind of prefer the header technique to keep things cleaner.

2019-10-04 18:53 UTC, iameli commented on packages/api/src/store/postgres-store.js
> +        [`${prefix}%`, `${prefix}/${cursor}`, `${limit}`],
I think the slash between prefix and cursor isn't necessary here, prefix should already include the slash

2019-10-07 17:49 UTC, ya7ya commented on packages/api/src/controllers/stream.js
> +  res.json({ payload: output, context })
ah , this is much cleaner 👏 , done 👍

2019-10-07 18:21 UTC, ya7ya commented on packages/api/src/controllers/stream.js
> +    context.cursor = output[output.length - 1].id
so I moved the logic to the store level and followed the cloudflare way of of returning a data array and a cursor, the only difference is the they call the data array `keys` which is specific to KV , but I thought it might be confusing so I call it `data`
```js
    return { data: ret, cursor: <cursor_id> } // how it's currently implemented
    return { keys: [], cursor: <cursor_id> } // cloudflare KV
```

2019-10-07 18:34 UTC, ya7ya commented on packages/api/src/controllers/stream.js
> +  const output = await req.store.list(`stream/`, cursor, limit)
well. it's not that it'd be cleaner, but for this case the code handles the `undefined` vars, and has store specific defaults for `postgres` and `level` stores. 

putting these options in an object means we'd have to add some default option merging statement right in the next step. currently it's done at function definition 

```js
async *listStream(prefix = '', cursor, limit = DEFAULT_LIMIT) {
  // no if (!opts.limit) opts.limit = DEFAULT_LIMIT required here
  // .....
}
```

2019-10-08 03:34 UTC, iameli requested changes
Looking good! Let's just add a test that looks at the `Link` header in the response and uses that information to request the next page of results; that'll be what we want to do in the production case. Good to go after that!

2019-10-08 03:34 UTC, iameli commented on packages/api/src/store/postgres-store.js
> +    return { data: data, cursor: data[data.length - 1].id }
I suspect this will break for empty returns (`cannot read property id of undefined`) — let's add a test that checks that case, too!

2019-10-08 10:36 UTC, ya7ya commented on packages/api/src/store/postgres-store.js
> +    return { data: data, cursor: data[data.length - 1].id }
done 👍

2019-10-08 20:11 UTC, iameli requested changes
tiny change

2019-10-08 20:11 UTC, iameli commented on packages/api/src/controllers/stream.js
> +    } catch (e) {
Need to handle this error somehow... or just remove the try/catch and let the global error handler handle it.

2019-10-08 20:27 UTC, ya7ya commented on packages/api/src/controllers/stream.js
> +    } catch (e) {
i forgot we handle uncaught errors with a global handler. I'll remove the try/catch then 👍

2019-10-08 20:39 UTC, iameli approved these changes
sweet! merging when CI passes

2019-10-09 08:58 UTC, merged