initial google auth commit: not ready for review
livepeer/livepeer-monorepo pull request #477
Opened 2019-09-30 20:28 UTC by angyangie

**What does this pull request do? Explain your changes. (required)**

Adding google auth to LivepeerJS. More details here: https://github.com/livepeer/livepeerjs/issues/458#event-2655489324

**Specific updates (required)**

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2019-09-30 20:28 UTC, angyangie commented on packages/api/src/index.js
> +  const app = express() // top level app! middleware for entire application
will remove comment in later version

2019-09-30 20:28 UTC, angyangie commented on packages/api/src/middleware/health-check.js
> +  res.sendFile(path.join(__dirname + '/index.html'))
test route here until we place it somewhere

2019-09-30 20:30 UTC, angyangie commented on packages/api/src/middleware/index.html
> +      const { OAuth2Client } = require('google-auth-library')
This doesn't work ... need to figure out way of adding this JS somewhere. Didn't seem to work when I added it in `health-check.js`, inside the `router.get('/',` file. Would love pointers on how to think about where to place this code so it executes correctly!

Good news is ... we do get correct info logged out on lines 26 - 29 in this file

2019-09-30 20:45 UTC, iameli commented on packages/api/src/middleware/index.html
> +      const { OAuth2Client } = require('google-auth-library')
I think everything up to this line will run on the client, and the stuff after will run on the server in some manner of auth middleware - we can take a look in a sec!

2019-10-03 05:29 UTC, iameli requested changes
Solid start! Let's talk about tests for this tomorrow

2019-10-03 05:29 UTC, iameli commented on packages/api/src/controllers/stream.js
> +app.get(
Can probably take this out now that we can test against `/api/streams` above

2019-10-03 05:29 UTC, iameli commented on packages/api/src/index.js
> +  const app = express() // top level app! middleware for entire application
👍

2019-10-03 05:29 UTC, iameli commented on packages/api/src/index.js
> +    req.trustedDomain = trustedDomain
Hmmm, we're going to have to keep doing stuff like this... maybe let's put the whole config in here `req.config = params` and then we'll have access to whatever CLI parameters we'd need in a controller, including this one.

2019-10-03 05:29 UTC, iameli commented on packages/api/src/middleware/auth.js
> +            errors: ['not livepeer.org email address'],
Should fill this in from `req.trustedDomain`

2019-10-03 05:29 UTC, iameli commented on packages/api/src/middleware/auth.js
> +  var lpToken = req.headers.lptoken
Not sure I follow this logic. I think we want to keep everything in `authorization`, yeah?

2019-10-03 05:29 UTC, iameli commented on packages/api/src/middleware/auth.js
> +  let clientId = req.clientId
I think most of these can be `const`, `let` is only necessary if you're going to change what `clientId` points to later

2019-10-03 05:29 UTC, iameli commented on packages/api/src/middleware/auth.js
> +  let { OAuth2Client } = require('google-auth-library')
This should just be `import { OAuth2Client } from 'google-auth-library` at the top of the file

2019-10-03 05:29 UTC, iameli commented on packages/api/src/middleware/auth.js
> +  let ticket = await client.verifyIdToken({
So presumably this is the line that'll fail if a hacker is trying to slip in with an invalid token. Probably we should `catch` that error and send a `403` back, yeah? This'll be a good unit test case.

2019-10-03 05:29 UTC, iameli commented on packages/api/src/middleware/auth.js
> +    user = await req.store.get(`user/${payload.sub}`)
We can skip a step here - `req.store.create` returns the created document, so you can just do `user = await req.store.create({` up on line 99.

2019-10-03 16:35 UTC, angyangie commented on packages/api/src/index.js
> +    req.trustedDomain = trustedDomain
good idea! This? I'll do that
```javascript
req.config = {
      store: store,
      trustedDomain: trustedDomain,
      clientId: clientId,
    }
```

2019-10-03 16:40 UTC, angyangie commented on packages/api/src/middleware/auth.js
> +            errors: ['not livepeer.org email address'],
Good call. Should we specify somewhere that `trustedDomain` is required for `admin` routes? Otherwise, if `req.config.trustedDomain` is empty, this will always result in an error `user.domain === req.config.trustedDomain`. Alternatively, we can add a check for `req.config.trustedDomain != null` prior to the if else statement.

2019-10-03 16:42 UTC, angyangie commented on packages/api/src/middleware/auth.js
> +  let clientId = req.clientId
I went a little "let" crazy. Yes, just educated myself on the distinction. Makes sense!

2019-10-03 16:51 UTC, angyangie commented on packages/api/src/middleware/auth.js
> +  let ticket = await client.verifyIdToken({
Yes, that makes sense. I'll wrap this in a try/catch statement and return a 403 + `return res.json({ errors: ['invalid oauth token'] })`

2019-10-04 18:54 UTC, iameli commented on packages/api/src/index.js
> +    req.trustedDomain = trustedDomain
I was thinking that we could put the whole `params` variable in there, which would have everything that we defined in the `makeApp` function there

2019-10-04 18:55 UTC, iameli commented on packages/api/src/middleware/auth.js
> +            errors: ['not livepeer.org email address'],
I'm cool with it being required for now, we're the only real users of this thing. In the future we could add an option to disable auth entirely or some such.

2019-10-04 20:42 UTC, angyangie commented on packages/api/src/index.js
> +    req.trustedDomain = trustedDomain
including all the kubeApi variables?

2019-10-04 22:44 UTC, angyangie commented on packages/api/src/middleware/auth.js
> +    user = await req.store.get(`user/${payload.sub}`)
it doesn't seem like this is the case for some reason 🤔

2019-10-04 22:46 UTC, angyangie commented on packages/api/src/middleware/auth.js
> +  var lpToken = req.headers.lptoken
hmm we have authorization set to have a Bearer token in `test-helpers.js`, `authorization: `Bearer ${this.apiKey}`. Do we want to change that to only hold our `lptoken`?

2019-10-08 20:36 UTC, iameli approved these changes
Looking solid, just a few things I don't yet follow

2019-10-08 20:36 UTC, iameli commented on packages/api/package.json
> +    "dev:server": "nodemon -w src -x node -r esm src/cli.js --trusted-domain=livepeer.org --client-id=211814034878-r7iugl9pa9fo2shd2pvmmadjatd5o4af.apps.googleusercontent.com",
Now that we have the `.env` file, all of this can be added there in the form `LIVEPEER_TRUSTED_DOMAIN` et al.

2019-10-08 20:36 UTC, iameli commented on packages/api/src/index.js
> +  const app = express() // top level app! middleware for entire application
👋

2019-10-08 20:36 UTC, iameli commented on packages/api/src/middleware/auth.js
> +      return next()
Hmm, I don't think this accomplishes the "admins can look at everything" case. This seems to grant full access to all `authMiddleware({})` endpoints when the user provides just nonsense in the `Authorization` header:

```javascript
fetch("/stream/secret-stream-id", {
  headers: {
    authorization: "nonsense"
  }
})
```

^^ Pretty sure I just hacked my way into that stream.

2019-10-08 20:36 UTC, iameli commented on packages/api/src/middleware/auth.js
> +        res.status(403)
Code coverage says these two lines aren't hit, and this seems like a pretty important test case - this would be when a user makes a request to an admin-secured endpoint with a totally nonsense JWT.

2019-10-08 20:36 UTC, iameli commented on packages/api/src/middleware/auth.js
> +  if (googleAuthToken != 'null') {
This might work but isn't a very idiomatic check - I think you could just do`if (googleAuthToken) {` to check for truthiness here.

But I still don't follow this logic - if `req.headers.authorization` is null, surely we don't need to move forward with validating a token or creating a user? They haven't provided us with any credentials.

2019-10-08 21:47 UTC, angyangie commented on packages/api/package.json
> +    "dev:server": "nodemon -w src -x node -r esm src/cli.js --trusted-domain=livepeer.org --client-id=211814034878-r7iugl9pa9fo2shd2pvmmadjatd5o4af.apps.googleusercontent.com",
Cool, definitely can do that. Didn't understand the `.env` file before. Is this the best way of calling/setting the variables?
```javascript
app.use((req, res, next) => {
    req.store = store
    params.clientId = process.env.CLIENT_ID
    params.trustedDomain = process.env.TRUSTED_DOMAIN
    req.config = params
    next()
  })
```

2019-10-09 00:20 UTC, iameli commented on packages/api/package.json
> +    "dev:server": "nodemon -w src -x node -r esm src/cli.js --trusted-domain=livepeer.org --client-id=211814034878-r7iugl9pa9fo2shd2pvmmadjatd5o4af.apps.googleusercontent.com",
Nah, you don't even have to do that — [we're using a yargs feature to automatically populate command-line parameters from the environment.](https://yargs.js.org/docs/#api-envprefix). So adding

```
LP_TRUSTED_DOMAIN=livepeer.org
```

has exactly the same effect as running the server with
```
--trusted-domain=livepeer.org
```

2019-10-09 00:20 UTC, iameli commented on packages/api/package.json
> +    "dev:server": "nodemon -w src -x node -r esm src/cli.js --trusted-domain=livepeer.org --client-id=211814034878-r7iugl9pa9fo2shd2pvmmadjatd5o4af.apps.googleusercontent.com",
Which is to say you can just move that bit from `package.json` to `.env` - nothing else has to change

2019-10-09 14:30 UTC, angyangie commented on packages/api/package.json
> +    "dev:server": "nodemon -w src -x node -r esm src/cli.js --trusted-domain=livepeer.org --client-id=211814034878-r7iugl9pa9fo2shd2pvmmadjatd5o4af.apps.googleusercontent.com",
Thank you for the link and explanation! I see how it works now. Fun JS/Yargs magic 🎉

2019-10-09 15:28 UTC, angyangie commented on packages/api/src/middleware/auth.js
> +      return next()
Not good. I will fix this!

2019-10-09 16:01 UTC, angyangie commented on packages/api/src/middleware/auth.js
> +  if (googleAuthToken != 'null') {
I see where the confusion here on my end came from. I had my prior HTML page not sending `req.headers.authorization` every time, only if on the login page. In that scenario, we would not always have the authorization token - it would only have it in the `/login` page when the user logged in.

We're providing the authorization header on every request we're sending on the front-end now. You're right that we don't need to do much other than return "null" if header isn't there!

2019-10-10 03:01 UTC, iameli requested changes
Just minor changes to the auth logic.

I'm getting this error trying to log in using Brave, but it works with Firefox:

![image](https://user-images.githubusercontent.com/257909/66535768-89a60700-eacf-11e9-8c59-5884143201cd.png)

Happy to take a look at tomorrow!

2019-10-10 03:01 UTC, iameli commented on packages/api-frontend/pages/login.tsx
> +  // return (
This can go away

2019-10-10 03:01 UTC, iameli commented on packages/api/src/middleware/auth.js
> +    } else if (!req.headers.authorization.startsWith('Bearer')) {
This will throw an error if there's no `authorization` header at all, we could do something like

```
} else if (req.headers.authorization && !req.headers.authorization.startsWith('Bearer')) {
```

2019-10-10 03:01 UTC, iameli commented on packages/api/src/middleware/auth.js
> +      const user = await getUser(req, res, next)
This should probably get a `try{}` similarly to the previous block or we'll error out of this function and send a `500` when we hit this error case: https://github.com/livepeer/livepeerjs/pull/477/files#diff-4c61da62170e37facb95e23c25f8c602R105

2019-10-10 16:14 UTC, angyangie commented on packages/api/src/middleware/auth.js
> +    } else if (!req.headers.authorization.startsWith('Bearer')) {
That's righttt

2019-10-10 16:27 UTC, angyangie commented on packages/api/src/middleware/auth.js
> +      const user = await getUser(req, res, next)
That's right. We want to return a 403 here. I'll add it. I hadn't thought of the hacker scenario you mentioned previously ... that's the only scenario in which someone would have a token not starting with "Bearer" who wasn't logged into Google.

2019-10-10 20:57 UTC, iameli approved these changes

2019-10-10 20:57 UTC, iameli commented
LGTM!

2019-10-10 21:00 UTC, merged