Adding proper handling to incoming width/height 0 from wowza templates
livepeer/livepeer-monorepo pull request #486
Opened 2019-10-11 15:33 UTC by angyangie

**What does this pull request do? Explain your changes. (required)**

Adding a 16/9 or 9/16 multiplier to any height or width coming in as 0 from incoming enabled wowza rendition templates. 

**How did you test each of these updates (required)**
- Added tests to output 4 correct rendition templates for various encodings coming in with heights / widths = 0

**Does this pull request close any open issues?**
https://github.com/livepeer/livepeerjs/issues/472

**Checklist:**
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2019-10-11 15:34 UTC, angyangie commented on packages/api/src/controllers/wowza-hydrate.test-data.json
> -      "templatesInUse": "${SourceStreamName}.xml,transrate.xml",
@iameli I removed this so we could test the `'no template found from templatesInUse'` error scenario, but am not sure if this is the default coming in with Wowza. If it is, I can add it back and remove the extra test! All in an effort to get closer to 100% test coverage for this file.

2019-10-11 15:37 UTC, angyangie commented on packages/api/src/controllers/wowza-hydrate.test.js
> +      width_height_test_720p:
Interesting to note here @iameli ... if a 720p rendition template comes in, the `P720p60fps16x9` rendition will always get chosen. The `P720p30fps16x9` will never be chosen, given that we're selecting based on `if (thisDiff < diff) {` .... diff will always be 0 once we get to this line after selecting `P720p60fps16x9`. Do we see this as a problem?

2019-10-11 23:06 UTC, iameli requested changes
Looks solid, one test to tweak.

2019-10-11 23:06 UTC, iameli commented on packages/api/src/controllers/wowza-hydrate.test-data.json
> -      "templatesInUse": "${SourceStreamName}.xml,transrate.xml",
Easy enough to generate a version with `transrate` and a version without — 
```javascript
const stream = require('./wowza-hydrate.test-data.json');
const streamWithTransrate = JSON.parse(JSON.stringify(stream)); // "deep copy" but I'm lazy
streamWithTransrate.wowza.transcoderAppConfig.templatesInUse = "${SourceStreamName}.xml,transrate.xml"
```

Then we can have test cases both `${SourceStreamName}.xml` and the fallback!

2019-10-11 23:06 UTC, iameli commented on packages/api/src/controllers/wowza-hydrate.test.js
> +      width_height_test_720p:
Oh hmmmmmmmm good point. FPS is tricky, 'cause I think Wowza just does the same FPS as the input stream but our presets require us to pick ahead of time. Wondering if for now we should just do 30fps for maximum compatibility...

2019-10-15 16:14 UTC, angyangie commented on packages/api/src/controllers/wowza-hydrate.test-data.json
> -      "templatesInUse": "${SourceStreamName}.xml,transrate.xml",
Good idea! Actually, just figured out I don't need to do that. I'm already changing the stream name for that test `stream.name = 'fake_name'`, so no reason it should find a template name even if `transrate.xml` is included. Thank you Eli

2019-10-15 16:26 UTC, angyangie commented on packages/api/src/controllers/wowza-hydrate.test.js
> +      width_height_test_720p:
That sounds fine to me. Would that mean removing `P720p60fps16x9` from the `VIDEO_PROFILES`?

2019-10-17 04:13 UTC, iameli requested changes
looks good, minor fixes

2019-10-17 04:13 UTC, iameli commented on packages/api/src/controllers/wowza-hydrate.test-data.json
> +      "templatesInUse": "${SourceStreamName}.xml, transrate.xml",
I'm nervous about this space right here, I don't think Wowza includes that

2019-10-17 04:13 UTC, iameli commented on packages/api/src/controllers/wowza-hydrate.test.js
> +      width_height_test_720p:
Something like that... I'll open a ticket, doesn't need to block this PR

2019-10-17 04:13 UTC, iameli commented on packages/api/src/controllers/wowza-hydrate.test.js
> +    try {
This will return a false positive in the event that `wowzaHydrate` _doesn't_ throw an error - the `catch` block will never be hit and the test will complete without incident. Easy enough fix:

```javascript
    let message;
    try {
      const newStream = wowzaHydrate({ ...stream })
    } catch (e) {
      message = e.message;
    }
    expect(e.message).toEqual('no template found from templatesInUse')
```

2019-10-28 19:16 UTC, angyangie commented on packages/api/src/controllers/wowza-hydrate.test.js
> +    try {
Good catch!

2019-10-29 18:51 UTC, iameli approved these changes

2019-10-29 18:52 UTC, iameli commented
LGTM!

2019-10-29 19:14 UTC, merged