adding swagger schema to api
livepeer/livepeer-monorepo pull request #494
Opened 2019-10-28 17:52 UTC by angyangie

**What does this pull request do? Explain your changes. (required)**
Adding swagger schema to LivepeerJS `/stream` endpoint.

**Specific updates (required)**
- 
- 
- 

**How did you test each of these updates (required)**
- Added tests
- Ran livepeerjs locally

**Does this pull request close any open issues?**

**Checklist:**
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2019-10-31 10:28 UTC, ya7ya reviewed
great start :+1:

2019-10-31 10:28 UTC, ya7ya commented on packages/api/src/schema/schema.yaml
>    /ingress/{id}:
nice work :+1: , `/ingress/{id}` endpoint doesn't have a title in the generated docs, this can be solved by adding `description` or `summary` field

2019-10-31 14:47 UTC, angyangie commented on packages/api/src/schema/schema.yaml
>    /ingress/{id}:
Thank you @ya7ya ! Good feedback. Since that's an unused endpoint though, I think we can actually delete that one altogether. @iameli ?

2019-11-04 02:37 UTC, iameli requested changes
Sweet! Just minor changes.

Let's make sure one or both of us runs through the Wowza workflow after this rolls out to staging, that's the only real critical path for this work at the moment

2019-11-04 02:37 UTC, iameli commented on packages/api/src/schema/schema.yaml
>    /ingress/{id}:
Yeah, all of the ingress resources can be removed from documentation, their controller doesn't even exist anymore

2019-11-04 02:37 UTC, iameli commented on packages/api/src/middleware/validators.js
> +        errors: validate.errors.map(message => message),
This is fine, I like getting more error detail back from the validator, but let's do `message => JSON.stringify(message)` so we're at least confident that the field is a string.

2019-11-04 21:51 UTC, iameli approved these changes
LGTM!

We can test this in staging during our meeting tomorrow.

2019-11-04 22:12 UTC, merged