Ar/add user id to stream object
livepeer/livepeer-monorepo pull request #496
Opened 2019-10-29 20:11 UTC by angyangie

**What does this pull request do? Explain your changes. (required)**
Adds a `userId` field to the stream object, and populates it when user is logged through gmail. 

**How did you test each of these updates (required)**
Added tests + local testing

**Does this pull request close any open issues?**
https://github.com/livepeer/livepeerjs/issues/488

**Checklist:**
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2019-11-04 02:49 UTC, iameli requested changes
This looks solid, but I think we should go one step further here - API token requests should also create a user the same way that administrative users create a user. That way we can start to set up a record of which API tokens are associated with which users, which users are currently streaming, that sort of thing.

Basically the process will be 

1. After you've retrieved/created an API token, check to see if that API token has a userId field.
  * If so, retrieve it.
  * If not, create an empty user and modify the API token record to include the userId.
2. Populate `req.user` with the appropriate user record.

2019-11-04 16:50 UTC, angyangie commented
@iameli sounds like a great addition. We have two options:
1. Make the `id` field on `user` be the same as the `id` on the token object
2. Autogenerate an `id` on `user` object, and copy to additional `userId` field on token object

Which did you have in mind?

2019-11-04 21:57 UTC, iameli commented
@angyangie 2 - we need the ability to revoke access tokens while leaving the user object intact.

2019-11-04 21:58 UTC, iameli commented on packages/api/src/middleware/auth.js
> +        const user = await getUserWithGoogleAUth(req, res, next)
`AUth` typo

2019-11-04 21:59 UTC, iameli requested changes

2019-11-04 21:59 UTC, iameli commented on packages/api/src/middleware/auth.js
> +  await req.store.create({
Gots to assign a new UUID here and save that onto the API token, per discussion on the ticket

2019-11-06 20:43 UTC, iameli requested changes
Looks cool, just suggested a tweak to the workflow so avoid the empty-string-user case

2019-11-06 20:43 UTC, iameli commented on packages/api/src/controllers/stream.test.js
> +  delete mockStream.id
Same deal here as on the other PR - this will delete those fields for every other unit test that runs. (Possibly. Jest's actual execution patterns are kinda murky.) Good to clone the object before modifying it.

2019-11-06 20:43 UTC, iameli commented on packages/api/src/controllers/stream.test.js
> +        userId: '',
I think this should just be omitted? I sure hope we don't end up with any empty-string userIds in the database.

2019-11-06 20:43 UTC, iameli commented on packages/api/src/middleware/auth.js
> +    await req.store.create({
I don't think this intermediate step is necessary - we can just create the `user` prior to creating the `apitoken` and save ourselves the trouble of having this in-between state with the `apitoken` has a empty-string userId. This'll be especially important as we move to Cloudflare Worker KV where we won't always have strong read-after-write consistency; this empty record could stick around for longer than we'd prefer.

2019-11-06 20:43 UTC, iameli commented on packages/api/src/middleware/auth.js
> +        if (tokenObject.userId == '') {
As above, can cut out this step by creating the user first. Though we will still need replace logic here for when it's an old `tokenObject` that doesn't have a `userId` quite yet.

2019-11-08 15:17 UTC, angyangie commented on packages/api/src/controllers/stream.test.js
> +  delete mockStream.id
Sure thing! Since that's the stream we're using for all tests but one, I'll just clone it for the `should not accept additional properties for creating a stream` test. `mockStream` should be the standard for all tests. I'll change the name to `postMockStream` to perhaps convey the idea better

2019-11-08 15:17 UTC, angyangie commented on packages/api/src/controllers/stream.test.js
> +        userId: '',
Sure thing. I hope not!

2019-11-08 15:29 UTC, angyangie commented on packages/api/src/middleware/auth.js
> +    await req.store.create({
Hmm perhaps I interpreted this differently: 
```
We need the ability to revoke access tokens while leaving the user object intact.
```
I assumed "revoke" meant we would delete the access token altogether. So theoretically, we'd have a user in our DB with no API Token. If that's not the case, then the logic here can be simpler. I had it setup with user being created first in the previous local interation of this - I'll set it up that way again :)

2019-11-13 23:26 UTC, iameli commented on packages/api/src/middleware/auth.js
> +    await req.store.create({
Right — we don't yet have the ability to issue new API tokens for a given user but once we do, your description will line up a bit better.

2019-11-13 23:36 UTC, iameli approved these changes
LGTM after one small change

2019-11-13 23:36 UTC, iameli commented on packages/api/src/middleware/auth.js
> +    if (tokenObject && tokenObject.userId == '') {
I think this'll fail for most of the existing database — they don't have userIds at all, so those fields would be `undefined`. This check could just be `if (tokenObject && !tokenObject.userId) {` — that'll catch both empty strings and undefined/null values.

2019-11-14 20:56 UTC, angyangie commented on packages/api/src/middleware/auth.js
> +    if (tokenObject && tokenObject.userId == '') {
ohhh right. good catch!

2019-11-14 21:42 UTC, merged