Match incoming FPS and aspect ratio (WIP)
livepeer/livepeer-monorepo pull request #498
Opened 2019-11-01 21:48 UTC by angyangie

**What does this pull request do? Explain your changes. (required)**
- We need to be able to match incoming stream fps to an existing profile in `VIDEO_PROFILES` in `packages/sdk/src/index.js`
- We should be able to derive aspect ratio from incoming stream height and width.

**Specific updates (required)**
- As a temporary solution, add 25fps profiles to `VIDEO_PROFILES`, mirroring profiles that exist in `go-livepeer`: https://github.com/livepeer/go-livepeer/pull/1148 (see comments in link for more long-term solutions).
- Add `sourceInfo` object to the request body coming from livepeer-wowza, to be accessed as such:  `req.body.wowza.sourceInfo`, with the following fields:
```json
"sourceInfo": {
   "width": 1920,
   "height": 1920,
   "fps": 25
}
```
- In addition to using height / width, also use incoming `sourceInfo.fps` to select correct present.
- When `width` or `height` in `transcoderTemplateAppConfig` template comes back as zero, use aspect ratio to fill in correct missing number.

**How did you test each of these updates (required)**
Test file

**Does this pull request close any open issues?**
https://github.com/livepeer/livepeerjs/issues/497

**Checklist:**
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2019-11-06 20:29 UTC, iameli requested changes
Solid, a few changes.

2019-11-06 20:29 UTC, iameli commented on packages/api/src/schema/schema.yaml
> +              type: object
I think we should fully define the schema here; the other properties in here are Wowza-internal blobs, so we didn't do a strict schema for forwards-compatibility, but the contents of this field are entirely up to us so we may as well define the fields explicitly.

2019-11-06 20:29 UTC, iameli commented on packages/api/src/controllers/wowza-hydrate.test-data.json
> +      "sourceInfo": {
Let's match the rest of the Camcast settings for this second test case - should be 1080p25.

2019-11-06 20:29 UTC, iameli commented on packages/api/src/controllers/wowza-hydrate.test.js
> +    stream.name = 'width_height_test'
I get nervous about directly modifying the stream object like this, as that data sticks around between tests and could theoretically cause tests to pass or fail if they're reordered. `const newStream = JSON.parse(JSON.stringify(stream))` is a hacky-but-totally-fine-for-a-test way to do a deep clone prior to doing anything with it. Or if you wanna do it the "right" way...

```javascript
const newStream = {
  ...stream,
  name: "width_height_test",
  wowza: {
    ...stream.wowza,
    sourceInfo: {
      ...stream.wowza.sourceInfo
      fps: 50
    }
  }
}
```

But that's not so fun 😄

2019-11-06 21:28 UTC, angyangie commented on packages/api/src/schema/schema.yaml
> +              type: object
good point - I'll define it!

2019-11-08 01:34 UTC, iameli commented
@angyangie I just pushed a tiny change to master to ignore this field so that it doesn't break the version of LivepeerWowza I'm releasing just now. https://github.com/livepeer/livepeerjs/commit/dee9a37fda2e1a9bb522de2291bdbb635179deb5

Let me know when this is ready and I'll switch over to the actual logic :+1:

2019-11-11 02:08 UTC, iameli approved these changes
Looks great! Made one tiny change so I can get it merged in advance of demo tomorrow morn: https://github.com/livepeer/livepeerjs/pull/498/commits/994bb7b4fc02798ac611afafa83d7af64c0e2450

2019-11-11 02:08 UTC, iameli commented on packages/api/src/controllers/wowza-hydrate.js
> +  const aspectRatio = sourceInfo.width / sourceInfo.height
Let's add `minValue: 1` to the schema for this just to avoid the possibility of a division-by-zero error.

2019-11-11 02:08 UTC, iameli commented on packages/api/src/controllers/wowza-hydrate.js
> +    // TODO: do we need to validate whether or not the incoming height/width fit the aspect ratio?
I don't think so — if Wowza lies to us about the dimensions of the video that's on them.

2019-11-11 02:56 UTC, merged

2019-11-11 15:30 UTC, angyangie commented on packages/api/src/controllers/wowza-hydrate.js
> +  const aspectRatio = sourceInfo.width / sourceInfo.height
Thank you!!!