AR/Adding CloudFlare DB to API (WIP - still needs tests)
livepeer/livepeer-monorepo pull request #504
Opened 2019-11-11 21:23 UTC by angyangie

**What does this pull request do? Explain your changes. (required)**
Alongside LevelStore and PostgresStore we should have a CloudflareStore that implements the same interface.

**Specific updates (required)**
https://github.com/livepeer/livepeerjs/issues/453

**How did you test each of these updates (required)**
Locall & future tests

**Does this pull request close any open issues?**
https://github.com/livepeer/livepeerjs/issues/453

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2019-11-11 21:45 UTC, angyangie commented on packages/api/src/store/cloudflare-store.js
> +// const CONNECT_TIMEOUT = 5000
Not sure if we need to implement any kind of timeout here ... so left this as a reminder to ask

2019-11-13 21:53 UTC, angyangie commented on packages/api/src/controllers/stream.test.js
> +jest.setTimeout(50000)
We can remove this once the CloudFlare rate limit is increased. For now, tests will take a long time to run!

2019-11-13 21:54 UTC, angyangie commented on packages/api/src/controllers/stream.test.js
> -    it('should get a working next Link', async () => {
Combined this test with the last one ... esp with CloudFlare rate limits, didn't see a point to having two of them testing stream object lengths

2019-11-13 21:54 UTC, angyangie commented on packages/api/src/controllers/stream.test.js
> +      for (let i = 0; i < 3; i += 1) {
Only need to test 403s a couple of times. 10 seemed like a lot (again, keeping in mind these rate limits)

2019-11-13 21:54 UTC, angyangie commented on packages/api/src/middleware/hardcoded-nodes.js
> +    console.error('Error parsing LP_BROADCASTERS and LP_ORCHESTRATORS')
Annoying log ... took it out

2019-11-13 21:55 UTC, angyangie commented on packages/api/src/store/cloudflare-store.js
> +      await sleep(3000)
We can remove this when rate limit is increased, along with other sleeps

2019-11-13 22:16 UTC, angyangie commented
Still need to figure out how to give circleci default values for the `cloudflare namespace`, `account id`, and `authorization key` so the tests actually pass 🤔 🤔

2019-11-14 00:27 UTC, iameli requested changes
Cool! Just a few pieces of polish.

2019-11-14 00:27 UTC, iameli commented on packages/api/src/controllers/stream.test.js
> +jest.setTimeout(50000)
I think this is fine for the tests... we want it to work with other folks' Cloudflare accounts out-of-the-box too. Still a good idea for me to open that ticket though, I'll do that now

2019-11-14 00:27 UTC, iameli commented on packages/api/src/controllers/stream.test.js
> -    it('should get a working next Link', async () => {
Cool, looks fine to me

2019-11-14 00:27 UTC, iameli commented on packages/api/src/controllers/stream.test.js
> +      for (let i = 0; i < 3; i += 1) {
Sure.

2019-11-14 00:27 UTC, iameli commented on packages/api/src/middleware/hardcoded-nodes.js
> +    console.error('Error parsing LP_BROADCASTERS and LP_ORCHESTRATORS')
:+1:

2019-11-14 00:27 UTC, iameli commented on packages/api/src/store/cloudflare-store.js
> +const querystring = require('querystring')
Can also be spelled `import querystring from 'querystring'` for consistency

2019-11-14 00:27 UTC, iameli commented on packages/api/src/store/cloudflare-store.js
> +const cloudflareUrl = 'https://api.cloudflare.com/client/v4/accounts'
Kinda prefer `CAPITAL_CASE` for constants like this... but idc very much tbh

2019-11-14 00:27 UTC, iameli commented on packages/api/src/store/cloudflare-store.js
> +    for (i = 0; i < respData.result.length; i++) {
`let` is preferable to `var` here and can be defined inline: `for (let i = 0; i < respData.result.length; i++) {`

2019-11-14 00:27 UTC, iameli commented on packages/api/src/store/cloudflare-store.js
> +    const respData = await cloudFlareFetch(reqUrl, data, 'PUT', 0) // can we not declare?
Sure! `await cloudFlareFetch(reqUrl, data, 'PUT', 0)`

2019-11-14 00:27 UTC, iameli commented on packages/api/src/store/cloudflare-store.js
> +async function cloudFlareFetch(reqUrl, data, method, retries) {
I like this function and its parameters but I think the `null`s for body make it a little awkward to call: 

```
await cloudFlareFetch(reqUrl, null, 'DELETE', 0)
```

Perhaps we could give it the same `fetch(url, opts)` signature that `fetch` itself uses? So that could look like uhhh

```javascript
async function cloudFlareFetch(reqUrl, {method = 'GET', retries = 0, data = null} = {}) {
```

And then it could be called like

```javascript
const respData = await cloudFlareFetch(reqUrl, {
  data: data,
  method: 'PUT',
  retries: 0
)
```

Or a simple GET could be:
```javascript
await cloudFlareFetch(reqUrl)
```

Oh! And Cloudflare doesn't capitalize the F, so probably `cloudflareFetch`.

2019-11-14 00:27 UTC, iameli commented on packages/api/src/store/cloudflare-store.js
> +  if (res.status != 200) {
Confirming - it's a 200 even for `POST`s and `DELETE`s? That's unusual.

2019-11-14 00:27 UTC, iameli commented on packages/api/src/store/cloudflare-store.js
> +      await sleep(3000)
Hmmm yeah, trying to figure out what to do here - these `sleep`s and retries aren't going to help much if we're under any kind of load and making thousands of requests — the requests will just loop and keep exceeding the limit. So that'd call for a rate-limiting system with a queue and rules about the number of concurrent requests. On the other hand, all of that would be just to use this thing outside of the Worker, and we really aren't designing this to work outside of the Worker. So I kinda wanna say let's ship this if the tests are consistent and worry about performance after we're actually deploying to the worker.

2019-11-14 16:35 UTC, angyangie commented on packages/api/src/controllers/stream.test.js
> +jest.setTimeout(50000)
Thank you for filing that ticket. Cool, we'll just leave the timeout regardless

2019-11-14 16:35 UTC, angyangie commented on packages/api/src/store/cloudflare-store.js
> +const cloudflareUrl = 'https://api.cloudflare.com/client/v4/accounts'
hahaha love it. I don't either, so I'll just change to all capitals :)

2019-11-14 16:35 UTC, angyangie commented on packages/api/src/store/cloudflare-store.js
> +    for (i = 0; i < respData.result.length; i++) {
Thank you! Oh javascript

2019-11-14 16:35 UTC, angyangie commented on packages/api/src/store/cloudflare-store.js
> +    const respData = await cloudFlareFetch(reqUrl, data, 'PUT', 0) // can we not declare?
🙇‍♀🙇‍♀🙇‍♀

2019-11-14 16:35 UTC, angyangie commented on packages/api/src/store/cloudflare-store.js
> +  if (res.status != 200) {
Good point, I'll confirm and adjust if needed

2019-11-14 16:35 UTC, angyangie commented on packages/api/src/store/cloudflare-store.js
> +      await sleep(3000)
Agreed. If I had to streamline tests and triple the default jest timeout for tests to pass, no way this would work work under any kind of load. Why would this not be a problem inside the worker? Because it'll handle the load appropriately?  I'm fine shipping it since tests are consistent

2019-11-14 16:35 UTC, angyangie commented on packages/api/src/store/cloudflare-store.js
> +async function cloudFlareFetch(reqUrl, data, method, retries) {
Love the edits ... thanks for making my code cleaner. I'll change

2019-11-14 16:46 UTC, j0sh commented on packages/api/src/controllers/stream.test.js
> +jest.setTimeout(50000)
Normally for these types of tests, mocking is used to simulate the behavior of external resources. That way our logic can be tested (and particular failures etc injected to test specific error paths) without introducing a run-time dependency on resources that are slow/expensive/rate-limited/hard-to-access/etc.

2019-11-14 20:43 UTC, angyangie commented on packages/api/src/store/cloudflare-store.js
> +  if (res.status != 200) {
200s from `POST`s and `DELETE`s confirmed. Unusual indeed!

2019-11-18 20:26 UTC, iameli commented on packages/api/src/controllers/stream.test.js
> +jest.setTimeout(50000)
I hear that, and there might be some value in it eventually, but I've liked so far that we've run pretty much everything as integration tests — it's caught bugs in inconsistent implementations between the two existing stores that I'm not sure we'd have seen if we were mocking everything.

2019-11-18 21:28 UTC, j0sh commented on packages/api/src/controllers/stream.test.js
> +jest.setTimeout(50000)
Sure, the stuff that directly talks to CF should still be tested separately to ensure that whatever assumptions we are making still hold.

I haven't actually reviewed any of these tests, but are we actually testing different CF behaviors, or the same CF behavior repeatedly but with a slightly different code path on our end? The latter is what would justify mocking, *in addition to* separate tests for specific behaviors we expect from CF.

2019-11-18 21:54 UTC, iameli approved these changes
LGTM!

2019-11-18 22:04 UTC, angyangie commented on packages/api/src/controllers/stream.test.js
> +jest.setTimeout(50000)
Hmmm I'm not sure what you mean @j0sh. We're testing all stores (local, postgres, CloudFlare) in `stream.test.js`. We're running that file three times using all three DB options to ensure consistent results regardless of DB chosen ( see here: https://github.com/livepeer/livepeerjs/pull/504/files#diff-43c6f412a6b721476ad29c6674d36fa6R42-R47). 

Since I'm working on another Cloudflare ticket, we can do additional testing there if necessary there: https://app.zenhub.com/workspaces/video-user-team-5dd2c75e4ee08500015994d7/issues/livepeer/livepeerjs/508

2019-11-18 22:04 UTC, merged