Adding the ability to handle passthrough custom profiles
livepeer/livepeer-monorepo pull request #515
Opened 2019-12-04 21:41 UTC by angyangie

**What does this pull request do? Explain your changes. (required)**
Adding the ability for API to handle passthrough custom profiles.

**Specific updates (required)**

- Removing presets from Wowza Hydrate
- Adding profile construction from Wowza config 

**How did you test each of these updates (required)**
- End to end test with go-livepeer changes + streaming
- Unit tests

**Does this pull request close any open issues?**
https://github.com/livepeer/go-livepeer/issues/1185 and https://github.com/livepeer/go-livepeer/issues/811

**Checklist:**
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2019-12-04 22:04 UTC, angyangie commented on packages/api/src/controllers/wowza-hydrate.test.js
> +        width: 426.66666666666663,
This sort of thing is bound to happen when width or height is zero with custom profiles ... do we care?

2019-12-05 02:26 UTC, iameli requested changes
Looks good, few changes

2019-12-05 02:26 UTC, iameli commented on packages/api/src/controllers/wowza-hydrate.test.js
> +        width: 426.66666666666663,
We should probably round it to an integer, no such thing as a two-thirds pixel.

2019-12-05 02:26 UTC, iameli commented on packages/api/src/controllers/wowza-hydrate.js
> +      bitrate: parseInt(videoBitrate),
Pretty sure the Wowza bitrates are in bytes. Ours are in kilobytes, so this should get a `Math.round(parseInt(videoBitrate)) / 1000`.

2019-12-05 02:26 UTC, iameli commented on packages/api/src/controllers/wowza-hydrate.test.js
> +        bitrate: 1300000,
Yeah, all of these should be adjusted — this would be about 1.2 gigabits per second haha

2019-12-05 17:28 UTC, j0sh commented on packages/api/src/controllers/wowza-hydrate.js
> +      bitrate: parseInt(videoBitrate),
> Ours are in kilobytes

Kilobits, so if Wowza is actually in bytes (rather than bits) then it would be `parseInt(videoBitrate)*8/1000`  (or equivalently, `parseInt(videoBitrate)/125`).

2019-12-05 18:31 UTC, angyangie commented on packages/api/src/controllers/wowza-hydrate.test.js
> +        bitrate: 1300000,
lol 🤦‍♀

2019-12-05 18:34 UTC, angyangie commented on packages/api/src/controllers/wowza-hydrate.test.js
> +        width: 426.66666666666663,
Sounds good to me!

2019-12-05 18:36 UTC, angyangie commented on packages/api/src/controllers/wowza-hydrate.js
> +      bitrate: parseInt(videoBitrate),
Thank you both! Good catch Eli

2019-12-06 18:47 UTC, iameli commented on packages/api/src/controllers/wowza-hydrate.js
> +      bitrate: parseInt(videoBitrate),
Ah, I mispoke — both of mine should have been bits, no `8` required here.

Actually I think it should be `/1024`, yeah?

2019-12-09 17:48 UTC, iameli approved these changes

2019-12-19 21:03 UTC, merged