(WIP - not for review) adding api store endpoint
livepeer/livepeer-monorepo pull request #518
Opened 2019-12-16 20:26 UTC by angyangie

**What does this pull request do? Explain your changes. (required)**

Adds the ability for an API user to specify the credentials and store into, then when they make a stream to associate it with the store such that it could be returned by the Webhook.

**Specific updates (required)**
- Adding credentials schema & endpoint

**How did you test each of these updates (required)**
Will add tests 

**Does this pull request close any open issues?**
https://github.com/livepeer/livepeerjs/issues/516

**Checklist:**
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-01-17 00:46 UTC, iameli requested changes
Solid — two meaningful changes (changing the key where we store OSes and a string --> object proposed change for `credentials`), everything else is just polish.

2020-01-17 00:46 UTC, iameli commented on packages/api/src/controllers/object-stores.js
> +  const credentials = await req.store.get(`objectstores/${req.params.id}`)
Let's do a bit more work here and validate that `req.user.id === credentials.userId` so users can only download their own objectStores.

2020-01-17 00:46 UTC, iameli commented on packages/api/src/controllers/object-stores.js
> +  const credentials = await req.store.get(`objectstores/${req.params.id}`)
And I'd say maybe this could be called `const os` so we can tell the difference between the `credentials` variable and the `credentials.credentials` sub-field

2020-01-17 00:46 UTC, iameli commented on packages/api/src/controllers/object-stores.js
> +  const resp = await req.store.list(`objectstores/`, cursor, limit)
I think for this particular object we're going to want to store OSes at `/objectstores/${userId}/${objectStoreId}`. I can't think of a good scenario to want to list them globally, but we do want users to easily be able to list their _own_ stores, which we can do with a list on `/objectstores/${userId}/`.

2020-01-17 00:46 UTC, iameli commented on packages/api/src/controllers/object-stores.js
> +    store.credentials = 'xxx'
Solid, but I like `null` here, "this field is here but you cannot see it"

2020-01-17 00:46 UTC, iameli commented on packages/api/src/controllers/object-stores.js
> +  res.json(credentials)
On this endpoint - the one used by individuals to retrieve one set of their credentials - we shouldn't send back the actual credentials. We want them to stay secure even if your account is compromised. Easy enough to accomplish with something like
```javascript
const secureOS = {...os, credentials: null}
res.json(secureOS).
```

2020-01-17 00:46 UTC, iameli commented on packages/api/src/controllers/object-stores.js
> +  let baseUrl = new URL(
This process will get repetitive fast - let's get this into a shared helper function that takes `(req, nextCursor)` and returns `next.href`

2020-01-17 00:46 UTC, iameli commented on packages/api/src/controllers/object-stores.js
> +  res.json(output)
We should do an `output.filter()` option here to clear out the `credentials` field of each of these

2020-01-17 00:46 UTC, iameli commented on packages/api/src/middleware/auth.js
> +        throw e
If we don't need to do anything else with this error, we can lose the `try{}` block entirely

2020-01-17 00:46 UTC, iameli commented on packages/api/src/middleware/auth.js
> +        const store = await req.store.get(
This is a good check - we want to make sure that the store exists if you're using it in a stream - but we should do this check in the `POST /stream` endpoint rather than here where it'll run for any potential body containing an `objectStoreId` key

2020-01-17 00:46 UTC, iameli commented on packages/api/src/schema/schema.yaml
> +        - objectStoreId
It shouldn't be required, lots of streams work just fine without an OS.

2020-01-17 00:46 UTC, iameli commented on packages/api/src/schema/schema.yaml
> +        - presets
I don't think presets should be required either - we're transitioning to `profiles` for most cases anyway.

2020-01-17 00:46 UTC, iameli commented on packages/api/src/schema/schema.yaml
> +        credentials:
Thinking this should be an object with `type`, `path`, and `credentials` fields like this here https://github.com/livepeer/go-livepeer/issues/1263

2020-01-17 00:46 UTC, iameli commented on packages/api/src/schema/schema.yaml
> +      - stream
What result does this have on the docs? Thinking maybe it should have an `objectstores` tag or something

2020-01-17 18:54 UTC, angyangie commented on packages/api/src/controllers/object-stores.js
> +  const credentials = await req.store.get(`objectstores/${req.params.id}`)
Really good point! However, in conjunction with one of your other (great) comments, if we store OS's in `/objectstores/${userId}/${objectStoreId}` ... do we still want to check for `os.userId`? If we store the object this way, the userId in the route will always be the same as the `userId` stored in the `objectStores` object itself. Which leads me to the question: do we then need to store the `userId` in the object itself? 

```javascript
await req.store.create({
      id: id,
      credentials: req.body.credentials,
      path: req.body.path,
      userId: req.user.id,
      type: req.body.type,
      kind: `objectstores/${req.user.id}`,
    })
```

2020-01-17 18:54 UTC, angyangie commented on packages/api/src/controllers/object-stores.js
> +  const resp = await req.store.list(`objectstores/`, cursor, limit)
You're right. I can't think of a scenario in which we'd want to list them globally either.

2020-01-17 18:55 UTC, angyangie commented on packages/api/src/middleware/auth.js
> +        const store = await req.store.get(
Good point ... we don't need to do this check for every endpoint

2020-01-17 18:55 UTC, angyangie commented on packages/api/src/schema/schema.yaml
> +        credentials:
What do you mean? I included it in the `objectstores` object here

2020-01-17 18:55 UTC, angyangie commented on packages/api/src/schema/schema.yaml
> +      - stream
haha woops

2020-01-18 01:36 UTC, iameli requested changes
Cool, just minor changes.

2020-01-18 01:36 UTC, iameli commented on packages/api/src/controllers/object-stores.js
> +  output = output.filter(x => x.userId == req.user.id)
`===` always. We should get a linter rule for that.

2020-01-18 01:36 UTC, iameli commented on packages/api/src/controllers/object-stores.js
> +  output.map(x => (x.credentials = null))
This'll modify the existing records, kinda bad form for a `.map()` call. I like 
```javascript
output = output.map(x => ({
  ...x,
  credentials: null 
}))
```

2020-01-18 01:36 UTC, iameli commented on packages/api/src/schema/schema.yaml
> +        credentials:
Oh, so you did. Whoops! JSON-Schema brain fart.

In that case, we should add the rest of the fields onto this — these three are all that are required for a POST, but there's also `id` and `userId` on the object itself.

2020-01-18 01:36 UTC, iameli commented on packages/api/src/controllers/stream.js
> +      console.error(e)
Erg, this is another place where we have to do the annoying pattern where we check for "NotFoundError" and continue if it's of that type but throw otherwise. Let's open a ticket to change that to returning null from `req.store.get` next week?

2020-01-20 18:06 UTC, angyangie commented on packages/api/src/controllers/stream.js
> +      console.error(e)
Yes, that would be helpful. Just created the ticket: https://github.com/livepeer/livepeerjs/issues/525

2020-01-24 07:29 UTC, iameli commented on packages/api/src/controllers/object-stores.test.js
> +      // testing right number of object stores returned when multiple created by different users
:+1:

2020-01-24 07:31 UTC, iameli requested changes
One line change 👍

2020-01-24 07:31 UTC, iameli commented on packages/api/src/controllers/stream.js
> +  const store = await req.store.get(`objectstores/${stream.objectStoreId}`)
This'll break for streams that don't have an object store. Which is, at the moment, all of them.

2020-01-24 09:16 UTC, iameli commented on packages/api/src/controllers/object-stores.js
> +      kind: `objectstores/${req.user.id}`,
So I tried to be clever with this `kind` field and it ended up being kind of silly. What do you think would be a better way to handle multiple indexes like this? One option would be to ditch the `kind` field entirely and have this thing's `id` be `objectstores/${userId}/${id}`. But I dunno.

2020-01-24 21:58 UTC, angyangie commented on packages/api/src/controllers/object-stores.js
> +      kind: `objectstores/${req.user.id}`,
We could do that. Is having an ID of `objectstores/${userId}/${id}` v. having a kind and ID more intuitive? Are we thinking of doing this only for objectstores? Or, is this important as a standard for future routes for items that might need to be nested under a userId?

2020-01-24 21:58 UTC, angyangie commented on packages/api/src/controllers/object-stores.js
> +      kind: `objectstores/${req.user.id}`,
I'll push up my changes without this one included for now, but will circle back to this once we come to consensus!

2020-01-28 18:10 UTC, iameli commented on packages/api/src/controllers/stream.js
> +  let objectStore = { type: '', path: '' }
```suggestion
  let objectStore = undefined
```

2020-01-28 18:15 UTC, iameli approved these changes

2020-01-28 18:16 UTC, merged