Removing NotFoundErrors from API
livepeer/livepeer-monorepo pull request #540
Opened 2020-01-31 18:10 UTC by angyangie

**What does this pull request do? Explain your changes. (required)**

We have a pattern of returning NotFoundError when an item isn't found in the database. As a result, the following is repeated often:

```javascript
if (e.type !== 'NotFoundError') {
        throw e
}
```

**Specific updates (required)**
We should return null from req.store.get instead of `NotFoundError`.

**Does this pull request close any open issues?**
https://github.com/livepeer/livepeerjs/issues/525

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-01-31 22:28 UTC, iameli commented
![image](https://user-images.githubusercontent.com/257909/73578962-e5591f00-4435-11ea-901f-9df43b48a4a1.png)

This indicates to me this was a good idea 😄

2020-01-31 22:39 UTC, iameli requested changes
Cool, mostly just cleanup of instances where we can remove try{} blocks entirely.

I'm thinking there might need to be some extra logic in Cloudflare and LevelDB's `update` and `delete` methods - I think in those cases we do want to throw an error if the record doesn't exist. Probably most of the time if I try and `update()` with an id that doesn't exist something has gone horribly wrong.

2020-01-31 22:39 UTC, iameli commented on packages/api/src/controllers/stream.js
> +      throw e
This and the other cases like it can have the `try/catch` removed entirely. If the only thing we're doing upon an error is throwing it up the stack, there's no difference there

2020-01-31 22:39 UTC, iameli commented on packages/api/src/middleware/auth.js
> +      throw e
same here

2020-01-31 22:39 UTC, iameli commented on packages/api/src/middleware/auth.js
> +    console.error(error)
Same - feel free to remove these `console.error()` statements generally too. There should be unhandled error logging that takes care of that above us.

2020-01-31 22:39 UTC, iameli commented on packages/api/src/store/level-store.js
> +      }
We should `throw err` here if it was an error other than a NotFoundError

2020-01-31 22:39 UTC, iameli commented on packages/api/src/store/level-store.js
> +      throw err
block can be removed

2020-01-31 22:39 UTC, iameli commented on packages/api/src/store/postgres-store.js
> -      throw new NotFoundError()
Interesting... I think we might still want these two. Calling `update()` on something that doesn't exist is still an error condition

2020-02-02 21:13 UTC, angyangie commented on packages/api/src/controllers/stream.js
> +      throw e
I didn't realize that ... thank you!

2020-02-02 21:17 UTC, angyangie commented
Thanks for the comments Eli! Working on extra logic for Cloudflare and LevelDB's update and delete methods now

2020-02-05 04:17 UTC, iameli approved these changes
One tiny change, feel free to merge after that and CI passes!

2020-02-05 04:17 UTC, iameli commented on packages/api/src/store/postgres-store.js
> -    if (res.rowCount < 1) {
Think this one should still be here.

2020-02-05 20:08 UTC, angyangie commented on packages/api/src/store/postgres-store.js
> -    if (res.rowCount < 1) {
Thanks Eli!

2020-02-05 20:08 UTC, merged