Update SDK to be compatible with Streamflow
livepeer/livepeer-monorepo pull request #557
Opened 2020-02-10 16:32 UTC by adamsoffer

**What does this pull request do? Explain your changes. (required)**
This PR updates the SDK with the latest changes introduced by streamflow.

**Specific updates (required)**
- Removes all instances of deprecated JobsManager
- Adds option to return a transaction hash from each method 
- Updates ABI files

**How did you test each of these updates (required)**
- Ran `yarn test`. All unit tests pass.
 
**Checklist:**
- [x] I have read the **CONTRIBUTING** document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-02-13 00:44 UTC, kyriediculous requested changes
We actually don't need many of these ABIs for the SDK which is why I would be in favor of extracting only the necessary ones into a seperate package and maintaining that. We _could_ set up some CI tool that rebuilds that package when there's changes to the `livepeer/protocol` repo. 

ABIs that aren't used (or most of them, I haven't checked too thorough) : Assertions, Interfaces, Mocks, inherited contracts*

_* eg. TicketBroker ABI contains all of the internal types of eg MReserve , because the encapsulating TicketBroker contract inherits it_ 

I would be in favor of just removing the unused ABIs for now and creating a seperate issue for a more robust way to keep the ABIs in sync with the protocol branch. 

cc @iameli @yondon what do you think?

2020-02-13 00:47 UTC, kyriediculous commented on packages/sdk/package.json
> -  "version": "1.0.0-streamflow-alpha.17",
Does this get changed automatically on each commit? 
Might be interesting to set up releases or per PR bumps.

2020-02-13 00:56 UTC, kyriediculous requested changes

2020-02-13 00:56 UTC, kyriediculous commented on packages/sdk/src/index.js
> +      unbondingLockId = null,
I think we shouldn't set up the default to be `null` as that would lead to failure  anyway. 
What do you think about considering a null check and fail early instead?

2020-02-21 20:36 UTC, adamsoffer commented on packages/sdk/package.json
> -  "version": "1.0.0-streamflow-alpha.17",
It doesn't. I didn't mean to commit that package version change. Reverted. Definitely need to think about how to best handle releases across packages in the monorepo.

2020-02-21 20:37 UTC, adamsoffer commented on packages/sdk/src/index.js
> +      unbondingLockId = null,
Agreed. I now perform a null check and throw an error if argument is null.

2020-02-21 20:38 UTC, adamsoffer commented
Thanks @kyriediculous. I made the requested change. I also cleaned up the commit history so all the ABI updates are in a separate commit now.

2020-02-24 13:26 UTC, kyriediculous commented on packages/sdk/package.json
> -  "version": "1.0.0-streamflow-alpha.17",
Rethinking this a bit , it doesn't really matter if it isn't published to npm , but might be good taking a proactive approach here. We might also want to consider publishing certain package to npm possibly (again out of scope here, just spewing ideas).

2020-02-24 13:29 UTC, kyriediculous commented on packages/sdk/src/index.js
> +      unbondingLockId = null,
Also here it's unfortunate that I can't see the in-between diff between that review and now, only the end-result. Related to https://github.com/livepeer/livepeerjs/pull/570#issuecomment-590313254

2020-02-24 13:33 UTC, kyriediculous commented on packages/sdk/src/index.js
> +      if (!unbondLockId) {
This threw me off for a second as I forgot empty strings are falsy values in JS 😄

2020-02-24 13:34 UTC, kyriediculous approved these changes
LGTM 👍 

I have created an issue regarding the CI stuff in the protocol repo : https://github.com/livepeer/protocol/issues/371

2020-02-26 15:04 UTC, merged