Ar/broadcaster addresses endpoint
livepeer/livepeer-monorepo pull request #566
Opened 2020-02-12 20:07 UTC by angyangie

**What does this pull request do? Explain your changes. (required)**
https://github.com/livepeer/livepeerjs/issues/560

**Specific updates (required)**
https://github.com/livepeer/livepeerjs/issues/560

**How did you test each of these updates (required)**
TBD

**Does this pull request close any open issues?**
https://github.com/livepeer/livepeerjs/issues/560

**Checklist:**
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-02-19 17:56 UTC, angyangie commented on yarn.lock
> -  resolved "https://registry.yarnpkg.com/web3/-/web3-1.2.6.tgz#c497dcb14cdd8d6d9fb6b445b3b68ff83f8ccf68"
I won't mess with this ... will remove most of these yarn changes from next commit

2020-02-22 00:11 UTC, iameli requested changes
Cool, few changes, nothing that can't wait until you're back :+1:

2020-02-22 00:11 UTC, iameli commented on packages/api/src/controllers/broadcaster.js
> +  request(graphUrl, query)
This can be rewritten as `const broadcasterFunds = await request(graphUrl, query);`, which would mean we won't need the promises and whatnot.

2020-02-22 00:11 UTC, iameli commented on packages/api/src/worker.js
> +    return responses
I don't think this format will work — an array of response objects. What happens at `http://localhost:3011/broadcaster/addresses`?

A general pattern for doing a bunch of requests in parallel could look something like this:

```javascript
const urls = [ ... ];
const responses = await Promise.all(urls.map(async url => {
  const res = await fetch(url);
  return await res.json();
}));
```

After that, `responses` will be an array of JSON objects back from the various servers

2020-02-22 00:11 UTC, iameli commented on packages/api/src/controllers/broadcaster.js
> +        if (ethAddresses[b['id']]) {
A bit easier to read as `ethAddresses[b.id]` on the following lines, I think

2020-02-22 00:11 UTC, iameli commented on packages/api/src/controllers/broadcaster.js
> +      ethAddr = addrRes.body._readableState.buffer.head.data
Hah, I had no idea you could sneak the data out this way! There's a much easier way: `const ethAddr = await addrRes.text()`.

2020-02-22 00:11 UTC, iameli commented on packages/api-frontend/pages/broadcasters.tsx
> +      const googleAuthToken = localStorage.getItem('googleAuthToken')
Yeahhhhhhh we never came up with a good solution for this, did we?. When you're back let's do an api-frontend kickoff where we make a list of that remaining stuff and figure out what we wanna do.

2021-01-02 03:58 UTC, closed without merging