explorer: add orchestrator table sorting
livepeer/livepeer-monorepo pull request #567
Opened 2020-02-14 15:38 UTC by adamsoffer

**What does this pull request do? Explain your changes. (required)**
This PR adds the ability for users to sort table columns in the orchestrators view by clicking column header titles. Available for testing on [staging url](https://beta.explorer.livepeer.org).

**Specific updates (required)**
- Adds sorting to each orchestrator column. Clicking once will sort ascending, twice descending, thrice will reset.
- Updates `react-table` dependency

**Does this pull request close any open issues?**
Fixes #556

**Checklist:**
- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-02-19 16:50 UTC, kyriediculous commented
On initial load we sort by stake but the sorting arrow isn't there in the table header, would it be possible to show this so that there is a visual indication that columns are now sortable? I tried looking in the commit where it's missing but it's been a while since I've looked at react stuff 😅

2020-02-19 16:51 UTC, kyriediculous requested changes
On initial load we sort by stake but the sorting arrow isn't there in the table header, would it be possible to show this so that there is a visual indication that columns are now sortable? I tried looking in the commit where it's missing but it's been a while since I've looked at react stuff 😅

2020-02-20 23:05 UTC, adamsoffer commented
> On initial load we sort by stake but the sorting arrow isn't there in the table header, would it be possible to show this so that there is a visual indication that columns are now sortable? I tried looking in the commit where it's missing but it's been a while since I've looked at react stuff 😅

@kyriediculous Good call. I added a desc sort icon on the initial page load. It's up on staging.

2020-02-25 19:05 UTC, kyriediculous commented on packages/explorer-2.0/components/NetworkWidget/index.tsx
> +    console.log(error)
Shouldn't have console logs according to convention I think? Isn't this an ESLINT thing?

2020-02-25 19:14 UTC, kyriediculous requested changes

2020-02-25 19:14 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingView/index.tsx
> +  const isMyAccount = account.toLowerCase() === context?.account?.toLowerCase()
We should not convert addresses to lowercase but use the checksums of the addresses `web3.utils.toChecksumAddress(address)`

Additionally we should check if both addresses are checksum addresses before comparing them `web3.utils.checkAddressChecksum(address)` 

https://web3js.readthedocs.io/en/v1.2.0/web3-utils.html#tochecksumaddress

2020-02-25 19:15 UTC, kyriediculous commented
Looks good, just one more request regarding address checksums. Should use those across the board, especially in functions that involve `eth_send(Raw)Transaction`

2020-02-26 02:09 UTC, adamsoffer commented on packages/explorer-2.0/components/NetworkWidget/index.tsx
> +    console.log(error)
Yeah it is. I've removed console logs 👍

2020-02-26 02:12 UTC, adamsoffer commented on packages/explorer-2.0/components/StakingView/index.tsx
> +  const isMyAccount = account.toLowerCase() === context?.account?.toLowerCase()
I created a helper function `checkAddressEquality(address1, address2)` that converts to checksum addresses first. I'm not using `checkAddressChecksum(address)` because I'm grabbing the address from the url and we can't guarantee that it will be valid checksum.

2020-02-26 22:27 UTC, adamsoffer commented
@kyriediculous thanks for the review! Good to squash and merge?

2020-02-26 22:33 UTC, kyriediculous commented
Changes look good !

2020-02-26 22:33 UTC, kyriediculous approved these changes

2020-02-26 22:35 UTC, merged