explorer: add rinkeby support
livepeer/livepeer-monorepo pull request #570
Opened 2020-02-18 17:28 UTC by adamsoffer

**What does this pull request do? Explain your changes. (required)**
This PR adds Rinkeby support to the explorer via network change detection. It also includes a refactor of the way web3-react is implemented in an effort to improve how the app persists web3 connections. Available for testing on [staging server](https://explorer.beta.livepeer.org).

**Specific updates (required)**
- added rinkeby support
- refactored web3-react implementation
- added `react-ga` dependency for simplifying google analytics event tracking

**How did you test each of these updates (required)**
- Tested by changing network from mainnet to rinkeby and back again using metamask.

**Does this pull request close any open issues?**
#565 

**Checklist:**
- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-02-19 18:02 UTC, kyriediculous requested changes

2020-02-19 18:02 UTC, kyriediculous commented on packages/explorer-2.0/lib/connectors.tsx
> +const POLLING_INTERVAL = 12000
any reason for the change ? I don't think this has to approximate the block time. 
We multiply this on L15, perhaps we can just put this at something like 30 seconds then? Or would that feel too unreactive?

2020-02-19 18:02 UTC, kyriediculous commented on packages/explorer-2.0/lib/connectors.tsx
> +  urls: { 1: RPC_URLS[1], 4: RPC_URLS[4] },
since this isn't strongly typed we could just do `urls: RPC_URLS` here

2020-02-21 19:39 UTC, adamsoffer commented on packages/explorer-2.0/lib/connectors.tsx
> +const POLLING_INTERVAL = 12000
no good reason. I just noticed that's what [the example used](https://github.com/NoahZinsmeister/web3-react/blob/v6/example/connectors.ts#L14) in the `web3-react` framework lol

2020-02-24 13:06 UTC, kyriediculous commented on packages/explorer-2.0/lib/connectors.tsx
> +const POLLING_INTERVAL = 12000
I see... I personally think it's a bad example of them to try to approximate the blocktime.
Since blocktimes aren't exactly 12 seconds, the poller will run out of sync anyway. Worst case scenario we are only polling for a discovered block 11.99999... seconds after it has appeared. This could lead to confusion for novice devs building web3 dapps. 

I think it's more important to optimize for UX and memory here rather than blocktimes. 

What I've done personally in the past is immediately refresh state that pertains to the user itself when the user takes an action. For other state we can just rely on the polling interval and it would be fine to just have this at 30 seconds. Alternatively use pub-sub RPC but this is experimental (which is why it has been removed in go-livepeer as well).

2020-02-24 13:12 UTC, kyriediculous commented
As a rule of thumb I think it would be good to not force-push until the review process has been completed. This allows the reviewer a diff between the new updates and the last review as well as consistent commit history. 

A process we've been using in the protocol team for `go-livepeer` is as follows: 
1.  we submit `fixup` commits during the review process using 
`git commit --fixup <previous commit hash>` 

3. When all changes have been accepted by the reviewer we leave a comment to rebase the commit history and auto-squash the fixups (but don't approve the PR yet)
`git rebase -i --autosquash <branch, most often master>`

4. After rebasing locally, force-push the branch 
`git push --force-with-lease`

5. The reviewer will now accept the PR for merging. 

As more people start working on this repo it could be a good idea to consider a process everyone working on the repo follows.

2020-02-24 13:23 UTC, kyriediculous approved these changes
LGTM 👍 

As mentioned let's address polling interval optimisation separately if we really want to (observing memory usage might be a good idea here). 

I'd also squash the last commit into `add rinkeby support` but I'll leave that up to you.

2020-02-24 17:38 UTC, yondonfu commented on packages/explorer-2.0/lib/utils.tsx
> +  main: 1,
Is this a duplicate of `mainnet`?

2020-02-24 17:42 UTC, adamsoffer commented on packages/explorer-2.0/lib/utils.tsx
> +  main: 1,
ah yea it is. I'll remove.

2020-02-24 17:46 UTC, yondonfu commented
Looks like the orchestrator table view does not refresh when toggling between mainnet & Rinkeby.

Reproduction steps:
1. Connect with Metamask
2. Connect to mainnet in Metamask
3. Observe that the network indicator says "Mainnet" and that the orchestrator table view reflects the list of orchestrators on mainnet
4. Connect to Rinkeby in Metamask
5. Observe that the network indicator says "Rinkeby"
6. Observe that the orchestrator table view still reflects the list of orchestrators on mainnet

I had to manually refresh the page in order for the orchestrator table view to be populated with the list of orchestrators on Rinkeby.

I don't this issue should block this PR though and we can track it in a separate issue.

2020-02-24 17:50 UTC, adamsoffer commented on packages/explorer-2.0/lib/utils.tsx
> +  main: 1,
This utility function is based on [this package ](https://github.com/miguelmota/web3-detect-network). Wondering if that's actually intended.

2020-02-24 19:48 UTC, adamsoffer commented
> As a rule of thumb I think it would be good to not force-push until the review process has been completed. This allows the reviewer a diff between the new updates and the last review (by just selecting the added fixup commit) as well as consistent commit history.
> 
> A process we've been using in the protocol team for `go-livepeer` (thanks to Yondon ! ) is as follows:
> 
> 1. we submit `fixup` commits during the review process using
>    `git commit --fixup <previous commit hash>`
> 2. When all changes have been accepted by the reviewer we leave a comment to rebase the commit history and auto-squash the fixups (but don't approve the PR yet)
>    `git rebase -i --autosquash <branch, most often master>`
> 3. After rebasing locally, force-push the branch
>    `git push --force-with-lease`
> 4. The reviewer will now accept the PR for merging.
> 
> As an example, [this last commit](https://github.com/livepeer/livepeerjs/pull/570/commits/85113850927534a036ec8b9c37d023aa3dcb524b) , could have been submitted as fixup to `add rinkeby support`
> 
> As more people start working on this repo it could be a good idea to consider a process everyone working on the repo follows.
> 
> Here's the blog post Yondon sent me to better understand fixup commits and rebasing https://thoughtbot.com/blog/autosquashing-git-commits

This process looks great. Let's use it moving forward. Question - is it necessary to autosquash at the end since github has the "squash and merge" button?

2020-02-24 19:49 UTC, merged

2020-02-24 20:49 UTC, yondonfu commented
> Looks like the orchestrator table view does not refresh when toggling between mainnet & Rinkeby.

As discussed offline, it turns out that the orchestrator table view *does* refresh when toggling between mainnet & Rinkeby, the refresh is just delayed. Tracking in #576 

> Question - is it necessary to autosquash at the end since github has the "squash and merge" button?

I think this comes down to personal preference. IIUC, GH's "squash and merge" button will always squash all commits into a single commit. This is nice and easy if the contributor wants everything to be in a single commit. The benefit of doing the local rebase when squashing fixup commits is that the contributor has control over the commit history so the contributor can choose to merge the PR with commits X, Y and Z (each commit would contain its own distinct set of changes that the contributor wants to keep separate from each other) as opposed to merging the PR with a single commit. It also gives the maintainer/reviewer the opportunity to do a final code check + commit history check prior to merging.

2020-02-24 21:05 UTC, adamsoffer commented
> > Looks like the orchestrator table view does not refresh when toggling between mainnet & Rinkeby.
> 
> As discussed offline, it turns out that the orchestrator table view _does_ refresh when toggling between mainnet & Rinkeby, the refresh is just delayed. Tracking in #576
> 
> > Question - is it necessary to autosquash at the end since github has the "squash and merge" button?
> 
> I think this comes down to personal preference. IIUC, GH's "squash and merge" button will always squash all commits into a single commit. This is nice and easy if the contributor wants everything to be in a single commit. The benefit of doing the local rebase when squashing fixup commits is that the contributor has control over the commit history so the contributor can choose to merge the PR with commits X, Y and Z (each commit would contain its own distinct set of changes that the contributor wants to keep separate from each other) as opposed to merging the PR with a single commit. It also gives the maintainer/reviewer the opportunity to do a final code check + commit history check prior to merging.

ah yeah makes sense!