subgraph: index TicketBroker deposit/reserve events
livepeer/livepeer-monorepo pull request #575
Opened 2020-02-24 16:34 UTC by adamsoffer

**What does this pull request do? Explain your changes. (required)**
This PR includes an update to the subgraph for indexing TicketBroker deposit/reserve events. More specific updates detailed below.

**Specific updates (required)**
- adds `Broadcaster` entity with `deposit` and `reserve` fields
- adds `totalMovedStake` field to `Round` entity
- add `totalGeneratedFees` `totalNewStake` and `totalGeneratedFees` to `Round` entity
- renames `accruedFees` to `totalGeneratedFees` in `Transcoder` entity to be consistent
- updates README with instructions on how to run subgraph locally
- patches graph-cli dep (the graph pushed up a fix to this package but haven't yet published to npm)

**How did you test each of these updates (required)**
Successfully deployed and synced on [livepeer-canary](https://thegraph.com/explorer/subgraph/livepeer/livepeer-canary) subgraph

**Does this pull request close any open issues?**
#571 

**Checklist:**
- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-02-24 22:38 UTC, yondonfu requested changes

2020-02-24 22:38 UTC, yondonfu commented on packages/subgraph/README.md
> +3. In the root of this project run `docker-compose up`. This command will look for the `docker-compose.yml` file and automatically provision a server with rust, postgres, and ipfs, and spin up a grap
Extra parens at the end?

2020-02-24 22:38 UTC, yondonfu commented on packages/subgraph/README.md
> +2. Inside `docker-compose.yml` set the ethereum network to an archive node that has tracing enabled. If you don't have access to an archive node we recommend using [Alchemy](https://alchemyapi.io/).
Might be helpful to note the key name (i.e. `ethereum` under the `environment` section) within the YAML file for which a value should be specified.

2020-02-24 22:38 UTC, yondonfu commented on packages/subgraph/schema.graphql
> +The Livepeer protocol is round based and each round is represented by some number of Ethereum blocks.
Seems like this comment is in the wrong place (doesn't describe the `Broadcaster` entity)?

2020-02-24 22:38 UTC, yondonfu commented on packages/subgraph/src/mappings/ticketBroker.ts
> +    event.transaction.hash.toHex() + 'WinningTicketRedeemedEvent',
We currently use [tx hash + log index](https://github.com/livepeer/livepeerjs/blob/f80f47baa02f8a09ec1fe00b7d8acc67d5c5e723/packages/subgraph/src/mappings/ticketBroker.ts#L7) in the identifier since there could be multiple events in the same transaction - should we do the same here?

2020-02-24 22:38 UTC, yondonfu commented on packages/subgraph/schema.graphql
> +type WinningTicket @entity {
Why do we need an `WinningTicket` entity and a `WinningTicketRedeemedEvent` entity? Seems like `WinningTicketRedeemedEvent` contains a superset of the fields of `WinningTicket`.

2020-02-24 22:38 UTC, yondonfu commented on packages/explorer-2.0/queries/orchestratorsView.gql
> -    active
We don't need the `active` field anymore?

2020-02-24 22:38 UTC, yondonfu commented on packages/subgraph/src/mappings/bondingManager.ts
> +  let additionalAmount = delegatorData.value0.minus(bondedAmount)
I think this will include the new LPT staked by the delegator as well as the delegator's unclaimed rewards since the last time its `bondedAmount` field was updated in the DB. I don't think we should count the delegator's unclaimed rewards to `additionalAmount` because:

1. The unclaimed rewards do not consist of new LPT being staked by the delegator (rather they consist of new LPT that is minted and automatically staked)
2. The `Bond` event handler in [bondingManager_LIP11.ts](https://github.com/livepeer/livepeerjs/pull/575/files#diff-f99a2db018ec7d0de146285dc8f28e3cR85) has access to an `additionalAmount` field that only counts new LPT being staked by the delegator and not unclaimed rewards. So, as-is, this `Bond` event handler mapping's behavior will be different from the behavior of the `bondingManager_LIP11` `Bond` event handler mapping.

Handling this might not be that straightforward...

- One solution could be to index LPT `Transfer` events and when this `Bond` event handler fires check if we have an LPT `Transfer` event with `from = delegator's address` and `to = Minter address` in the same transaction then the [value field](https://github.com/livepeer/protocol/blob/cbcdf50b5e7cb93b61da009824ca6dae9fe34ae7/contracts/bonding/BondingManager.sol#L333) will be the new LPT staked by the delegator. This isn't full proof though since in theory an address could send LPT directly to the Minter without it being staked with the BondingManager

- Another solution could be to call `pendingStake()` at the block number right before the block in which the new `Bond` event is included in. The delegator's last recorded `bondedAmount` could be subtracted from the value returned to get the unclaimed rewards. Then, the unclaimed rewards could be subtracted from the `delegatorData.value0.minus(bondedAmount)` to get the new LPT staked by the delegator. I think this might work, but I'm not sure about the practicality of calling `pendingStake()` at a past block number in the event handler

2020-02-25 18:49 UTC, adamsoffer commented on packages/subgraph/src/mappings/bondingManager.ts
> +  let additionalAmount = delegatorData.value0.minus(bondedAmount)
Confirmed `additionalAmount` included unclaimed rewards which we don't want. I pushed a fix that replaces the `Bond` event handler with a call handler which gives us access to a delegator's inputted amount.

2020-02-25 18:58 UTC, kyriediculous requested changes

2020-02-25 18:58 UTC, kyriediculous commented on packages/subgraph/schema.graphql
> +Bonded accounts who have delegated their stake towards a transcoder candidate
Let's be proactive about adopting ubiquitous streamflow languageh ere. 

"towards an orchestrator"

2020-02-25 18:58 UTC, kyriediculous commented on packages/subgraph/schema.graphql
> +Broadcasters pay transcoders to do the work of transcoding in exchange for fees
"pay orchestrators for transcoding work"

2020-02-25 18:58 UTC, kyriediculous commented on packages/subgraph/src/mappings/bondingManager_LIP12.ts
> +  transcoderUpdated.save()
Kinda of out of scope and more of a question than a remark as this goes for any type similar to this one. 

Why are we not simply passing the event into the constructor ? 

Alternatively we can use a method that calls the constructor instead, validates the necessary fields and can return an error if necessary.

2020-02-25 18:58 UTC, kyriediculous commented on packages/subgraph/src/mappings/bondingManager_LIP12.ts
> +    event.transaction.hash.toHex() + '-' + event.logIndex.toString(),
we can extract this into a helper , something like `GetEventID` ?

2020-02-25 19:51 UTC, adamsoffer commented on packages/explorer-2.0/queries/orchestratorsView.gql
> -    active
As of streamflow, in the Explorer, we only use `activationRound` and `deactivationRound` to determine if an O is active so we no longer need to ask for the `active` field. 

These are the ways I can query the active and pending active sets in th explorer as of now:
1. Current active set: `activationRound <= currentRound && deactivationRound > currentRound`
2. Pending active: `activationRound > currentRound  && deactivationRound > currentRound`
3. Pending inactive: `activationRound <= currentRound &&  deactivationRound == currentRound + 1`

I pushed an update that sets a transcoder's `active` state whenever a `transcoderActivated` or `transcoderDeactivated` event gets emitted, so we can query transcoders by the `active` field again if we want and without needing the current round ahead of time, but important to note this query would exclude transcoders who are set to become inactive in the following round and includes transcoders who are currently inactive but are set to become active in the following round.  I believe the only way to keep track of the current active set using the `active` field would be to loop through all registered transcoders upon new round events and call `isActiveTranscoder` but there's no easy way to query all registered transcoders in a mapping right now and it also wouldn't scale very well.

2020-02-25 19:55 UTC, adamsoffer commented on packages/subgraph/schema.graphql
> +Bonded accounts who have delegated their stake towards a transcoder candidate
Yeah, I was going to use "orchestrator" but decided to stick with "transcoder" simply because the smart contracts still refer to them as transcoders and I want to maintain parity with them. I think if we use the term Orchestrator in one place we should update it everywhere else in the subgraph, which maybe we want to do. Worth a discussion.

2020-02-25 19:56 UTC, adamsoffer commented on packages/subgraph/schema.graphql
> +Bonded accounts who have delegated their stake towards a transcoder candidate
My philosophy right now is to use "orchestrator" in all user-facing UIs but maintain parity with smart contracts in code.

2020-02-25 20:01 UTC, kyriediculous commented on packages/subgraph/schema.graphql
> +Bonded accounts who have delegated their stake towards a transcoder candidate
The problem with the contracts is that we cant' just change function signatures whenever we want to conform to a certain language, well we _could_, but that would be ill advised. Upgrading contracts is a risky endeavour and it would change the existing API surface for ABI bindings (eg JS contract bindings or Go contract bindings). 

Additionally in streamflow a transcoder is by definition not protocol aware.

Therefore I think not maintaining parity is fine but since I don't actively work on this repo I will leave the end decision up to you. There's some overlap in go-livepeer as well still.

2020-02-25 20:10 UTC, adamsoffer commented on packages/subgraph/schema.graphql
> +Bonded accounts who have delegated their stake towards a transcoder candidate
Yeah, agreed. Let's aim to rename all instances of the subgraph `Transcoder` entity to `Orchestrator`. Want to create an issue for this?

2020-02-25 20:14 UTC, adamsoffer commented on packages/subgraph/schema.graphql
> +type WinningTicket @entity {
This is indeed duplicative. I've removed `WinningTicket` in favor of a single `WinningTicketRedeemed` entity that implements the Transaction interface defined in `schema.graphql`

2020-02-25 20:14 UTC, adamsoffer commented on packages/subgraph/src/mappings/ticketBroker.ts
> +    event.transaction.hash.toHex() + 'WinningTicketRedeemedEvent',
Yeah, we should do the same here. Fixed.

2020-02-25 20:15 UTC, adamsoffer commented on packages/subgraph/README.md
> +3. In the root of this project run `docker-compose up`. This command will look for the `docker-compose.yml` file and automatically provision a server with rust, postgres, and ipfs, and spin up a grap
removed

2020-02-25 20:15 UTC, adamsoffer commented on packages/subgraph/README.md
> +2. Inside `docker-compose.yml` set the ethereum network to an archive node that has tracing enabled. If you don't have access to an archive node we recommend using [Alchemy](https://alchemyapi.io/).
I've updated readme to make this more clear.

2020-02-25 20:46 UTC, adamsoffer commented on packages/subgraph/schema.graphql
> +The Livepeer protocol is round based and each round is represented by some number of Ethereum blocks.
Updated comment to describe `Broadcaster` entity

2020-02-25 20:48 UTC, adamsoffer commented on packages/subgraph/schema.graphql
> +Broadcasters pay transcoders to do the work of transcoding in exchange for fees
👍I'll replace all instances of "transcoder" with "orchestrator" in another PR.

2020-02-25 21:02 UTC, adamsoffer commented on packages/subgraph/src/mappings/bondingManager_LIP12.ts
> +  transcoderUpdated.save()
Yeah, it's a good question. It appears the graph only allows you to instantiate an entity with an id. https://thegraph.com/docs/define-a-subgraph#writing-mappings

2020-02-25 21:36 UTC, kyriediculous commented on packages/subgraph/src/mappings/bondingManager_LIP12.ts
> +  transcoderUpdated.save()
Ahh these Classes are generated? Gotcha !

2020-02-25 21:43 UTC, kyriediculous commented on packages/subgraph/schema.graphql
> +Broadcasters pay transcoders to do the work of transcoding in exchange for fees
okay sounds good to me

2020-02-26 01:07 UTC, adamsoffer commented on packages/subgraph/src/mappings/bondingManager_LIP12.ts
> +    event.transaction.hash.toHex() + '-' + event.logIndex.toString(),
Created a `makeEventId` helper. Also, as an aside I'm now using `event.transactionLogIndex` instead of `event.logIndex` since I discovered `logIndex` wasn't guaranteeing a unique id. `transactionLogIndex` is the index of the event in the transaction, whereas `logIndex` is the index of the event in the block.

2020-02-26 16:25 UTC, yondonfu commented on packages/subgraph/src/mappings/roundsManager.ts
> +    transcoder.active = bondingManager.isActiveTranscoder(
Looks like there is already a `bondingManager.isActiveTranscoder()` call in the previous line.

2020-02-26 16:49 UTC, adamsoffer commented on packages/subgraph/src/mappings/roundsManager.ts
> +    transcoder.active = bondingManager.isActiveTranscoder(
woops

2020-02-26 18:37 UTC, adamsoffer commented on packages/subgraph/src/mappings/roundsManager.ts
> +    transcoder.active = bondingManager.isActiveTranscoder(
Fixed.

2020-02-26 18:46 UTC, yondonfu approved these changes
LGTM 🚢. Let's squash into a single commit before merging.

Nit: I noticed that 4b4f1dc contains a few changes that are not related to subgraph indexing (i.e. README updates and the graph-cli patch). For future reference, it could be helpful to keep those changes in separate commits. IMO this makes review easier and also helps with navigating commit history when trying to figure out where a change/bug was introduced. No need to do anything for this PR, but just wanted to make the suggestion.

2020-02-26 18:57 UTC, adamsoffer commented
> LGTM 🚢. Let's squash into a single commit before merging.
> 
> Nit: I noticed that [4b4f1dc](https://github.com/livepeer/livepeerjs/commit/4b4f1dc860e284fbf22f458f5f5611f86d3a7d08) contains a few changes that are not related to subgraph indexing (i.e. README updates and the graph-cli patch). For future reference, it could be helpful to keep those changes in separate commits. IMO this makes review easier and also helps with navigating commit history when trying to figure out where a change/bug was introduced. No need to do anything for this PR, but just wanted to make the suggestion.

Awesome. For sure. Commit readability will be top of mind on all future commits 👍

2020-02-26 18:58 UTC, merged