fix 3box external account signature verification
livepeer/livepeer-monorepo pull request #578
Opened 2020-03-02 16:20 UTC by adamsoffer

**What does this pull request do? Explain your changes. (required)**
This PR fixes an issue causing the 3box signature verification to fail when adding an external account. This bug was introduced when we switched the web3 library we pass into `web3-react` (`ethers.js` instead of `web3.js`) since ether.js doesn't have a `ecrecover` method. 

It also prevents the account page from reloading and displaying the loading indicator after successfully linking an external account.

**Specific updates (required)**
- Instantiates web3 instance and uses `ecRecover` method for signature verification
- Checks if data has already been fetched and if so prevents loading indicator from taking over the page upon data refetching.

**Checklist:**
- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-03-02 19:04 UTC, kyriediculous commented on packages/explorer-2.0/components/EditProfile/index.tsx
> +      const Web3 = require('web3') // use web3 lib for ecRecover method
Ooh I see what's happening, no need to wrap the provider even here. That's just because web3 requires a provider to get the object that exposes the API. 

In ethersjs the EC functions are in utilities : https://docs.ethers.io/ethers.js/html/api-utils.html#elliptic-curve

2020-03-02 19:08 UTC, kyriediculous commented on packages/explorer-2.0/components/EditProfile/index.tsx
> +      const Web3 = require('web3') // use web3 lib for ecRecover method
````
let recovered = ethers.utils.verifyMessage(messageHashBytes, flatSig);
console.log(recovered === wallet.address);
// true
```

2020-03-02 21:33 UTC, adamsoffer commented on packages/explorer-2.0/components/EditProfile/index.tsx
> +      const Web3 = require('web3') // use web3 lib for ecRecover method
ah good find thanks!

2020-03-03 14:15 UTC, kyriediculous requested changes

2020-03-03 14:15 UTC, kyriediculous commented on packages/explorer-2.0/components/EditProfile/index.tsx
> +        let verifiedAccount = ethers.utils.verifyMessage(
We need to pass in the message digest here as a uint8 array

```
let messageHash = ethers.utils.arrayift(ethers.utils.solidityKeccak256(message.replace(/<br ?\/?>/g, '\n')));
```

2020-03-03 14:15 UTC, kyriediculous commented on packages/explorer-2.0/components/EditProfile/index.tsx
> +import { ethers } from 'ethers'
I think we can even do `import {arrayify , verifyMessage} from 'ethers/utils'` but I'll leave that up to you

2020-03-03 15:45 UTC, adamsoffer commented on packages/explorer-2.0/components/EditProfile/index.tsx
> +        let verifiedAccount = ethers.utils.verifyMessage(
@kyriediculous hmm is this necessary? This works as is:
```js
let verifiedAccount = verifyMessage(
  message.replace(/<br ?\/?>/g, '\n'),
  signature,
)
```

2020-03-03 17:46 UTC, kyriediculous commented on packages/explorer-2.0/components/EditProfile/index.tsx
> +        let verifiedAccount = ethers.utils.verifyMessage(
this will always return an address, as is it will return the wrong one.

2020-03-03 20:15 UTC, adamsoffer commented on packages/explorer-2.0/components/EditProfile/index.tsx
> +import { ethers } from 'ethers'
Oddly ethers throws a weird a `Can't resolve 'child_process'` error when I import individual methods like that so I'll leave as is.

2020-03-04 00:24 UTC, kyriediculous commented on packages/explorer-2.0/components/EditProfile/index.tsx
> +        let verifiedAccount = ethers.utils.verifyMessage(
Do we have unit testing? If we extract it into a helper then we can easily unit test it.

2020-03-04 02:32 UTC, kyriediculous commented on packages/explorer-2.0/components/EditProfile/index.tsx
> +        let verifiedAccount = ethers.utils.verifyMessage(
Or can we do a sanity check at least to see that this works as expected ?

2020-03-04 02:36 UTC, adamsoffer commented on packages/explorer-2.0/components/EditProfile/index.tsx
> +        let verifiedAccount = ethers.utils.verifyMessage(
Not yet :/ Been meaning to set up unit testing. I can create an issue to set that up. I did a sanity test locally and then on https://beta.explorer.livepeer.org

2020-03-04 02:37 UTC, kyriediculous commented on packages/explorer-2.0/components/EditProfile/index.tsx
> +        let verifiedAccount = ethers.utils.verifyMessage(
Ok , looks good then !

2020-03-04 02:37 UTC, kyriediculous commented on packages/explorer-2.0/components/EditProfile/index.tsx
> +        let verifiedAccount = ethers.utils.verifyMessage(
Could we squash the second commit into the first one ?

2020-03-04 02:41 UTC, adamsoffer commented on packages/explorer-2.0/components/EditProfile/index.tsx
> +        let verifiedAccount = ethers.utils.verifyMessage(
Great! Will do.

BTW in addition to unit tests, another thing I set up to help us test new features/fixes is "deployment previews" with Now. Preview urls for every commit and PR  👉https://zeit.co/features/deployment-previews

2020-03-04 02:44 UTC, kyriediculous approved these changes

2020-03-04 03:17 UTC, merged