ar/adding email password registration backend
livepeer/livepeer-monorepo pull request #592
Opened 2020-03-11 22:49 UTC by angyangie

**What does this pull request do? Explain your changes. (required)**
First pass at https://github.com/livepeer/livepeerjs/issues/582

**Specific updates (required)**
https://github.com/livepeer/livepeerjs/issues/582

**Does this pull request close any open issues?**
https://github.com/livepeer/livepeerjs/issues/582

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-03-17 17:40 UTC, iameli requested changes

2020-03-17 17:40 UTC, iameli commented on packages/api/src/controllers/user.js
> +const iterations = 10000
Maybe let's go with a all caps `ITERATIONS` to signify it's a constant

2020-03-17 17:40 UTC, iameli commented on packages/api/src/controllers/user.js
> +function makeNextHREF(req, nextCursor) {
Let's move this into a shared file and import it from there rather than duplicating it in all the different controllers.

2020-03-17 17:40 UTC, iameli commented on packages/api/src/controllers/user.js
> +  //   TODO: if (hashedPassword.length != req.body.password.length) {
This can be enforced via the JSON-schema

2020-03-17 17:40 UTC, iameli commented on packages/api/src/controllers/user.js
> +    const userEmail = await req.store.get(`user-emails/${email}`)
`const userEmail = await req.store.find("user", {email})` post-refactor

It'll do a list("user-emails/eli@iame.li"), which'll return
```
[user-emails/eli@iame.li/ABC123]
```

And then we can retrieve userId ABC123

2020-03-17 17:40 UTC, iameli commented on packages/api/src/controllers/user.js
> +    if (!user) {
Refactor note: this data integrity stuff can be enforced on the new model layer

Eli DevOps note: let's add a Papertrail alert for "data integrity exception"

2020-03-17 17:40 UTC, iameli commented on packages/api/src/controllers/user.js
> +    const token = jwt.sign({ sub: user.id }, 'secret', {
Let's add `--jwt-secret=` as a parameter in cli.js

2020-03-17 17:40 UTC, iameli commented on packages/api/src/controllers/user.js
> +    const token = jwt.sign({ sub: user.id }, 'secret', {
Let's also at  `--jwt-audience=` as a CLI parameter and add it to the JWT here with `{sub: user.id, aud: cliParamters.jwtAudience}`

2020-03-17 17:40 UTC, iameli commented on packages/api/src/controllers/user.js
> +async function hash(password, salt) {
Let's move this function and its helpers into its own file so it can be imported by the API frontend

2020-03-17 17:40 UTC, iameli commented on packages/api/src/controllers/user.test.js
> +  describe('basic CRUD with google auth', () => {
Don't think we probably need to test this

2020-03-17 17:40 UTC, iameli commented on packages/api/src/controllers/user.js
> +app.get('/', authMiddleware({ admin: true }), async (req, res) => {
Other things we might do on `authMiddleware`: 

Enforce that there is a user, but not anything else:

`authMiddleware({})`

Let's say users can't change their password with an API key, that'd be like:

`authMiddleware({ apiKey: false })`

2020-03-17 17:40 UTC, iameli commented on packages/api/src/schema/schema.yaml
> +        password:
We can do the `minLength` and `maxLength` enforcement here - should be exactly 64 characters

2020-04-10 12:04 UTC, angyangie commented
Closing this branch - all changes were included in https://github.com/livepeer/livepeerjs/pull/604

2020-04-10 12:04 UTC, closed without merging