update subgraph Protocol entity with new fields
livepeer/livepeer-monorepo pull request #595
Opened 2020-03-12 04:15 UTC by adamsoffer

**What does this pull request do? Explain your changes.**
This PR adds a new set of fields to the Protocol entity and introduces 4 new entities.

**Specific updates**
- Adds the following fields to the Protocol entity: 
`currentRound, inflation, inflationChange, lastInitializedRound, lastRoundLengthUpdateRound, lastRoundLengthUpdateStartBlock, lockPeriod, maxEarningsClaimsRounds, numActiveTranscoders, paused, roundLength, roundLockAmount, targetBondingRate, unbondingPeriod`
- Introduces the following new entities:
`SetCurrentRewardTokens, Pause, Unpause, ParameterUpdate`

**How did you test each of these updates**
The changes haven been deployed and synced on the Livepeer Canary subgraph

**Does this pull request close any open issues?**
#437 

**Checklist:**
- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-03-26 10:42 UTC, kyriediculous requested changes
Looks good overall although my subgraph working knowledge is limited. One minor detail.

2020-03-26 10:42 UTC, kyriediculous commented on packages/subgraph/src/mappings/livepeerToken.ts
> +  }
We can shorten this to  `const protocol = Protocol.load('0') || new Protocol('0')` , that goes for every file in this PR where we do this. 

```
const a = null || undefined || "foo" 
console.log(a)
// "foo"
```

2020-03-26 16:21 UTC, adamsoffer commented on packages/subgraph/src/mappings/livepeerToken.ts
> +  }
@kyriediculous yeah good call. I've updated each file with this shortened syntax.

2020-03-27 20:28 UTC, kyriediculous commented
Changes look good, can we squash the commits on merge?

2020-03-27 20:28 UTC, kyriediculous approved these changes

2020-03-27 20:29 UTC, merged