Ar/adding new db model to api
livepeer/livepeer-monorepo pull request #604
Opened 2020-03-23 15:47 UTC by angyangie

**What does this pull request do? Explain your changes. (required)**
Adding new DB model to API

**Specific updates (required)**
https://github.com/livepeer/livepeerjs/issues/599

**How did you test each of these updates (required)**
Need to fix all tests, but working locally

**Does this pull request close any open issues?**
https://github.com/livepeer/livepeerjs/issues/599

**Checklist:**
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-03-28 23:04 UTC, iameli commented on packages/api/src/controllers/user.js
> +    res.json({ error: 'incorrect password' })
Let's do `errors: ["incorrect password"]` here for consistency

2020-04-07 01:01 UTC, iameli requested changes
Sweet!

Something's making me nervous about our join keys just being concatenations of kind and field name... `useremail/eli@iame.li` means "the `user` that has the `email` field set to `eli@iame.li` but it could also mean we have something with `kind: useremail`. What if we did `user+email/eli@iame.li`? That way we can make plusses illegal in `kind` fields and we never have to worry about a collision.

2020-04-07 01:01 UTC, iameli commented on packages/api/src/controllers/object-stores.js
> +  if (objStoreIds.includes(id)) {
Need an `else` condition here. Actually, for multiple checks like this, I usually like to flip the condition and flatten out all the failure cases? Like...

```javascript
if (!objStoreIds.includes(id)) {
  res.status(403);
  return res.json({errors: [etc etc]})
}

if (req.user.admin !== true && req.user.id !== objStore.userId) {
  res.status(403);
  return res.json //etc...
}

res.status(200)
res.json(objStore)
```

2020-04-07 01:01 UTC, iameli commented on packages/api/src/controllers/user.js
> +  const admin = 'admin' in req.body ? req.body.admin : false
Hmm, this would let anyone creating an account declare themselves to be an admin. Let's have all users set to `false` for now, and we can manually change folks in the database for now.

2020-04-07 01:01 UTC, iameli commented on packages/api/src/controllers/user.js
> +  console.log(`USERUDSSSS: ${JSON.stringify(userIds)}`)
Pronounced "useroods", perhaps?

2020-04-07 01:01 UTC, iameli commented on packages/api/src/controllers/user.js
> +  }
Same as above, we can flatten out the logic here:

```suggestion
  if (!user) {
    res.status(403)
    return res.json({ errors: ['user not created'] })
  }
  
  res.status(201)
  res.json(user)
```

2020-04-07 01:01 UTC, iameli commented on packages/api/src/controllers/user.test.js
> +      }
This pattern will cause a false positive when the `deleteKey` _doesn't_ return an error —  the `catch` block will never run and nothing will ever be `expect`ed. An alternative:

```suggestion
      let error;
      try {
        await server.store.deleteKey(`user/${userRes.id}`)
      } catch (err) {
        error = err
      }
      expect(error.status).toBe(404)
```

2020-04-07 01:01 UTC, iameli commented on packages/api/src/controllers/user.test.js
> +      try {
same error pattern

2020-04-07 01:01 UTC, iameli commented on packages/api/src/store/model.js
> +    if (!properties || properties.length) {
Does this ever happen? Seems like we'd want everything to have properties.

2020-04-07 01:03 UTC, iameli commented on packages/api/src/store/model.js
> +  cleanWriteOnlyResponses(id, responses) {
I like this!

2020-04-07 01:11 UTC, iameli commented on packages/api/src/store/model.js
> +  async getPropertyIds(prefix, cursor, limit, cleanWriteOnly) {
I think the signature here could be improved. It would be nice to not have to know about how the keys are stored internally (e.g. `user+email/eli@iame.li/ABC123`) to work with this. How about something like this:

```javascript
const [userId] = await req.store.find("user", {email: "eli@livepeer.org"})
```

And then we can parse that out into something that can be passed to listKeys, something like

```javascript
async query(kind, queryObj, cursor, limit, cleanWriteOnly) {
  const [queryKey, ...rest] = Object.keys(queryObj);
  if (rest.length > 0) {
    throw new Error("you may only query() by one key")
  }
  const queryValue = queryObj[queryKey];
  const prefix = `${kind}+${queryKey}/${queryValue}`
  const [keys] = await this.backend.listKeys(prefix, cursor, limit, cleanWriteOnly)
```

2020-04-08 22:13 UTC, angyangie commented on packages/api/src/store/model.js
> +    if (!properties || properties.length) {
You are right! I just removed it. Good catch

2020-04-08 23:13 UTC, angyangie commented on packages/api/src/store/model.js
> +  async getPropertyIds(prefix, cursor, limit, cleanWriteOnly) {
This is much cleaner! I have just edited

2020-04-10 02:22 UTC, merged