add real-time poll tallying to subgraph
livepeer/livepeer-monorepo pull request #611
Opened 2020-03-31 21:34 UTC by adamsoffer

**What does this pull request do? Explain your changes. (required)**
This PR introduces real-time poll tallying to the subgraph as per the spec outlined in [LIP16](https://github.com/livepeer/LIPs/issues/16). 

**Does this pull request close any open issues?**
#600 #601 

**Todos**
- [ ] Complete integration test assertions
- [ ] Spin up graph-node and ganache instance as part of integration tests
- [ ] Add `PollCreator` rinkeby contract address to networks.yaml
- [ ] Add `PollCreator` mainnet contract address to networks.yaml

2020-04-15 00:51 UTC, kyriediculous commented
CI fails because the VM it runs on does not have truffle installed. 

There's two ways to fix this 
- Add truffle to the dependencies for the project and instead of `truffle test` use `./node_modules/.bin/truffle test`
- Add a job to the circle yaml file that installs truffle globally 

I'd prefer the first option as it is the simplest

2020-04-16 00:02 UTC, kyriediculous requested changes

2020-04-16 00:02 UTC, kyriediculous commented on packages/subgraph/docker-compose.yml
> +      ethereum: 'development:http://host.docker.internal:8545'
Is this a permanent change or was this meant for development?

2020-04-16 00:02 UTC, kyriediculous commented on packages/subgraph/schema.graphql
> +  "The voter that casted the vote"
how about "vote caster" for brevity ?

2020-04-16 00:02 UTC, kyriediculous commented on packages/subgraph/schema.graphql
> +  "This will be non-zero if voter is an orchestrator and any of the its delegators voted"
Since there are other cases where this can be negative I think, ie any stake that is not bonded. How about rewording this to "stake  weight not eligible for voting"

If not rewording "any of the its delegators" -> "any of its delegators"

2020-04-16 00:02 UTC, kyriediculous commented on packages/subgraph/schema.graphql
> +  "The voter address"
is writing "The voted address" instead of "voter address" a subgraph convention?

2020-04-16 00:02 UTC, kyriediculous commented on packages/subgraph/truffle.js
> +}
I don't think we need truffle for this because this package isn't set up to fully utilise truffle suite anyway. The only thing we really get right now is web3 provider injection but this is quite trivial to set up. 

We can just use vanilla mocha and replace `contract` blocks with `describe` blocks. 

Then we also don't need to run and install truffle for CI but can just run `npm run test`

2020-04-20 14:19 UTC, adamsoffer commented on packages/subgraph/docker-compose.yml
> +      ethereum: 'development:http://host.docker.internal:8545'
This is a permanent change. We only use the docker file for development purposes. If a developer wants to deploy the subgraph using their own archive node I mention they can change the `ethereum` value in the README.

2020-04-20 14:20 UTC, adamsoffer commented on packages/subgraph/schema.graphql
> +  "The voter that casted the vote"
Sounds good

2020-04-20 14:24 UTC, adamsoffer commented on packages/subgraph/schema.graphql
> +  "This will be non-zero if voter is an orchestrator and any of the its delegators voted"
hmm, I'm not aware that this can ever be negative. `voteStake` will always match a user's pending stake, and `nonVoteStake` will always be the sum of all it's delegators voteStake that voted.

> If not rewording "any of the its delegators" -> "any of its delegators"
Will fix typo

2020-04-20 14:26 UTC, adamsoffer commented on packages/subgraph/schema.graphql
> +  "The voter address"
lol no it's not a convention. Not sure why I prefaced with "the". I can change to "voter address".

2020-04-20 17:50 UTC, kyriediculous commented on packages/subgraph/schema.graphql
> +  "This will be non-zero if voter is an orchestrator and any of the its delegators voted"
Oh sorry I meant non-zero but somehow wrote 'negative'

2020-04-20 17:53 UTC, kyriediculous commented on packages/subgraph/docker-compose.yml
> +      ethereum: 'development:http://host.docker.internal:8545'
this was previously running against a mainnet ethereum node but now we expect users  to run this docker image against their own local node? 

Could we update the `README.md` as well if that's the case?

2020-04-20 17:55 UTC, kyriediculous commented on packages/subgraph/schema.graphql
> +  "This will be non-zero if voter is an orchestrator and any of the its delegators voted"
Oh okay I see this is per orchestrator, description looks good then !

2020-04-22 11:57 UTC, kyriediculous requested changes

2020-04-22 11:57 UTC, kyriediculous commented on packages/subgraph/src/mappings/dynamic.ts
> -      if (!vote) {
I think we should keep this, no ? 

Once an orchestrator votes we can use its stake weight that was updated by the subgraph up until then.

This should reduce the amount of updates needed for orchestrators not participating in governance.

2020-04-22 11:57 UTC, kyriediculous commented on packages/subgraph/src/mappings/dynamic.ts
> +  if (voterAddress == event.params.delegator.toHex()) {
Nit: instead of nesting the entire function body in this if statement, how about adopting some go idiomatics here of always trying to end with the happy case ? 

```
if (voterAddress !== event.params.delegator.toHex()) return;
// function body ... 
```

2020-04-22 11:57 UTC, kyriediculous commented on packages/subgraph/src/mappings/dynamic.ts
> +  if (voterAddress == event.params.delegator.toHex()) {
Nit: instead of nesting the entire function body in this if statement, how about adopting some go idiomatics here of always trying to end with the happy case ? 

```
if (voterAddress !== event.params.delegator.toHex()) return;
// function body ... 
```

2020-04-22 11:57 UTC, kyriediculous commented on packages/subgraph/src/mappings/dynamic.ts
> +  if (voterAddress == event.params.delegator.toHex()) {
Nit: instead of nesting the entire function body in this if statement, how about adopting some go idiomatics here of always trying to end with the happy case ? 

```
if (voterAddress !== event.params.delegator.toHex()) return;
// function body ... 
```

2020-04-22 11:57 UTC, kyriediculous commented on packages/subgraph/src/mappings/dynamic.ts
> -      // return if voter didn't vote in this specific poll
same comment as above

2020-04-22 11:57 UTC, kyriediculous commented on packages/subgraph/src/mappings/dynamic.ts
> -      // return if voter didn't vote in this specific poll
same question as above

2020-04-22 11:57 UTC, kyriediculous commented on packages/subgraph/test/integration/test.js
> +    await Poll.methods.vote(1).send({ from: delegator3 })
nit: we don't have to do this serially , we can use `Promise.all()`. 

```
await Promise.all([
  Poll.methods.vote(0).send({ from: transcoder1 }),
  Poll.methods.vote(1).send({ from: delegator1 })
  Poll.methods.vote(0).send({ from: delegator2 })
  Poll.methods.vote(1).send({ from: delegator3 })
])
```

2020-04-22 11:57 UTC, kyriediculous commented on packages/subgraph/test/integration/test.js
> +    await Poll.methods.vote(1).send({ from: delegator3 })
Additionally how about creating an object here first that we can then re-use throughout this test

```
const voters = {}
voters[transcoder1]=0
voters[delegator1]=1
voters[delegator2]=0
voters[delegator3]=1

await Promise.all(
  function() {
    let calls = []
    for voter, choiceID in voters {
       calls.push(Poll.methods.vote(choiceID).send({ from: voter }))
     }
    return calls
  }
)
```

2020-04-22 11:57 UTC, kyriediculous commented on packages/subgraph/test/integration/test.js
> +      subgraphPollData.data.transcoder1VoteChoice[0].choiceID,
If we also return the voter from the subgraph query on L324, L327, L330 and L333 and we adopt the object described in the comment above then this can be shortened to 

```
for (k, vote in subgraphPollData.data) {
  assert.equal(vote[0].choiceID, voters[vote.voter], "incorrect vote choice")
}

2020-04-22 13:15 UTC, kyriediculous requested changes

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/schema.graphql
> +enum PollChoice @entity {
the CLI has an "Abstain" option. 

Should we add it here as well ? This has been a discussion point in LIP16. 

Personally I think it won't be used much if at all , but then again it doesn't hurt adding it for completeness. 

I'm wondering what @yondonfu thinks about this.

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/bondingManager.ts
> +  transcoder.pendingPricePerSegment = event.params.pendingPricePerSegment
Why are we re-adding setting this state considering these fields are deprecated?

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/bondingManager.ts
> +  transcoderUpdated.feeShare = event.params.pendingFeeShare
Why are we re-adding setting this state considering these fields are deprecated?

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/bondingManager.ts
> +    // no existing delegate && delegator has bondedAmount then it is rebonding
can we just make this comment  `// delegator rebonding` , I don't think we need to repeat the if statement expressed below in the comment. Let's be brief !

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/bondingManager.ts
> +  let totalActiveStake = bondingManager.getTotalBonded()
we can just assign thi return values straight to `protocol.totalActiveStake`  at L345  and remove this line I believe ?

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/bondingManager_LIP11.ts
> +  protocol.totalActiveStake = totalActiveStake
same comment as above about just assigning directly instead of first declaring `totalActiveStake`

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/bondingManager_LIP11.ts
> +  protocol.totalActiveStake = totalActiveStake
same comment as above about just assigning directly instead of first declaring totalActiveStake

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/bondingManager_LIP11.ts
> +  protocol.totalActiveStake = totalActiveStake
same comment as above about just assigning directly instead of first declaring totalActiveStake

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/poll.ts
> +  let vote = Vote.load(voteId) || new Vote(voteId)
In the case a user votes twice on the same poll , could we remove the old vote from the tally and just create a new vote instead of mutating the old one? That should simplify/shorten this function a little bit. I'm not sure if this is actually possible though , eg `vote.remove()` ?

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/poll.ts
> +    if (v.choiceID == 0) {
WDYT about turning this into a `switch` statement?

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +  if (
What do you think about reversing this `if`statement to check for the bad case and `return`  so we don't have to encapsulate the entire function body in the `if` statement

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +      let protocol = Protocol.load('0') || new Protocol('0')
what do you think about moving this top-level and doing 

```
if (poll.endBlock <= event.block.number) return;
```

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +      } else {
if the changes above are implemented we can unnest  this as well and do 

```
if (delegator.id !== event.params.transcoder.toHex()) return;
// rest of function body here 
```

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +export function updatePollTallyOnBond(event: BondEvent): void {
see comment above about preventing `if else` nesting by first checking the bad case and possibly returning, which allows the happy case of the function to be unnested, improving readability. We can apply the same logic here.

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +    if (poll.endBlock > event.block.number) {
see comment above about preventing if else nesting by first checking the bad case and possibly returning, which allows the happy case of the function to be unnested, improving readability. We can apply the same logic here.

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +  if (voterAddress == event.params.delegator.toHex()) {
see comment above about preventing if else nesting by first checking the bad case and possibly returning, which allows the happy case of the function to be unnested, improving readability. We can apply the same logic here.

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +    if (poll != null && poll.endBlock > event.block.number) {
see comment above about preventing if else nesting by first checking the bad case and possibly returning, which allows the happy case of the function to be unnested, improving readability. We can apply the same logic here.

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +    if (poll != null && poll.endBlock > event.block.number) {
see comment above about preventing if else nesting by first checking the bad case and possibly returning, which allows the happy case of the function to be unnested, improving readability. We can apply the same logic here.

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/roundsManager.ts
> +  protocol.totalActiveStake = totalActiveStake
let's assign this directly instead of first declaring `totalActiveStake`

2020-04-22 13:15 UTC, kyriediculous commented on packages/subgraph/src/mappings/roundsManager_streamflow.ts
> +  protocol.totalActiveStake = totalActiveStake
let's assign this directly instead of first declaring totalActiveStake

2020-04-22 13:56 UTC, adamsoffer commented on packages/subgraph/src/mappings/dynamic.ts
> -      if (!vote) {
ah yeah this file is outdated. Sorry. I renamed this file to `pollTallyHandlers.ts` where I make this check

2020-04-22 14:02 UTC, adamsoffer commented on packages/subgraph/src/mappings/dynamic.ts
> +  if (voterAddress == event.params.delegator.toHex()) {
This is also outdated and has been changed.

2020-04-22 14:03 UTC, adamsoffer commented on packages/subgraph/src/mappings/dynamic.ts
> +  if (voterAddress == event.params.delegator.toHex()) {
This is also outdated and has been changed. See `pollTallyHandlers.ts`

2020-04-22 14:03 UTC, adamsoffer commented on packages/subgraph/src/mappings/dynamic.ts
> -      // return if voter didn't vote in this specific poll
outdated

2020-04-22 14:05 UTC, adamsoffer commented on packages/subgraph/test/integration/test.js
> +    await Poll.methods.vote(1).send({ from: delegator3 })
Nice yeah I like that.

2020-04-22 14:05 UTC, adamsoffer commented on packages/subgraph/test/integration/test.js
> +      subgraphPollData.data.transcoder1VoteChoice[0].choiceID,
Nice will do

2020-04-22 14:07 UTC, adamsoffer commented on packages/subgraph/src/mappings/bondingManager.ts
> +  transcoder.pendingPricePerSegment = event.params.pendingPricePerSegment
I removed these fields in a previous commit because they're deprecated, then realized I'll need them in the future to calculate historical reward shares.

2020-04-22 14:07 UTC, adamsoffer commented on packages/subgraph/src/mappings/bondingManager.ts
> +  transcoderUpdated.feeShare = event.params.pendingFeeShare
same as above

2020-04-22 14:08 UTC, adamsoffer commented on packages/subgraph/src/mappings/bondingManager.ts
> +    // no existing delegate && delegator has bondedAmount then it is rebonding
totally

2020-04-22 14:09 UTC, adamsoffer commented on packages/subgraph/src/mappings/bondingManager.ts
> +  let totalActiveStake = bondingManager.getTotalBonded()
yeah let's do that

2020-04-30 17:06 UTC, yondonfu requested changes

2020-04-30 17:06 UTC, yondonfu commented on packages/subgraph/patches/@graphprotocol+graph-cli+0.18.0.patch
> +     let getNonNullable = `return ${typesCodegen.valueToAsc('value', fieldValueType)}`
We have this patch here because it hasn't landed in the latest release of graph-cli?

2020-04-30 17:06 UTC, yondonfu commented on packages/subgraph/schema.graphql
> +enum PollChoice @entity {
I know that the details of how the enum is represented internally (as integers for example) are not leaked to the client, but might be good for consistency to put `Yes` first to match the description in the LIP-16 spec and the ordering in [livepeer_cli](https://github.com/livepeer/go-livepeer/blob/acea1c17be1cc319e808d1bf70f58bf6de8adc48/eth/types/contracts.go#L104).

2020-04-30 17:06 UTC, yondonfu commented on packages/subgraph/networks.yaml
> +    pollCreator:
Adding this note as a reminder to myself that this is a placeholder that needs to be updated once the contract is deployed on mainnet.

2020-04-30 17:06 UTC, yondonfu commented on packages/subgraph/src/mappings/bondingManager.ts
> +    let totalActiveStake = bondingManager.getTotalBonded()
The value returned by `bondingManager.getTotalBonded()` will only be updated when a new round is initialized. The BondingManager will keep track of stake that is pending activation and deactivation during a round and when a new round is initialized it will update the active stake for the new round to take into account stake that was pending activation or deactivation in the previous round. So, I think we only need to update the `totalActiveStake` field in the Protocol entity when a new round is initialized.

2020-04-30 17:06 UTC, yondonfu commented on packages/subgraph/src/mappings/pollCreator.ts
> +  poll.tally = event.params.poll.toHex()
Just to clarify - we should just be setting `tally` to the poll address because the ID of the PollTally instance will be the poll address?

2020-04-30 17:06 UTC, yondonfu commented on packages/subgraph/src/mappings/poll.ts
> +        event.params.voter.toHex() != delegator.delegate
`delegator.delegate` -> `delegate` since `delegate` is already declared?

2020-04-30 17:06 UTC, yondonfu commented on packages/subgraph/src/mappings/poll.ts
> +  if (pollVotes.indexOf(voteId) == -1) {
IIUC we are not just checking if there is already a Vote saved here i.e. `Vote.load(voteId) == null` because if a delegator votes then a Vote will be saved for its orchestrator even if the orchestrator itself has not voted yet. This `indexOf` call will get more expensive as the # of voters increases which likely won't be an issue at this stage, but I wonder if there is an alternative that doesn't involve `indexOf`.

Since choiceID is nullable, could we check if the old choiceID (before updating it starting on L24) was null? If the old choiceID was null then this would be the first time the voter is voting in the poll.

2020-04-30 17:06 UTC, yondonfu commented on packages/subgraph/src/mappings/poll.ts
> +    vote.choiceID = 'Yes'
Could we use the `PollChoice` enum here? i.e. `vote.choiceID = PollChoice.Yes`

2020-04-30 17:06 UTC, yondonfu commented on packages/subgraph/subgraph.template.yaml
> +      # callHandlers:
Don't we need these call handlers for the period of time on mainnet when the necessary data wasn't available in events yet?

2020-04-30 17:06 UTC, yondonfu commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +          delegateVote.voteStake = transcoder.totalStake
Isn't this case handled already?

- If a delegate has voted already, then this handler will fire for the delegate and L38 will update its vote stake
- If a delegator has not voted yet, then its vote stake will be updated by the vote handler when the delegate casts a vote

2020-04-30 17:06 UTC, yondonfu commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +          delegateVote.voteStake = transcoder.totalStake
Isn't this case handled already?

- If a delegate has voted already, then this handler will fire for the delegate and L06 will update its vote stake
- If a delegator has not voted yet, then its vote stake will be updated by the vote handler when the delegate casts a vote

2020-04-30 17:06 UTC, yondonfu commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +          delegateVote.voteStake = transcoder.totalStake
Ditto other comments from other handlers about already handling this case.

2020-04-30 17:06 UTC, yondonfu commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +        let protocol = Protocol.load('0') || new Protocol('0')
A lot of the logic for this case seems to be the same across all the handlers in this file i.e. call pendingStake, update the delegate's non vote stake, update the delegator's vote stake. Perhaps we can extract this into a helper?

2020-04-30 17:06 UTC, yondonfu commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +    if (poll != null && poll.endBlock > event.block.number) {
Would the poll ever be null since this handler is only setup if the voter voted in the poll already? Also don't see this check in the other handlers.

2020-04-30 17:06 UTC, yondonfu commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +      if (!vote) {
Wouldn't this always be non-null since this handler is only setup if the voter voted?

2020-04-30 17:06 UTC, yondonfu commented on packages/subgraph/test/integration/test.js
> +      .send({ gas: 1000000, from: transcoder1 })
Looks like web3.js allows you to set a default gas limit for all txs sent for a contract instance ([docs](https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html#options)). That could help avoid having to set the gas limit for all the txs in this test file.

2020-05-04 14:36 UTC, kyriediculous commented on packages/subgraph/src/mappings/dynamic.ts
> +  if (voterAddress == event.params.delegator.toHex()) {
It seems like the if-else structure persisted across renaming but I left similar comments on the updated version as well. Note that this won't actually change the logic just code readability so it's really nitpicking and might be personal opinion as well so I'll leave it up to you whether you'd like to address the code structure or not.

2020-05-06 22:32 UTC, adamsoffer commented on packages/subgraph/docker-compose.yml
> +      ethereum: 'development:http://host.docker.internal:8545'
Updated README 👍

2020-05-06 22:32 UTC, adamsoffer commented on packages/subgraph/schema.graphql
> +  "The voter that casted the vote"
Changed to vote caster in latest

2020-05-06 22:33 UTC, adamsoffer commented on packages/subgraph/schema.graphql
> +  "The voter address"
Updated all comments and removed "the" prefixes for brevity

2020-05-06 22:34 UTC, adamsoffer commented on packages/subgraph/src/mappings/dynamic.ts
> +  if (voterAddress == event.params.delegator.toHex()) {
I've adopted this go idiomatic across the board in latest commit 👍

2020-05-06 22:34 UTC, adamsoffer commented on packages/subgraph/src/mappings/dynamic.ts
> -      // return if voter didn't vote in this specific poll
done

2020-05-06 22:35 UTC, adamsoffer commented on packages/subgraph/src/mappings/bondingManager.ts
> +    // no existing delegate && delegator has bondedAmount then it is rebonding
Changed in latest 👍

2020-05-06 22:36 UTC, adamsoffer commented on packages/subgraph/src/mappings/bondingManager_LIP11.ts
> +  protocol.totalActiveStake = totalActiveStake
Done. Also, per Yondon this only needs to get set on NewRound events, so I removed from this handler altogether.

2020-05-06 22:37 UTC, adamsoffer commented on packages/subgraph/src/mappings/bondingManager_LIP11.ts
> +  protocol.totalActiveStake = totalActiveStake
Same as above.

2020-05-06 22:37 UTC, adamsoffer commented on packages/subgraph/src/mappings/bondingManager_LIP11.ts
> +  protocol.totalActiveStake = totalActiveStake
Same comment as above.

2020-05-06 22:38 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +  if (
I dig it. I've adopted this go idiomatic throughout.

2020-05-06 22:38 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +      let protocol = Protocol.load('0') || new Protocol('0')
done

2020-05-06 22:40 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +export function updatePollTallyOnBond(event: BondEvent): void {
done

2020-05-06 22:41 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +    if (poll.endBlock > event.block.number) {
done

2020-05-06 22:41 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +  if (voterAddress == event.params.delegator.toHex()) {
done

2020-05-06 22:41 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +    if (poll != null && poll.endBlock > event.block.number) {
done

2020-05-06 22:41 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +    if (poll != null && poll.endBlock > event.block.number) {
done

2020-05-06 22:41 UTC, adamsoffer commented on packages/subgraph/src/mappings/roundsManager.ts
> +  protocol.totalActiveStake = totalActiveStake
done

2020-05-06 22:41 UTC, adamsoffer commented on packages/subgraph/src/mappings/roundsManager_streamflow.ts
> +  protocol.totalActiveStake = totalActiveStake
done

2020-05-06 22:42 UTC, adamsoffer commented on packages/subgraph/patches/@graphprotocol+graph-cli+0.18.0.patch
> +     let getNonNullable = `return ${typesCodegen.valueToAsc('value', fieldValueType)}`
Yeah exactly. I need to follow up with Leo from the Graph about landing a fix for this in `graph-cli` so we can remove this patch.

2020-05-06 22:42 UTC, adamsoffer commented on packages/subgraph/schema.graphql
> +enum PollChoice @entity {
Done

2020-05-06 22:43 UTC, adamsoffer commented on packages/subgraph/src/mappings/bondingManager.ts
> +    let totalActiveStake = bondingManager.getTotalBonded()
Makes sense. I've removed it from all the handlers with the exception of `newRound`.

2020-05-06 22:44 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollCreator.ts
> +  poll.tally = event.params.poll.toHex()
Yeah exactly.

2020-05-06 22:45 UTC, adamsoffer commented on packages/subgraph/src/mappings/poll.ts
> +        event.params.voter.toHex() != delegator.delegate
Updated to use `delegate.id`.

2020-05-06 22:46 UTC, adamsoffer commented on packages/subgraph/src/mappings/poll.ts
> +  if (pollVotes.indexOf(voteId) == -1) {
Yeah good call that would be more performant. I pushed up an update that instead checks if the old `choiceID` is null.

2020-05-06 22:47 UTC, adamsoffer commented on packages/subgraph/src/mappings/poll.ts
> +    vote.choiceID = 'Yes'
For some reason the autogenerated exported types don't include enums, so I have to hard code 🤷‍♂️

2020-05-06 22:48 UTC, adamsoffer commented on packages/subgraph/subgraph.template.yaml
> +      # callHandlers:
Yeah we do. I temporarily commented them out because ganache and rinkeby don't support them. I just pushed up an update that conditionally outputs the callHandlers in the subgraph.yaml manifest based on the network name.

2020-05-06 22:49 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +          delegateVote.voteStake = transcoder.totalStake
Good call. Removed.

2020-05-06 22:49 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +          delegateVote.voteStake = transcoder.totalStake
ditto. removed.

2020-05-06 22:49 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +          delegateVote.voteStake = transcoder.totalStake
ditto. removed.

2020-05-06 22:51 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +        let protocol = Protocol.load('0') || new Protocol('0')
Yeah good point. I pushed up an update that abstracts this logic into its own function called `updatePollTally` used by the `updatePollTallyOnUnbond` and `updatePollTallyOnRebond`.

2020-05-06 22:51 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +    if (poll != null && poll.endBlock > event.block.number) {
Yeah you're right the poll should never be null. Removed.

2020-05-06 22:51 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +      if (!vote) {
Yup. Removed this check in latest.

2020-05-07 04:03 UTC, adamsoffer commented on packages/subgraph/src/mappings/poll.ts
> +    if (v.choiceID == 0) {
I found that switch case statements don't compile with the assembly script compiler for some reason 🤷‍♂️

2020-05-07 04:12 UTC, adamsoffer commented on packages/subgraph/test/integration/test.js
> +    await Poll.methods.vote(1).send({ from: delegator3 })
done

2020-05-07 04:12 UTC, adamsoffer commented on packages/subgraph/test/integration/test.js
> +      subgraphPollData.data.transcoder1VoteChoice[0].choiceID,
done

2020-05-07 13:43 UTC, adamsoffer commented on packages/subgraph/src/mappings/poll.ts
> +  let vote = Vote.load(voteId) || new Vote(voteId)
We could but not sure it would shorten the function all that much. The only thing we change at this point if a user votes a second time is the votes choiceID.

2020-05-07 15:25 UTC, kyriediculous requested changes
Changes look good so far :+1:  , one minor comment regarding setting a default `gas` value on the contract instance when  we create it.

2020-05-07 15:25 UTC, kyriediculous commented on packages/subgraph/test/integration/test.js
> +const defaults = { gas: 1000000 }
Can we use this value as a fallback as per [this comment](https://github.com/livepeer/livepeerjs/pull/611#discussion_r418158455) 

That way we don't have to deconstruct `...defaults`  when we make a `send` we can just overwrite the default `from` address.  

___________

We can add this default to the `web3.eth.Contract()` call 

`web3.eth.Contract(ABI, address, options)`  where `options` is the object of transaction options of which some will be used as fallbacks for calls/sends 

https://web3js.readthedocs.io/en/v1.2.5/web3-eth-contract.html#new-contract

2020-05-07 15:29 UTC, kyriediculous commented
Looks like CI Is failing because it can't find a remote ethereum node. 

I think we need an additional job in CircleCI that spins up the ganache with protocol image before we run the tests.

2020-05-07 15:46 UTC, yondonfu requested changes

2020-05-07 15:46 UTC, yondonfu commented on packages/subgraph/src/mappings/poll.ts
> +        vote.voteStake = pendingStake
I think the code in this else block will give vote stake to a delegator even if its delegate is not a registered orchestrator. I think this code only be executed if the delegate is a registered orchestrator (along with the code starting at L75)?

2020-05-07 15:46 UTC, yondonfu commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +  if (voterAddress == event.params.delegator.toHex()) {
If the voter is a registered orchestrator I think the code starting on L234 will run and then the code in this block will run overwriting the vote stake with the pending stake of the registered orchestrator as opposed to its total stake?

2020-05-07 16:33 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +  if (voterAddress == event.params.delegator.toHex()) {
There's a check on L248 that only runs if the voter isn't delegated to itself (a registered O). We can probably combine the conditionals on L241 and 248.

2020-05-07 17:54 UTC, yondonfu commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +  if (voterAddress == event.params.delegator.toHex()) {
Ah woops missed that check. Combining the conditionals sounds good.

2020-05-07 18:14 UTC, adamsoffer commented on packages/subgraph/src/mappings/poll.ts
> +        vote.voteStake = pendingStake
Do we only want to count stake with registered transcoders? I'm actually not sure if that explicitly mentioned in LIP-16. We make the distinction between inactive and active stake, but is stake with an unregistered delegate considered inactive?

2020-05-07 18:26 UTC, adamsoffer commented on packages/subgraph/src/mappings/poll.ts
> +        vote.voteStake = pendingStake
My assumption was only registered orchestrators, but just want to double check!

2020-05-07 18:54 UTC, yondonfu commented on packages/subgraph/src/mappings/poll.ts
> +        vote.voteStake = pendingStake
Hm LIP-16 actually just states that stake (both inactive and active) receives voting power. Under that definition, all stake, regardless of whether it is delegated to a registered orchestrator or not receives voting power. That actually seems fine to me then. Nvm!

2020-05-09 19:05 UTC, adamsoffer commented
@yondonfu hooray all checks have passed ✅. This is ready to merge once we have the mainnet contract address. Should we deploy latest rinkeby contract with the state variable name change (`threshold` to `quota`) and rsync subgraph? Then I can update the graphql query in the UI with the new field name.

2020-05-09 19:46 UTC, yondonfu commented
> Should we deploy latest rinkeby contract with the state variable name change (threshold to quota) and rsync subgraph?

Deployed at [0x149805EF90FaDA12D27e8a020b6c138F3d86A9a3](https://rinkeby.etherscan.io/address/0x149805ef90fada12d27e8a020b6c138f3d86a9a3).

WDYT about resolving the conflicts with master, re-syncing the Rinkeby subgraph, merging and then updating the mainnet address in a separate PR?

2020-05-09 20:41 UTC, adamsoffer commented on packages/subgraph/test/integration/test.js
> +const defaults = { gas: 1000000 }
done!

2020-05-10 00:12 UTC, kyriediculous commented
Thanks for fixing up CI @yondonfu !

2020-05-10 00:14 UTC, adamsoffer commented on packages/subgraph/test/integration/test.js
> +      .send({ gas: 1000000, from: transcoder1 })
done!

2020-05-10 00:16 UTC, adamsoffer commented on packages/subgraph/truffle.js
> +}
I noticed the graph uses truffle in their integration tests which is what I based this on. https://github.com/graphprotocol/graph-node/tree/master/tests/integration-tests

I think using truffle could come in handy at some point since it's already working probably best to leave as is at this point.

2020-05-10 00:18 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +  if (voterAddress == event.params.delegator.toHex()) {
done

2020-05-10 00:27 UTC, kyriediculous commented on packages/subgraph/truffle.js
> +}
I'm fine leaving it as is although I find it a weird decision on their part. 

Truffle really shines as a smart contract development suite but is very opinionated about things like directory structure and to fully leverage truffle your deployed addresses need to be in the ABI files. 

Right now it just injects web3 and auto-connects the provider to the right network through the truffle config file. Since we just use a single network to run the tests that's a lot of package overhead. 

The main reason I'm fine with it is that it's a dev dependency and not included in the production build. Perhaps interesting features could come of it in the future, we'll see. It doesn't hurt keeping it either.

2020-05-10 00:28 UTC, adamsoffer commented on packages/subgraph/truffle.js
> +}
yeah that makes sense. I'm down to remove in a follow-up PR.

2020-05-10 17:20 UTC, adamsoffer commented
Heads up I’ve updated and deployed subgraph + UI with latest Rinkeby PollCreator contract and created a new test poll.

2020-05-10 17:38 UTC, yondonfu commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +    vote.voteStake = pendingStake
I think pendingStake == event.params.bondedAmount here so we could just use event.params.bondedAmount and remove the pendingStake variable/function call?

2020-05-10 17:38 UTC, yondonfu commented on packages/subgraph/test/integration/test.js
> +    Poll.methods.vote(1).send({ from: delegator6 })
Missing an `await` here

2020-05-10 17:38 UTC, yondonfu commented on packages/subgraph/test/integration/test.js
> +    Poll.methods.vote(1).send({ from: delegator6 })
Proposed change in #689

2020-05-10 17:38 UTC, yondonfu commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +    vote.voteStake = pendingStake
Proposed change in #689

2020-05-10 18:14 UTC, adamsoffer commented on packages/subgraph/src/mappings/pollTallyHandlers.ts
> +    vote.voteStake = pendingStake
ah nice one.

2020-05-10 20:44 UTC, adamsoffer commented
I've updated subgraph manifest with newly deployed mainnet address and startblock and deployed to our mainnet "canary" subgraph. It's currently syncing and should be up to date in a few hours or so. https://thegraph.com/explorer/subgraph/livepeer/livepeer-canary?version=pending

2020-05-10 22:08 UTC, yondonfu approved these changes
LGTM :shipit: after resolving conflicts with master

2020-05-11 00:03 UTC, merged