explorer: batchClaimEarnings gas optimisations
livepeer/livepeer-monorepo pull request #636
Opened 2020-04-18 10:52 UTC by kyriediculous

**What does this pull request do? Explain your changes. (required)**
This PR optimises gas usage for `batchClaimEarnings`. 

User reports have stated that when using metamask it would often set a very high tx gas limit or even default to the block gas limit. 

**Specific updates (required)**
- 3a3d415 - Add a gas estimation by doing an `eth_estimategas` RPC call before sending the transaction. This should prevent metamask from defaulting to high values.
- 9b5c485 - Change `MAX_EARNINGS_CLAIMS_ROUNDS` to `50`
  This will increase the number of transactions to be approved in metamask if there's a high number of rounds to claim for but it makes a tradeoff to better play into miner economics for gas price optimisation. Transactions with high gas limits (> 10%-20% of the block gas limit) are less likely to be included in blocks if they don't have a higher gas prices attached to them than what the average for a bunch of smaller transactions would be. However people are more inclined to commit to a higher gas price for smaller transactions to get faster confirmations. Leaving large , low gas price transactions in the memory pool for a long time.  

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**
Fixes #597

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-04-18 16:07 UTC, adamsoffer requested changes

2020-04-18 16:07 UTC, adamsoffer commented on packages/explorer-2.0/apollo/resolvers/Mutation.tsx
> +        {
You're passing the `gas` value as a parameter to the `claimEarnings` method which it doesn't accept. Try passing it as an option in the `request` method inside the `makeBatchRequest` function. See [here](https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html#methods-mymethod-send).

2020-04-18 16:07 UTC, adamsoffer commented on packages/explorer-2.0/lib/utils.tsx
> +export const MAX_EARNINGS_CLAIMS_ROUNDS = 50
I use this constant to determine whether to show the claim earnings banner when it's been over 100 rounds. Let's add a separate constant here called `BATCH_TOTAL` and use that instead.

2020-04-18 16:07 UTC, adamsoffer commented on packages/explorer-2.0/lib/utils.tsx
> +export const MAX_EARNINGS_CLAIMS_ROUNDS = 50
Sidenote: eventually I should really fetch `MAX_EARNINGS_CLAIMS_ROUNDS` from contract storage instead of hard coding.

2020-04-19 22:51 UTC, kyriediculous commented on packages/explorer-2.0/apollo/resolvers/Mutation.tsx
> +        {
I had to rewrite the function to make it work because of a couple of things:

- We can't estimate the gas within the loop, this will estimate the gas correctly only for the first iteration (for the next iterations it would estimate the gas as if we were claiming `i*MAX_BATCH_CLAIM_ROUNDS` rounds). 

- Previously there were two loops where one could be used 

- The previous closure function did not provide us access to the arguments used for a certain call we add to the batch to estimate the gas. While this might be retrievable from the object there was still the first issue to deal with

2020-04-19 22:52 UTC, kyriediculous commented on packages/explorer-2.0/lib/utils.tsx
> +export const MAX_EARNINGS_CLAIMS_ROUNDS = 50
introduced `MAX_BATCH_CLAIM_EARNINGS = 50`

2020-04-19 22:52 UTC, kyriediculous commented
I rebased and force pushed already because the diff is so vastly  different from the original commits in this PR.

2020-04-20 14:42 UTC, adamsoffer commented on packages/explorer-2.0/apollo/resolvers/Mutation.tsx
> +        {
Nice

2020-04-20 14:42 UTC, adamsoffer approved these changes

2020-04-20 14:43 UTC, adamsoffer commented
Just tested on the preview URL. Looks and works great! 🚢

2020-04-20 17:41 UTC, merged