Tracking API Token's `lastSeen`
livepeer/livepeer-monorepo pull request #639
Opened 2020-04-22 13:01 UTC by ya7ya

**What does this pull request do? Explain your changes. (required)**
Tracks last time an API token was used

**Specific updates (required)**
- updated schema.yaml
- added non-blocking `tracking.record` function

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**

Fixes https://github.com/livepeer/livepeerjs/issues/618

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-04-22 18:43 UTC, ya7ya commented
This is good to go, I'll remove the `console.logs` once it's gets reviewed :smile:

2020-04-22 21:19 UTC, iameli requested changes
Cool, just some cleanup and a tweak to the timestamp format.

Do you want to find a "time ago" library we can use for that column on the front-end? A quick Googling pointed me toward this one but I'm sure there's many out there https://www.npmjs.com/package/timeago.js

2020-04-22 21:19 UTC, iameli commented on packages/api/src/schema/schema.yaml
> +          example: 2020-04-22T12:35:13.297Z
Let's do these as numbers — in the password reset example we've already got a `Date.now()`-style "milliseconds since epoch" time in the database. I think that's probably the simplest solution unless we needed timezone-aware stuff for some reason

2020-04-22 21:19 UTC, iameli commented on packages/api/src/middleware/tracking.js
> +    console.log('debug: tracking record trigger')
This can go away

2020-04-22 21:19 UTC, iameli commented on packages/api/src/middleware/tracking.js
> +      console.log('all good')
Prolly don't need the catch block at all, and the error block can just log something

2020-04-22 21:19 UTC, iameli commented on packages/api/src/middleware/tracking.js
> +// function trackingFactory(params) {
Can clean up a little here

2020-04-23 20:55 UTC, iameli requested changes
very minor changes

2020-04-23 20:55 UTC, iameli commented on packages/api/src/middleware/tracking.js
> +    store.replace(tokenObject).then((_) => {
I think we should log an error on the `.catch()` block here — otherwise that'll result in an uncaught promise that crashes the server!

2020-04-23 20:55 UTC, iameli commented on packages/api/src/schema/schema.yaml
> +          type: string
```suggestion
          type: number
```

2020-04-23 20:55 UTC, iameli commented on packages/livepeer.com/www/components/TokenTable/index.tsx
> +          const formattedLastSeen = `${new Date(lastSeen).toLocaleDateString()} ${new Date(lastSeen).toLocaleTimeString()}`
Cool, good enough for now

2020-04-23 21:08 UTC, ya7ya commented on packages/livepeer.com/www/components/TokenTable/index.tsx
> +          const formattedLastSeen = `${new Date(lastSeen).toLocaleDateString()} ${new Date(lastSeen).toLocaleTimeString()}`
I prefer this way to `ago` because when you're debugging an API webhook, you wanna see exact absolute timestamps.

2020-04-23 22:25 UTC, iameli approved these changes
LGTM!

2020-04-23 22:57 UTC, merged