refactoring geolocate and `/api/broadcaster` for the new setup
livepeer/livepeer-monorepo pull request #640
Opened 2020-04-22 14:50 UTC by ya7ya

**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

- 
- 
- 

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-04-22 21:35 UTC, iameli requested changes
Sweet, few tweaks

2020-04-22 21:35 UTC, iameli commented on packages/api/src/middleware/geolocate.js
> +function geoLocateFactory (params) {
I'd like to have individual controllers opt in to the `first` behavior in the `params` — we'll want `/api/broadcaster` to do `geolocate({first: true})` but `/api/geolocate` should give us information about every region. I like the query parameter, though! `/api/geolocate?first=true` will be useful.

2020-04-22 21:35 UTC, iameli commented on packages/api/src/middleware/geolocate.js
> +    let first = req.query.first || true
This won't produce the expected results with `GET /api/geolocate?first=false`, as the string "false" is truthy. Perhaps we have explicit checks for `"true"` and `"false"`?

2020-04-22 21:35 UTC, iameli commented on packages/api/src/middleware/geolocate.js
> +    console.log('region populated: ', ret)
can remove

2020-04-22 21:35 UTC, iameli commented on packages/api/src/parse-cli.js
> +          default: ['esh.livepeer.live', 'chi.livepeer-ac.live'],
I don't think we need a default value here, we wouldn't want external users hitting our API servers anyway. And we want to use the hardcoded list if this isn't provided.

2020-04-22 21:35 UTC, iameli commented on packages/api/src/parse-cli.js
> +        ingests: {
Hmmmmm contemplating the name here. Right now they're mostly used for ingest, but they might be used later for other things as well... maybe `region`? So it can be called like
`node api.js --region chi.livepeer-ac.live --region esh.livepeer.live`

2020-04-22 21:35 UTC, iameli commented on packages/api/src/parse-cli.js
> +          type: 'array',
So one trick here is that we want this to be able to be configured entirely with environment variables in the worker context. (And elsewhere.) `yargs` doesn't support this for its array types by default, but [I wrote a workaround in this ticket](https://github.com/yargs/yargs/issues/821#issuecomment-614434134). I think it'll work if you just include that `coerce` function verbatim.

2020-04-23 20:22 UTC, iameli requested changes
Cool, just a little cleanup and a switch from string to number for dates

2020-04-23 20:22 UTC, iameli commented on packages/api/src/app-router.js
> +    console.log('debug: hooking up route ', name)
cleanup

2020-04-23 20:22 UTC, iameli commented on packages/api/src/middleware/tracking.js
> +// function trackingFactory(params) {
cleanup

2020-04-23 20:22 UTC, iameli commented on packages/api/src/middleware/tracking.js
> +      console.log('all good')
cleanup

2020-04-23 20:22 UTC, iameli commented on packages/api/src/middleware/tracking.js
> +      // TODO Log error
```suggestion
      console.error("error updating user API token", e)
```

2020-04-23 20:22 UTC, iameli commented on packages/api/src/middleware/tracking.js
> +    tokenObject.lastSeen = new Date()
```suggestion
    tokenObject.lastSeen = Date.now()
```

2020-04-23 20:22 UTC, iameli commented on packages/api/src/schema/schema.yaml
> +          example: 2020-04-22T12:35:13.297Z
```suggestion
          type: number
          example: 1587673332547
```

2020-04-23 20:27 UTC, iameli commented
Oh oops, looks like I reviewed the `lastSeen` stuff here — want to either merge the two branches or rebase out `lastSeen` from this one?

2020-04-24 11:37 UTC, ya7ya commented
I rebased the tracking features out to keep the PR clean :+1: , this is ready for review

2020-04-24 18:38 UTC, iameli commented on packages/api/src/schema/schema.yaml
> +<<<<<<< HEAD
Ruh roh

2020-04-24 18:41 UTC, ya7ya commented on packages/api/src/schema/schema.yaml
> +<<<<<<< HEAD
sorry :facepalm:, :coffee:  fixed

2020-04-26 23:05 UTC, iameli approved these changes
LGTM!

2020-04-26 23:25 UTC, merged