Combine steps 3 and 4
livepeer/livepeer-monorepo pull request #651
Opened 2020-04-27 21:44 UTC by ericxtang

**What does this pull request do? Explain your changes. (required)**

Based on @j0sh's comment, we can pipe the POST result into `munpack`, reducing a step in the tutorial :)

2020-04-27 21:51 UTC, j0sh commented on packages/livepeer.com/www/docs/index.mdx
>  --27bee784e2f2672487f5
If we do keep this section in, this probably also needs the original HTTP response headers (eg, full output of `curl -i ...`) in order to identify and extract the `boundary` ? If we don't want to bother describing the response in full, then we might as well remove this section.

2020-04-27 21:51 UTC, wohlner reviewed
I suggest moving munpack directions up to above where the command is used.

2020-04-27 21:51 UTC, wohlner commented on packages/livepeer.com/www/docs/index.mdx
> +_We used [`munpack`](https://linux.die.net/man/1/munpack) to unpack the multipart
What do you think about moving the munpack instructions to line 84, at the start of step 3. This is directly before the user is required to munpack. Otherwise, many will surely get errors and not make it to the bottom of the final step.

2020-04-27 21:57 UTC, wohlner commented on packages/livepeer.com/www/docs/index.mdx
> +_We used [`munpack`](https://linux.die.net/man/1/munpack) to unpack the multipart
Also, combining steps 3 and 4 combines the transcoding, unpacking and playback into one step. That's a lot for a tutorial. I fear we are missing out on the "aha" moment of unpacking and playing back the segment. If others feel differently, I won't be stubborn about it. But let's talk about it before deploying this change to prod.

2020-04-27 22:11 UTC, j0sh commented on packages/livepeer.com/www/docs/index.mdx
> +_We used [`munpack`](https://linux.die.net/man/1/munpack) to unpack the multipart
The fewer steps, the better, especially for a tutorial that's designed to get folks up and running quickly.

Unpacking isn't particularly enlightening unless you're looking to actively develop against the intermediate results. And even then, the format should be properly documented, which it is not right now. Incomplete / confusing documentation is worse than no documentation, because it just wastes people's time.

2020-04-27 22:15 UTC, ericxtang commented on packages/livepeer.com/www/docs/index.mdx
> +_We used [`munpack`](https://linux.die.net/man/1/munpack) to unpack the multipart
Moved the `munpack` instructions based on @wohlner's suggestion.  I think the user can still play back the result after the combined step, and have the "aha" moment.

2020-04-27 22:22 UTC, wohlner commented on packages/livepeer.com/www/docs/index.mdx
> +_We used [`munpack`](https://linux.die.net/man/1/munpack) to unpack the multipart
Make it future tense: "We _will_ use munpack to unpack the multipart API response." Otherwise it looks good.

2020-04-27 22:22 UTC, wohlner requested changes
Make it future tense, but otherwise all good.

2020-04-27 22:23 UTC, j0sh commented on packages/livepeer.com/www/docs/index.mdx
> +_We used [`munpack`](https://linux.die.net/man/1/munpack) to unpack the multipart
Or just "We use munpack" ... ?

2020-04-28 00:19 UTC, ericxtang commented
Updated according to comments by @wohlner and @j0sh.

2020-04-28 14:58 UTC, ericxtang commented
@wohlner and @j0sh can you give a review today so we can merge it quickly?

2020-04-28 18:16 UTC, j0sh approved these changes

2020-04-28 23:54 UTC, merged