ar/adding user list page for admins
livepeer/livepeer-monorepo pull request #678
Opened 2020-05-04 20:52 UTC by angyangie

**What does this pull request do? Explain your changes. (required)**
- Allows admin user only to see all users created on Livepeer
- Allows admin user to make another user on the list an admin

_In the future, will need to:(NOT included in this PR)_
- Paginate users
- Add other admin features
- Create side menu to allow for clicking into specific sections of the admin dashboard, like `api-tokens`, `users`, and any others added

**Specific updates (required)**
https://github.com/livepeer/livepeerjs/issues/655

**How did you test each of these updates (required)**
Locally

**Does this pull request close any open issues?**
https://github.com/livepeer/livepeerjs/issues/655

**Screenshots (optional):**

<img width="1680" alt="Screen Shot 2020-05-04 at 4 29 44 PM" src="https://user-images.githubusercontent.com/16169518/81012233-34449500-8e27-11ea-979b-ce0b25b6f2bf.png">

<img width="1335" alt="Screen Shot 2020-05-04 at 4 44 45 PM" src="https://user-images.githubusercontent.com/16169518/81012243-373f8580-8e27-11ea-9a52-f3ecf53e0be0.png">

<img width="1343" alt="Screen Shot 2020-05-04 at 4 44 56 PM" src="https://user-images.githubusercontent.com/16169518/81012261-3eff2a00-8e27-11ea-8ad6-45500360f366.png">

**Checklist:**
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-05-04 21:22 UTC, wohlner commented
Repeating from discord: Eventually we will have to add some sort of pagination. For now though, I'm ok with it taking a while to load if we have a bunch of users.

2020-05-05 19:09 UTC, darkdarkdragon requested changes

2020-05-05 19:09 UTC, darkdarkdragon commented on packages/livepeer.com/www/hooks/use-api.tsx
> +      opts = {}
It is not used, probable should be removed

2020-05-05 19:09 UTC, darkdarkdragon commented on packages/livepeer.com/www/components/TokenTable/index.tsx
> +          <strong>Api Tokens</strong>
Maybe 'Streams' title should be made strong too?

2020-05-05 19:10 UTC, darkdarkdragon commented
@angyangie Maybe we should add button `Remove admin rights`?

2020-05-05 20:08 UTC, angyangie commented
@darkdarkdragon true. I'll add a "Remove Admin Rights" button!

2020-05-06 18:21 UTC, darkdarkdragon requested changes

2020-05-06 18:21 UTC, darkdarkdragon commented on packages/api/src/schema/schema.yaml
> +                type: array
Never worked with these schemas specs, but isn't here specified that return type is array, but actually you're returning object?
```js
res.json({ email: user.email, admin: user.admin })
```

2020-05-06 18:21 UTC, darkdarkdragon commented on packages/livepeer.com/www/components/TokenTable/index.tsx
> +        <p>
this gives error in console:
```
Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
```
Outer <p> should be changed to <div>

2020-05-06 18:24 UTC, darkdarkdragon requested changes

2020-05-06 18:24 UTC, darkdarkdragon commented on packages/livepeer.com/www/components/UserTable/index.tsx
> +        disabled={!selectedUser}
```suggestion
        disabled={!selectedUser || selectedUser.admin}
```

2020-05-06 18:24 UTC, darkdarkdragon commented on packages/livepeer.com/www/components/UserTable/index.tsx
> +        disabled={!selectedUser}
```suggestion
        disabled={!selectedUser || !selectedUser.admin}
```

2020-05-06 18:40 UTC, angyangie commented on packages/api/src/schema/schema.yaml
> +                type: array
Ah yes, I missed that one!

2020-05-06 18:40 UTC, angyangie commented on packages/livepeer.com/www/components/TokenTable/index.tsx
> +        <p>
I added a couple of `Boxes` instead

2020-05-06 18:55 UTC, darkdarkdragon approved these changes
LGTM!

2020-05-06 19:40 UTC, merged

2020-05-07 15:31 UTC, wohlner commented
LGTM

Eventually, we will want to be able to sort by admin status, but that can be another ticket / PR. I'll document it in zenhub.