ar/adding segment tracking to API
livepeer/livepeer-monorepo pull request #713
Opened 2020-05-12 23:27 UTC by angyangie

**What does this pull request do? Explain your changes. (required)**
https://github.com/livepeer/livepeerjs/issues/702
https://github.com/livepeer/livepeerjs/issues/706

**How did you test each of these updates (required)**
See here: https://app.segment.com/livepeer/sources/livepeer-com/debugger and here: https://app.segment.com/livepeer/sources/livepeer-com/schema/events for examples of new events being logged on Segment

Note: before pushing, need to add Segment API key to our `.env` on stage and prod.

**Does this pull request close any open issues?**
https://github.com/livepeer/livepeerjs/issues/702
https://github.com/livepeer/livepeerjs/issues/706

**Screenshots (optional):**

Example:

<img width="1421" alt="Screen Shot 2020-05-12 at 6 25 33 PM" src="https://user-images.githubusercontent.com/16169518/81755379-9ab05f80-9486-11ea-8099-fa54ffe91087.png">

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-05-14 20:23 UTC, angyangie commented
Confirmed with Mark that it is safe to remove HubSpot code and lose the HubSpot page view records going forward. They will live in Segment.

2020-05-14 21:43 UTC, darkdarkdragon requested changes

2020-05-14 21:43 UTC, darkdarkdragon commented on packages/api/src/controllers/helpers.js
> +    for (const key in Object.keys(event.properties)) {
Here should be `for (const key of Object.keys(event.properties)) {`
`in` iterates over object properties, but Object.keys returns array.

2020-05-14 21:43 UTC, darkdarkdragon commented on packages/api/src/controllers/helpers.js
> +      email: email,
you could just write `traits: { email },`

2020-05-18 15:42 UTC, darkdarkdragon approved these changes
LGTM

2020-05-18 16:12 UTC, merged