fix poll end time display
livepeer/livepeer-monorepo pull request #727
Opened 2020-05-21 15:41 UTC by adamsoffer

**What does this pull request do? Explain your changes. (required)**
The poll end date is incorrectly displaying the timestamp associated with the latest block rather than the end block. This PR fixes that.

<img width="427" alt="Screen Shot 2020-05-21 at 11 40 17 AM" src="https://user-images.githubusercontent.com/555740/82576692-fa2dff80-9b57-11ea-9fa8-bab3ce61d1b9.png">

2020-05-21 15:42 UTC, adamsoffer commented on packages/explorer-2.0/lib/createSchema.tsx
> +            return Utils.toBN(totalStake).sub(totalVoteStake).toString()
FYI this change was just caused by an update to the `prettier` dependency and can be ignored.

2020-05-21 21:16 UTC, yondonfu requested changes

2020-05-21 21:16 UTC, yondonfu commented on packages/explorer-2.0/lib/createSchema.tsx
> +            const currentBlockData = await _context.livepeer.rpc.getBlock(
Looks like we resolve `endTime` [here](https://github.com/livepeer/livepeerjs/blob/69031600dd5da6e30f9bb4f966bfca966be69b69/packages/explorer-2.0/pages/voting/index.tsx#L163) and [here](https://github.com/livepeer/livepeerjs/blob/bfaec96ce0fdfc1a40215dd85b0e68bdb569f57f/packages/explorer-2.0/pages/voting/%5Bpoll%5D.tsx#L152). In both cases, we check if the poll is active and only resolve `endTime`  if the poll is inactive. So, could we just always return the timestamp of the poll end block here?

i.e.

```javascript
async resolve(...) {
    const endBlockData = await _context.livepeer.rpc.getBlock(
        _poll.endBlock,
    )
    return endBlockData.timestamp
}
```

2020-05-22 01:15 UTC, adamsoffer commented on packages/explorer-2.0/lib/createSchema.tsx
> +            const currentBlockData = await _context.livepeer.rpc.getBlock(
It's possible to query `endTime` before a poll is over in which case `getBlock()` would throw an error because you can't pass it a future block that doesn't exist yet. So I first check to see if the the latest block is greater than the end block and if so return null.

2020-05-26 20:26 UTC, yondonfu commented on packages/explorer-2.0/lib/createSchema.tsx
> +            const currentBlockData = await _context.livepeer.rpc.getBlock(
Gotcha so even though we only query `endTime` in the scenarios I described in my original comment, technically `endTime` could be queried in other scenarios so we'd prefer to make sure it doesn't throw an error in those scenarios.

2020-05-26 20:26 UTC, yondonfu approved these changes
LGTM!

2020-05-28 13:18 UTC, merged