ar/add-stream-create-functionality
livepeer/livepeer-monorepo pull request #747
Opened 2020-06-10 22:45 UTC by angyangie

**What does this pull request do? Explain your changes. (required)**

Check out the figma: https://www.figma.com/file/a0Lf5NLNrDo4A585EHOj92/API-front-end-v1?node-id=0%3A1

**Does this pull request close any open issues?**
https://github.com/livepeer/livepeerjs/issues/691

**Screenshots (optional):**

<img width="1259" alt="Screen Shot 2020-06-05 at 5 08 18 PM" src="https://user-images.githubusercontent.com/16169518/83926459-de317d00-a757-11ea-88af-e5aa6ae71e27.png">

<img width="1260" alt="Screen Shot 2020-06-05 at 5 08 34 PM" src="https://user-images.githubusercontent.com/16169518/83926469-e1c50400-a757-11ea-9b3c-8fbd69c10218.png">

<img width="1305" alt="Screen Shot 2020-06-05 at 5 10 08 PM" src="https://user-images.githubusercontent.com/16169518/83926476-e689b800-a757-11ea-9bfa-4b2afa4b2698.png">

<img width="1543" alt="Screen Shot 2020-06-05 at 5 09 33 PM" src="https://user-images.githubusercontent.com/16169518/83926472-e38ec780-a757-11ea-8fae-83de3c4776d0.png">

<img width="1315" alt="Screen Shot 2020-06-05 at 5 10 21 PM" src="https://user-images.githubusercontent.com/16169518/83926517-028d5980-a758-11ea-8fa0-8951d51427be.png">

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-06-11 22:51 UTC, darkdarkdragon requested changes

2020-06-11 22:51 UTC, darkdarkdragon commented on packages/api/src/schema/schema.yaml
> -                minimum: 1
maybe we should set `minimum` to zero? so negative number could not be passed?

2020-06-11 23:28 UTC, angyangie commented on packages/api/src/schema/schema.yaml
> -                minimum: 1
Sure, let's do that! Just changed it

2020-06-12 08:55 UTC, darkdarkdragon approved these changes
LGTM

2020-06-12 16:38 UTC, merged