add orchestrator prices to table and campaign view
livepeer/livepeer-monorepo pull request #749
Opened 2020-06-12 14:21 UTC by adamsoffer

**What does this pull request do? Explain your changes. (required)**
This PR adds orchestrator pricing to the orchestrator table and campaign views, using the [buidl api](https://github.com/buidl-labs/livepeer-pricing-tool/tree/master/api)

2020-06-23 19:25 UTC, kyriediculous requested changes

2020-06-23 19:25 UTC, kyriediculous commented on packages/explorer-2.0/lib/createSchema.tsx
> +              `https://livepeer-pricing-tool.com/priceHistory/${_transcoder.id}`,
Another reason why not using this endpoint is quite pressing: it has no pagination but does index price every hour so the request size (and thus it's relation to latency) grows linearly with time. 

https://github.com/buidl-labs/livepeer-pricing-tool/blob/c7ba5408b1bd8eed70652a85be549772312f3cff/api/dataservice/dataservice.go#L131

Let's just leave pricing outside of the subgraph for now and just request it in parallel with subgraph data and manage the state in the component itself (idk if we use a state management library ? ).

2020-06-23 19:25 UTC, kyriediculous commented on packages/explorer-2.0/lib/utils.tsx
> +export const expandedPriceLabels = {
What do you think of adding a USD toggle as well ?

2020-06-23 19:31 UTC, adamsoffer commented on packages/explorer-2.0/lib/createSchema.tsx
> +              `https://livepeer-pricing-tool.com/priceHistory/${_transcoder.id}`,
Yeah agreed, I'll add a separate query for fetching prices then merge results client side.

2020-06-23 19:33 UTC, adamsoffer commented on packages/explorer-2.0/lib/utils.tsx
> +export const expandedPriceLabels = {
Yeah definitely, I was thinking we could add a global setting/toggle for displaying anything denominated in ETH in USD across the app (earned fees, price, etc). But, I think this could be a separate PR.

2020-06-25 14:23 UTC, adamsoffer commented on packages/explorer-2.0/lib/createSchema.tsx
> +              `https://livepeer-pricing-tool.com/priceHistory/${_transcoder.id}`,
Refactored. I ended up using a package called [`graphql-middleware`](https://github.com/prisma-labs/graphql-middleware) for transforming the `transcoder` and `transcoders` query responses to include price data.

2020-06-25 15:33 UTC, kyriediculous commented on packages/explorer-2.0/lib/utils.tsx
> +export const expandedPriceLabels = {
Sounds good !

2020-06-25 15:57 UTC, kyriediculous requested changes

2020-06-25 15:57 UTC, kyriediculous commented on packages/explorer-2.0/lib/createSchema.tsx
> +          `https://livepeer-pricing-tool.com/priceHistory/${args.id}`,
I opened https://github.com/buidl-labs/livepeer-pricing-tool/issues/17 to allow date ranges. That should help. 

There's also [a bug ](https://github.com/buidl-labs/livepeer-pricing-tool/issues/18)whereby the orchestrator ethereum address needs to be lowercase. 

So for now let's use the `orchestratorStats` endpoint here as well until those two issues have been addressed.

`livepeer-pricing-tool.com/orchestratorStats` - 10.9 KB - 124ms 
`ivepeer-pricing-tool.com/priceHistory/0xf4e8ef0763bcb2b1af693f5970a00050a6ac7e1b`- 18.4 KB - 449 ms

Especially since under current circumstances the entire orchestrator list info is already nearly half the response size as the price history for one orchestrator. The latency is even more significant and we only care about the latest value for now. 

Once their API is more usable we can integrate it properly.

2020-06-25 15:57 UTC, kyriediculous commented on packages/explorer-2.0/lib/utils.tsx
> +export const getEstimatedBlockCountdown = async (number) => {
new linter rules?

2020-06-25 15:59 UTC, adamsoffer commented on packages/explorer-2.0/lib/createSchema.tsx
> +          `https://livepeer-pricing-tool.com/priceHistory/${args.id}`,
Sounds good. Will do.

2020-06-25 16:00 UTC, adamsoffer commented on packages/explorer-2.0/lib/utils.tsx
> +export const getEstimatedBlockCountdown = async (number) => {
Yeah, we updated prettier to v2.0.5 a few months ago and I noticed they updated their default rule for single parentheses and single argument functions. https://prettier.io/docs/en/options.html#arrow-function-parentheses.

Should really create another PR that reruns prettier on the entire repo to account for these.

2020-06-25 16:05 UTC, kyriediculous commented on packages/explorer-2.0/lib/utils.tsx
> +export const getEstimatedBlockCountdown = async (number) => {
Should we be using [standard.js](https://standardjs.com/) instead of prettier defaults?

2020-06-25 16:07 UTC, adamsoffer commented on packages/explorer-2.0/lib/utils.tsx
> +export const getEstimatedBlockCountdown = async (number) => {
Strong preference for Prettier. The defaults are nearly identical but Prettier has better tooling and adoption.

2020-06-26 19:04 UTC, kyriediculous commented
Changes look good 👍  perhaps let's rebase and force push already and that will also re-run CI so we can get a staging link and clean commit history in one go.

2020-06-26 20:56 UTC, adamsoffer commented
@kyriediculous rebased and all checks pass 👍 . I'll plan on squash + merging on Monday along with release notes for the "what's new" section.

2020-06-26 21:10 UTC, kyriediculous approved these changes
LGTM 👍

2020-06-29 19:11 UTC, merged