Geolocate /ingest endpoint
livepeer/livepeer-monorepo pull request #758
Opened 2020-06-15 20:30 UTC by darkdarkdragon

**What does this pull request do? Explain your changes. (required)**
For `/ingest` endpoint find closes server. Uses same code as `/broadcast` endpoint.

**Specific updates (required)**

- 
- 
- 

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-06-15 20:40 UTC, iameli requested changes
So our transcoding servers are going to be located at `https://chi.livepeer.com` and `https://rkv.livepeer.com`. But our ingest servers are going to be located at `rtmp://mdw.livepeer.com` and `rtmp://fra.livepeer.com`. So we're going to need a new command-line option for these, perhaps `--ingest-region`?

2020-06-15 20:56 UTC, darkdarkdragon commented
@iameli so there will own API service in the `mdw.livepeer.com` and own in the `fra.livepeer.com`?

2020-06-16 01:50 UTC, iameli requested changes
Solid, just polish

2020-06-16 01:50 UTC, iameli commented on packages/api/src/controllers/broadcaster.js
> +      const serverRes = await fetch(`http://${server}/api/${endpoint}`, {
I assume you did this for testing, but they're https-only in production

2020-06-16 01:50 UTC, iameli commented on packages/api/src/middleware/geolocate.js
> +    } else if ((req.query.first == 'true')) {
Whoa, good catch, we need some linting on here...

2020-06-16 01:50 UTC, iameli commented on packages/api/src/controllers/broadcaster.js
> +      const serverRes = await fetch(`http://${server}/api/${endpoint}`, {
Arguably we should specify these as `INGEST_REGION__0=https://mdw.livepeer.com` so we can allow both HTTP and HTTPS and ports and stuff. But it should at least default to `https` for backwards-compatibility.

2020-06-16 01:50 UTC, iameli commented on packages/api/src/parse-cli.js
> +          coerce: (supportAddr) => {
It looks like your IDE has a different version of Prettier than we're using or something, there's a few of these format changes in this PR. Could you run this and see if it makes everything consistent?

```
git diff --name-only master | xargs npx prettier --write
```

2020-06-16 19:15 UTC, darkdarkdragon commented on packages/api/src/controllers/broadcaster.js
> +      const serverRes = await fetch(`http://${server}/api/${endpoint}`, {
I've added ability to specify `--region` and `region-ingest` with or without protocol, defaulting to `https`

2020-06-16 19:19 UTC, darkdarkdragon commented on packages/api/src/middleware/geolocate.js
> +    } else if ((req.query.first == 'true')) {
Yes, preferable it should be typescript compiler 😄

2020-06-16 19:22 UTC, darkdarkdragon commented on packages/api/src/parse-cli.js
> +          coerce: (supportAddr) => {
> Could you run this and see if it makes everything consistent?

and this added more parentheses around arrowed functions 😄 
I've looked into prettier docs - adding parentheses is default option, and we not overriding it anywhere - so why you have different results?

2020-06-16 19:52 UTC, iameli commented on packages/api/src/parse-cli.js
> +          coerce: (supportAddr) => {
Hah, great question, super weird. No problem then.

2020-06-16 19:53 UTC, iameli approved these changes
LGTM!

2020-06-16 20:05 UTC, merged