Add support for calling staking functions with hints
livepeer/livepeer-monorepo pull request #776
Opened 2020-06-24 13:52 UTC by adamsoffer

**What does this pull request do? Explain your changes. (required)**
This PR adds support for calling all staking functions with hints in an effort to reduce the gas costs associated with these functions.

**Specific updates (required)**
- Adds `bondWithHint`, `unbondWithHint`, `rebondWithHint`, and `rebondFromUnbondedWithHint` methods to the sdk
- Updates the apollo mutations in the explorer to use these new methods

**Does this pull request close any open issues?**
Closes #742

2020-06-25 19:47 UTC, kyriediculous requested changes
Nice ! This PR will hopefully bring down the cost of staking operations a little bit when there aren't too many rounds to auto-claim for. 

Quick question, do we recalculate the `transcoders` list we pass into `getHint(id, transcoders)` to reflect what the list would look like after the staking operation completes?

2020-06-25 19:47 UTC, kyriediculous commented on packages/explorer-2.0/apollo/resolvers/Mutation.tsx
> +  const gas = await _ctx.livepeer.rpc.estimateGas(
Unrelated to this PR , more of a question. But on the quest for reducing RPC calls , should we remove gas estimation since all web3 providers will dry run transactions before sending them? 

They already do the gas estimation before sending the actual transaction. In the case of metamask you would get the popup screen where you could adjust things. In case of a geth node it would dry run the tx , calculate the gas and then send it.

2020-06-25 19:47 UTC, kyriediculous commented on packages/explorer-2.0/lib/utils.tsx
> +    // if transcoder is the first in the active set, only set posNex
This should be the other way around if I'm not mistaken. 

> * Given a new node with a `key`, a hint is of the form `(prevId, nextId)` s.t. `prevId` and `nextId` are adjacent in the list.
 > * `prevId` is a node with a key >= `key` and `nextId` is a node with a key <= `key`

Where key is the amount of stake

Since the list is in descending order and we start at the head `next` would mean downward and `previous` would mean back up. 



So if a node is the head, then the previous would be null 

Here's the actual implementation : https://github.com/livepeer/protocol/blob/streamflow/contracts/libraries/SortedDoublyLL.sol#L74

2020-06-29 15:50 UTC, adamsoffer commented on packages/explorer-2.0/apollo/resolvers/Mutation.tsx
> +  const gas = await _ctx.livepeer.rpc.estimateGas(
> Quick question, do we recalculate the `transcoders` list we pass into `getHint(id, transcoders)` to reflect what the list would look like after the staking operation completes?

ah good catch. We need to add a `pollInterval` to the transcoders query to make sure the transcoders list is up to date after a staking operation.

2020-06-29 16:06 UTC, adamsoffer commented
> Quick question, do we recalculate the `transcoders` list we pass into `getHint(id, transcoders)` to reflect what the list would look like after the staking operation completes?

ah good catch. We need to add a pollInterval to the transcoders query to make sure the transcoders list is up to date after a staking operation.

2020-06-29 16:09 UTC, adamsoffer commented on packages/explorer-2.0/apollo/resolvers/Mutation.tsx
> +  const gas = await _ctx.livepeer.rpc.estimateGas(
Yeah agreed we can probably remove gas estimation and rely on web3 providers for this. I don't see any downsides to that. It won't have a huge impact on the amount of RPC calls the app makes, but good to remove erroneous code.

2020-06-29 16:13 UTC, kyriediculous commented
> We need to add a pollInterval to the transcoders query to make sure the transcoders list is up to date after a staking operation.

Sorry I more like  meant that the transcoders list needs to be updated already (for what the state on-chain , ie stake, _would_ be if the transaction succeeds). 

So we would have to 

1. Get the transcoder stake
2. add/substract stake depending on the action
3. With updated stake calculate the _would be_  position in the list
4. Use those values as hints

So under the current implementation I guess we could make a copy of the transcoders list, adjust it for the update and then pass it into `getHint()`

2020-06-29 16:19 UTC, adamsoffer commented
> the transcoders list needs to be updated already (for what the state on-chain , ie stake, _would_ be if the transaction succeeds).

ah I misunderstood. I didn't realize we need to pass hints based on the order *after* a staking operation. Thanks for the clarification.

> i.e `getHint(action, amount, id, transcoders): {nextPos, prevPos}`

I'll use this function signature 👍

2020-06-29 16:20 UTC, kyriediculous commented
> I'll use this function signature 👍

I updated it slightly so it doesn't have to return an object and the caller can calculate previous and next positions based on the new position returned.

2020-06-29 16:24 UTC, kyriediculous commented
Just to make a small note, it is possible due to race conditions that a hint might be invalid by the time a transaction is mined. 
This would cause the function to fallback to old loop behaviour. 

I don't think there's much we should do about this though, I do wonder if RPC providers will be able to differentiate between these cases when estimating the gas cost as they dry  run the tx.

2020-06-29 16:48 UTC, adamsoffer commented
> Just to make a small note, it is possible due to race conditions that a hint might be invalid by the time a transaction is mined.
> This would cause the function to fallback to old loop behaviour.
> 
> I don't think there's much we should do about this though, I do wonder if RPC providers will be able to differentiate between these cases when estimating the gas cost as they dry run the tx.

Yeah not much we can do about this, but shouldn't be a very common occurrence and worst case is that a delegator ends up paying slightly more gas.

2020-07-06 21:37 UTC, adamsoffer commented
@kyriediculous I ended up going about this a little differently. I created a method called `simulateNewActiveSetOrder` that reorders the `transcoders` array based on the delegator's action and amount, then pass that updated array into the `getHint` method.

2020-07-06 21:38 UTC, kyriediculous commented
I briefly looked over it, looks okay to me at first sight but I'll take a closer look in a bit !

2020-07-07 00:02 UTC, kyriediculous requested changes

2020-07-07 00:02 UTC, kyriediculous commented on packages/explorer-2.0/lib/utils.tsx
> +    +Utils.fromWei(a.totalStake) < +Utils.fromWei(b.totalStake) ? 1 : -1,
Let's use the `cmp()` (compare) BN prototype instead of converting these 

```
a.cmp(b) - compare numbers and return -1 (a < b), 0 (a == b), or 1 (a > b) depending on the comparison result (ucmp, cmpn)
```

Since this already returns -1, 1 or 0 we can just do `return a.totalStake.cmp(b.totalStake)` 


Assuming this is `BN.js` and not `bignumber.js` but that should have a similar method. 

Edit: see my other comment about using BN's instead of strings here

2020-07-07 00:02 UTC, kyriediculous commented on packages/explorer-2.0/lib/utils.tsx
> +      .toString()
I would generally not advise converting bignumbers to strings outside of templating for displaying on the UI. 

If this is a string in the schema it should be a bignumber in my opinion. I guess changing this would ripple all the way back up. But when you look at my other comment as well it actually makes things cleaner.  We should avoid type juggling when not necessary. 

tl;dr BN in the logic, string on the UI

2020-07-07 00:55 UTC, adamsoffer commented on packages/explorer-2.0/lib/utils.tsx
> +      .toString()
Yeah that makes sense. In this case, however, the reason I convert it back to a string is because the original value in the array (fetched from the graph endpoint) is a string. I just converted it to a big number to do the math. Does that make sense?

2020-07-07 00:57 UTC, kyriediculous commented on packages/explorer-2.0/lib/utils.tsx
> +      .toString()
Is that a thegraph thing? Because I'm quite sure web3 js libraries would return a bignumber for `uint256`

2020-07-07 01:00 UTC, adamsoffer commented on packages/explorer-2.0/lib/utils.tsx
> +      .toString()
Yeah, the graph returns a BigInt numbers as strings in response to a query.

2020-07-07 01:02 UTC, adamsoffer commented on packages/explorer-2.0/lib/utils.tsx
> +      .toString()
Naturally, as JSON doesn't not support BigInt.

2020-07-07 01:02 UTC, kyriediculous commented on packages/explorer-2.0/lib/utils.tsx
> +      .toString()
Why can't we have nice things 😞 

I'm assuming this is a limitation of the graphQL type system itself, not so much thegraph specific ? 

I'm okay with converting to BN to do the math

2020-07-07 01:12 UTC, adamsoffer commented on packages/explorer-2.0/lib/utils.tsx
> +      .toString()
😞 It's a limitation of the JSON spec. JSON schema types are limited to strings, numeric types, object, array, boolean and null.

2020-07-07 13:25 UTC, adamsoffer commented on packages/explorer-2.0/lib/utils.tsx
> +    +Utils.fromWei(a.totalStake) < +Utils.fromWei(b.totalStake) ? 1 : -1,
Using `a.cmp(b)` instead now 👍

2020-07-07 13:57 UTC, kyriediculous commented
Changes look good, let's rebase and resolve the conflicts 👍

2020-07-07 14:46 UTC, merged