WIP webhooks
livepeer/livepeer-monorepo pull request #799
Opened 2020-07-15 17:29 UTC by ya7ya

**What does this pull request do? Explain your changes. (required)**
API webhooks implementation based on spec defined in #791 

**Specific updates (required)**

- 
- 
- 

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**
Fixes #791 

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-07-16 18:44 UTC, iameli commented on packages/api/src/schema/schema.yaml
> +          pattern: ^webhook/
We moved away from this architecture a little — now ids are just UUIDs. We should also have a `kind` field on here that's required to be `webhook`.

2020-07-16 18:47 UTC, iameli commented on packages/api/src/schema/schema.yaml
> +  /webhook:
Looks good. We should also document the `trigger` endpoint.

2020-07-21 16:40 UTC, iameli requested changes

2020-07-21 16:40 UTC, iameli commented on packages/api/src/controllers/webhook.js
> +  } // CF doesn't know what this means
I think that it does know now

2020-07-21 16:40 UTC, iameli commented on packages/api/src/controllers/webhook.js
> +  const webhook = await req.store.get(`webhook/${req.body.id}`)
Shouldn't need this section, `validatePost('webhook')` will reject anything that contains an ID

2020-07-21 16:40 UTC, iameli commented on packages/api/src/controllers/webhook.js
> +    eventType: 'streamStarted', // TODO, remove hardcoding once we have mutliple webhook events
We know from validatePost this'll be streamStarted, this can jsut be `req.body.eventType`

2020-07-21 16:40 UTC, iameli commented on packages/api/src/controllers/webhook.js
> +    url: req.body.url, // TODO validate this.
1. Let's at least do a `new URL(req.body.url)` and reject if the URL doesn't parse
2. Let's check that the url.protocol is `http` or `https`

At trigger time:

1. Get the IP from the domain. If it's already an IP, cool. https://nodejs.org/api/dns.html#dns_dns_resolve4_hostname_options_callback
2. Check that the resolved IP isn't local: https://www.npmjs.com/package/is-local-ip

2020-07-21 16:40 UTC, iameli commented on packages/api/src/controllers/webhook.js
> +  if (!resp || resp.statsCode !== 200) {
`status`?

2020-07-21 16:40 UTC, iameli commented on packages/api/src/controllers/webhook.js
> +    'content-type': 'application/json',
`user-agent`: `livepeer.com` maybe

2020-07-21 16:40 UTC, iameli commented on packages/api/src/controllers/webhook.js
> +    return res.end()
Let's do a `res.json()`

2020-07-21 16:40 UTC, iameli commented on packages/api/src/controllers/webhook.js
> +  let resp = await fetch(webhook.url, params)
Let's get a timeout here... 10 seconds?

2020-07-21 16:40 UTC, iameli commented on packages/api/src/controllers/webhook.js
> +  const webhook = await req.store.get(`webhook/${id}`)
I think we'll have to get all the webhooks for a stream, so `req.store.query({streamId: req.body.streamId})`

2020-07-25 04:08 UTC, iameli requested changes
So I think we're going to want the ability to block on a failed webhook — this would allow UGC platform operators to return an error code from a webhook and disallow the stream from happening. Nice feature, and it'll be even more important when we get to "wildcard streams" in a second.

That implies this webhook will need to happen before we save the stream "active" state.

Other than that, just a few notes :+1:

2020-07-25 04:08 UTC, iameli commented on packages/api/src/controllers/stream.js
> +    const filter1 = all ? (o) => o : (o) => !o[Object.keys(o)[0]].deleted
Hmm, no fun. We should figure out a way to handle this soon in the model layer.

2020-07-25 04:08 UTC, iameli commented on packages/api/src/controllers/stream.js
> +    output.forEach(async (webhook) => {
So this is where we can block on a failed webhook — instead of the `output.forEach` we can do an `await Promise.all(output.map(async (webhook) => {`.

2020-07-25 04:08 UTC, iameli commented on packages/api/src/controllers/stream.js
> +        // don't fire this webhook.
Good, but let's log something here so we can track down when it happened.

2020-07-25 04:08 UTC, iameli commented on packages/api/src/util.js
> +export const fetchWithTimeout = (url, options) => new Promise((resolve, reject) => {
Love having this function in util.js!

2020-07-25 04:08 UTC, iameli commented on packages/api/src/util.js
> +      if (response.status === 200) {
I think `fetchWithTimeout` will be more useful if it does the same thing as `fetch` and returns the response even if it's an error code. That way the two functions are totally interchangeable. We can check for success codes back up  in the webhook code

2020-07-25 04:08 UTC, iameli commented on packages/api/src/controllers/stream.js
> +  if (req.body.active) {
This section all being here is cool for now but eventually we're going to want a `triggerWebhook` function so we can do it from lots of different contexts.

2020-07-25 04:11 UTC, iameli commented on packages/api/src/controllers/stream.js
> +          body: JSON.stringify(sanitized),
We're going to want a little more in the webhook body: how about this?
```
{
  event: "streamStarted",
  stream: sanitized
}
```

2020-07-25 04:21 UTC, iameli commented on packages/api/src/controllers/stream.js
> +    const resp = await req.store.list({
I think this will not work when there are more than 10 streams in the app globally? How about
```
const resp = await req.store.query({
  kind: "webhook",
  query: {
    userId: stream.userId,
    eventType: "streamStarted"
  }

2020-07-27 07:53 UTC, ya7ya commented on packages/api/src/controllers/stream.js
> +  if (req.body.active) {
Agreed, I was gonna refactor it once I'm able to test it

2020-07-27 07:56 UTC, ya7ya commented on packages/api/src/controllers/stream.js
> +    const resp = await req.store.list({
Oh, I didn't know about this limitation, I'll change it to use `query`

2020-07-31 04:35 UTC, iameli requested changes
I wrote a test webhook! Check it out at https://winter-darkness-88ea.livepeer.workers.dev. It rejects all streams unless the `name` field of the stream contains the string "eli_is_cool". Live at https://winter-darkness-88ea.livepeer.workers.dev

There are a few changes to make here but I kind of suspect that we can't `req.store.query` by multiple fields right now :( That'll change next week. We can either wait until then or go back to the `req.store.list` technique you had a second ago in the interim.

2020-07-31 04:35 UTC, iameli commented on packages/api/src/controllers/stream.js
> +    delete sanitized.streamKey
This will still modify `stream` which you're presumably trying to avoid. If you do `const sanitized = {...stream}`, I think that'll have the effect you want

2020-07-31 04:35 UTC, iameli commented on packages/api/src/controllers/stream.js
> +            if (resp.status === 200) {
I think 201 and 204 are probably fine... maybe `if (resp.status >= 200 && resp.status < 300)`?

2020-07-31 04:35 UTC, iameli commented on packages/api/src/controllers/stream.js
> +            body: {
`body` needs to be a string, you'll need to move the `JSON.stringify` up around the entire thing

2020-07-31 04:35 UTC, iameli commented on packages/api/src/controllers/stream.js
> +              console.log(`webhook ${webhook.id} didn't get 200 back! response status: ${resp.status}`)
We'll want to throw an error here to block stream start

2020-07-31 04:35 UTC, iameli commented on packages/api/src/controllers/stream.js
> +            console.log('webhook Trigger error ', e) // TODO better logs.
should `throw e` here too

2020-07-31 04:35 UTC, iameli commented on packages/api/src/controllers/webhook.js
> +// trigger logic is in stream.js , /setactive endpoint
We can clean this up now, stuff like this will move to `triggerWebhook` whenever that exists

2020-07-31 04:35 UTC, iameli commented on packages/api/src/controllers/stream.js
> +      query: {
Does this work okay? I'm not positive the existing system works with more than one field, sorry about that 😅

2020-07-31 04:35 UTC, iameli commented on packages/api/src/schema/schema.yaml
> +        eventType:
It's `event` in the webhook itself and `eventType` here... I kind of like standardizing on `event`?

2020-07-31 07:32 UTC, ya7ya commented on packages/api/src/controllers/stream.js
> +    delete sanitized.streamKey
i don't know how, but I didn't know that :facepalm: :open_mouth:

2020-07-31 09:56 UTC, iameli approved these changes
LGTM if we can get CI passing and it works with that test webhook I wrote 👍

2020-08-04 10:27 UTC, darkdarkdragon commented
@ya7ya @iameli 
> So I think we're going to want the ability to block on a failed webhook 

Can we make it optional?
Add field `blocking` to the webhook object, and make it false by default?
For people who do not need  to reject streams it would make requirements for their webhook implementation less demanding.

2020-08-04 14:29 UTC, darkdarkdragon requested changes

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/controllers/webhook.js
> +    (webhook.userId !== req.user.id && !req.isUIAdmin)
```suggestion
  if ( !webhook || (webhook.deleted ||
    webhook.userId !== req.user.id) && !req.isUIAdmin)
```

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/controllers/webhook.js
> +      !(req.user.admin && !stream.deleted))
```suggestion
    ((webhook.userId !== req.user.id || webhook.deleted) &&
      !req.user.admin)
```

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/controllers/webhook.js
> +    (webhook.userId !== req.user.id && !req.isUIAdmin)
```suggestion
  if ( !webhook || (webhook.deleted ||
    webhook.userId !== req.user.id) && !req.isUIAdmin)
```

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/controllers/webhook.js
> +  res.json({})
```suggestion
  res.status(204)
  res.end()
```

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/schema/schema.yaml
> +        - id
shouldn't be required because `validatePost('webhook')` will reject without this field

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/schema/schema.yaml
> +        - timestamp
shouldn't be required

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/schema/schema.yaml
> +          readOnly: true
```suggestion
          readOnly: true
          index: true
```

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/schema/schema.yaml
> +        timestamp:
why not `createdAt`, like in other objects?

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/controllers/webhook.js
> +    deleted: false
Don't add `deleted` field here - it is being exposed to the user, we don't want it. Or you should sanitise it from every place where object is returned to the user.

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +            timeout: 10 * 1000, // 10 second timeout
I think 10 seconds is too much for blocking webhook at the stream start

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +              event: 'streamStarted',
```suggestion
              event: webhook.event,
```

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/util.js
> +  return fetch(url)
```suggestion
  return fetch(url, options)
```

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/util.js
> +      return resolve(response)
I think it would be good not to resolve promise if already was rejected

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +            body: JSON.stringify({
shouldn't we include webhook's id in the body?

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +          // don't fire this webhook.
why? is it for debugging only?

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +resolver.setServers(['8.8.8.8', '8.8.4.4']);
this is for debugging, right?

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +import { util } from 'prettier'
what is this?

2020-08-04 14:29 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +    const resp = await req.store.list({
I think it would be better:
1. Refactor getting list of webhooks to separate function and make it something like this:
```js
function getWebhooks(store, userId, event) {
  let filter = (o) => !o.deleted && o.event === event
  const { data } = await store.queryObjects({
    kind: 'webhook',
    query: { userId },
    limit: 100,
    filter
  })
  return data
}
```

2020-08-04 14:57 UTC, ya7ya commented on packages/api/src/controllers/stream.js
> +          // don't fire this webhook.
this is to make sure the webhook's url doesn't resolve to a local IP

2020-08-04 14:59 UTC, ya7ya commented on packages/api/src/controllers/stream.js
> +resolver.setServers(['8.8.8.8', '8.8.4.4']);
you mean the resolver ? it's to make sure the url is legit and accessible.

this isn't currently working, I'm actively debugging why.

2020-08-04 15:00 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +          // don't fire this webhook.
Ok, I've got it. But maybe we can allow to use local IPs for admins? It's much more convenient to test locally 😄

2020-08-04 15:05 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +resolver.setServers(['8.8.8.8', '8.8.4.4']);
> you mean the resolver ?

Yes, resolver. It's not good to change used dns servers, so - is resolver used only for debugging?

> this isn't currently working, 

what's not working?

2020-08-04 15:36 UTC, ya7ya commented on packages/api/src/controllers/stream.js
> +resolver.setServers(['8.8.8.8', '8.8.4.4']);
all dns queries are returning ENOTFOUND error, or timing out.

2020-08-04 17:03 UTC, iameli commented on packages/api/src/controllers/stream.js
> +          // don't fire this webhook.
Yeah, I was figuring there was an attack something like this:

1. Make a webhook for http://10.0.0.1:80
2. Stream in. Depending on the content/timing of the error, you know if there's a server there
3. Make a webhook for http://10.0.0.2:80 and repeat

You can do all of that really fast in parallel to do a scan of our entire internal network!

2020-08-05 18:15 UTC, darkdarkdragon requested changes

2020-08-05 18:15 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +app.put('/:id/setactive', authMiddleware({admin: true}), async (req, res) => {
`{admin: true}` requires user to be logged in throw JWT - which is not the case for the `mist-api-controller` calling this method. We really need to improve authMiddleware and change `admin` arg to `UIAdmin` and add new arg such as `justAdmin` 😃

2020-08-05 18:15 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +    const resp = await req.store.list({
can we use `getWebhooks` here?

2020-08-05 18:15 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +          urlObj = parseUrl(webhook.url)
`parseUrl` by itself can throw error. I think we should try to parse url in POST/PUT /api/webhook endpoint

2020-08-05 18:15 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +          ips = await resolver.resolve4(urlObj.host)
Can we move this check to POST/PUT /api/webhook endpoint?
@iameli what do you think?

2020-08-05 18:15 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +        if (req.query.allowLocalWebhooks) {
This will allow anyone to skip local check?
Can we just skip local check for admin? Without introducing new query param?

2020-08-05 18:15 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +            isLocal = isLocalIP(ips[0])
```suggestion
if (ips && ips.length) {
            isLocal = isLocalIP(ips[0])
}
```

`ips` can be empty, so without check it will throw useless indexing error

2020-08-05 18:15 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +            timeout: WEBHOOK_TIMEOUT, // 10 second timeout
it is not 10 seconds anymore, I think it would be better to just remove comment

2020-08-05 18:15 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +    await Promise.all(
Result of this call is not used anywhere, and hence `/setactive` endpoint will always return success, and stream can't be blocked by webhook

2020-08-05 18:15 UTC, darkdarkdragon commented on packages/api/src/controllers/webhook.js
> +  // create a webhook
comments not needed?

2020-08-05 18:15 UTC, darkdarkdragon commented on packages/api/src/controllers/webhook.js
> +import isLocalIP from 'is-local-ip'
not used

2020-08-05 18:15 UTC, darkdarkdragon commented on packages/api/src/controllers/webhook.js
> +})
```suggestion
async function getWebhooks(store, userId, event, limit = 100, cursor = undefined, includeDeleted = false) {
  let filter = (o) => (!o.deleted || includeDeleted) && (!event || o.event === event)
  const resp = await store.queryObjects({
    kind: 'webhook',
    query: { userId },
    limit,
    cursor,
    filter
  })
  return resp
}

const app = Router()

app.get('/', authMiddleware({}), async (req, res) => {
  let { limit, cursor, all, event } = req.query
  logger.info(`cursor params ${cursor}, limit ${limit} all ${all}`)
  
  const resp = await getWebhooks(req.store, req.user.id, event, limit, cursor, !!all && req.user.admin)
  res.status(200)

  if (output.length > 0) {
    res.links({ next: makeNextHREF(req, resp.cursor) })
  }
  res.json(resp.data)
})
```

something like this (not tested)

2020-08-05 18:15 UTC, darkdarkdragon commented on packages/api/src/controllers/webhook.js
> +    url: req.body.url,
at least do `url.parse`?
and it would be good to check that url has schema defined and it is http or https

2020-08-05 19:01 UTC, ya7ya commented on packages/api/src/controllers/stream.js
> +          ips = await resolver.resolve4(urlObj.host)
@darkdarkdragon we check every time to make sure the user didn't create a proper webhook then later changed the DNS record before triggering it.

2020-08-06 18:57 UTC, iameli requested changes
A few one-line cleanups and I left a suggestion for `fetchWithTimeout`

Feel free to move over and merge when CI on the other repo passes :+1:

2020-08-06 18:57 UTC, iameli commented on packages/api/src/controllers/stream.js
> +    console.log('output : ', output)
can clean this up

2020-08-06 18:57 UTC, iameli commented on packages/api/src/controllers/stream.js
> +                // throw new Error(`webhook ${webhook.id} didn't get 200 back! response status: ${resp.status}`)
Think this should throw, yeah?

2020-08-06 18:57 UTC, iameli commented on packages/api/src/controllers/webhook.js
> +  logger.info(`cursor params ${cursor}, limit ${limit} all ${all}`)
cleanup

2020-08-06 18:57 UTC, iameli commented on packages/api/src/util.js
> +});
Just added a little check to see if it already timed out:
```suggestion


export const fetchWithTimeout = (url, options) => new Promise((resolve, reject) => {
  let timeout = setTimeout(() => {
    timeout = null;
    reject('timeout');
  }, options.timeout || 10 * 1000);

  return fetch(url, options)
    .then(response => {
      if (timeout === null) {
        // already timed out
        return;
      }
      clearTimeout(timeout);

      return resolve(response)
      // return a response regardless of the status code.
      // if (response.status === 200) {
      //   return resolve(response);
      // }

      // return reject(response);
    }, rejectReason => {
      if (timeout === null) {
        // already timed out
        return;
      }
      clearTimeout(timeout);

      return reject(rejectReason);
    });
});
```

2021-01-02 03:54 UTC, closed without merging