explorer,sdk: LIP-52 claimSnapshot integration
livepeer/livepeer-monorepo pull request #835
Opened 2020-09-23 21:02 UTC by kyriediculous

**What does this pull request do? Explain your changes. (required)**
Integrate `claimSnapshotEarnings` into staking functions and remove the notion of claiming earnings as an active action that an end-user needs to undertake, this includes removing max claim rounds. 

See [LIP-52](https://github.com/livepeer/LIPs/blob/master/LIPs/LIP-52.md) for more context 

**Specific updates (required)**
- sdk: update ABIs 1fa3ebd
- sdk: verifySnapshot(id, proof, leafHash) d77849f
- sdk: getLipUpgradeRound(lipNumber) 3af49a0
- sdk: getCallData, estimateGasRaw, sendTransaction 7e8c582
- explorer: EarningsTree 1997bbf
- explorer: remove max claim rounds 132963d
- explorer: pass delegator and lastClaimRound to mutations 8c4511d
- explorer: add delegator and lastClaimRound to mutations e1e5b02
- explorer: update apollo resolvers to call claimSnapshotEarnings if necessary 1ffa122

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**
Fixes #831 

**Checklist:**
- [x] I have read the **CONTRIBUTING** document.
- [] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2020-09-29 23:57 UTC, adamsoffer reviewed
This looks great! Nice work. I'll just want to test and run locally once we get the rinkeby subgraph up before merging.

2020-09-29 23:57 UTC, adamsoffer commented on packages/explorer-2.0/apollo/resolvers/Mutation.tsx
> +  if (lastClaimRound <= LIP52Round) {
Should we return early and get the invalid case out of the way first? 
ie.
```js
if (lastClaimRound > LIP52Round) {
  return
}
```
You actually recommended this to me a while back and I like it as a best practice. Not necessary, but it's nice for readability.

2020-09-29 23:57 UTC, adamsoffer commented on packages/explorer-2.0/package.json
> +    "ethereumjs-util": "6.0.0",
Does this package provide us functionality that we don't already get with `web3.js` or `ethers`?

2020-09-30 00:02 UTC, kyriediculous commented on packages/explorer-2.0/apollo/resolvers/Mutation.tsx
> +  if (lastClaimRound <= LIP52Round) {
Hah , good point ! 😄

2020-09-30 00:04 UTC, kyriediculous commented on packages/explorer-2.0/package.json
> +    "ethereumjs-util": "6.0.0",
This is what the `EarningsTree` class uses which I copied partially  from the Zeppelin team. I can maybe rewrite it to use ethersjs instead but this should just be a small dependency. Higher versions of this break compatibility, that I know.

2020-09-30 00:06 UTC, kyriediculous commented on packages/explorer-2.0/components/StakeTransactions/index.tsx
> +
TODO: remove blank line

2020-09-30 00:06 UTC, adamsoffer commented on packages/explorer-2.0/package.json
> +    "ethereumjs-util": "6.0.0",
Gotcha. Cool yeah that doesn't sound necessary. I was just curious.

2020-10-02 08:22 UTC, kyriediculous commented on packages/explorer-2.0/apollo/resolvers/Mutation.tsx
> +  if (lastClaimRound <= LIP52Round) {
fixed in 3ee5f3b

2020-10-02 08:22 UTC, kyriediculous commented on packages/explorer-2.0/components/StakeTransactions/index.tsx
> +
fixed in af9c66b

2020-10-02 17:47 UTC, adamsoffer commented on packages/explorer-2.0/components/StakingWidget/Footer.tsx
> +        delegator = {delegator}
@kyriediculous `delegator` will be undefined for first time stakers. We should pass `account` here.

2020-10-02 17:51 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingWidget/Footer.tsx
> +        delegator = {delegator}
This is Unstake, I assume you mean at L126 instead? 

I believe we can't simply pass in account because `delegator` in this case is an object that contains other values other than the address, wouldn't we have to overwrite `delegator.id = account` ?

2020-10-02 17:56 UTC, adamsoffer commented on packages/explorer-2.0/components/StakingWidget/Footer.tsx
> +        delegator = {delegator}
oops yeah meant to leave this comment on L126. Yeah we'll also have to pass the `lastClaimRound` if it exists (it will be null for first time users).

2020-10-02 18:02 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingWidget/Footer.tsx
> +        delegator = {delegator}
`Null == 0` in JS but we'll have to add a statement to `encodeClaimSnapshotAndStakingAction` to return if `lastClaimRound == 0`

2020-10-02 18:36 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingWidget/Footer.tsx
> +        delegator = {delegator}
I think this would do the trick aaead8367b43413e3512c8654429bb52c0145cfc

2020-10-08 16:55 UTC, adamsoffer requested changes

2020-10-08 16:55 UTC, adamsoffer commented on packages/explorer-2.0/components/WithdrawFees/index.tsx
> +                lastClaiRound:delegator?.lastClaimRound
Should be `lastClaimRound: parseInt(delegator?.lastClaimRound.id, 10)`

2020-10-08 16:55 UTC, adamsoffer commented on packages/explorer-2.0/components/Restake/index.tsx
> +                lastClaimRound: delegator?.lastClaimRound
Should be `lastClaimRound: parseInt(delegator?.lastClaimRound.id, 10)`

2020-10-08 16:55 UTC, adamsoffer commented on packages/explorer-2.0/components/RestakeFromUnstaked/index.tsx
> +                lastClaimRound: delegator?.lastClaimRound
Should be `lastClaimRound: parseInt(delegator?.lastClaimRound.id, 10)`

2020-10-09 00:08 UTC, kyriediculous commented on packages/explorer-2.0/components/RestakeFromUnstaked/index.tsx
> +                lastClaimRound: delegator?.lastClaimRound
fixed in 5ddd00d3

2020-10-09 00:08 UTC, kyriediculous commented on packages/explorer-2.0/components/Restake/index.tsx
> +                lastClaimRound: delegator?.lastClaimRound
fixed in 5ddd00d3

2020-10-09 00:08 UTC, kyriediculous commented on packages/explorer-2.0/components/WithdrawFees/index.tsx
> +                lastClaiRound:delegator?.lastClaimRound
fixed in 5ddd00d3

2020-10-12 17:01 UTC, adamsoffer approved these changes

2020-10-12 20:54 UTC, merged