add wallet connect
livepeer/livepeer-monorepo pull request #840
Opened 2020-10-09 16:28 UTC by adamsoffer

**What does this pull request do? Explain your changes. (required)**
This PR adds WalletConnect as a wallet option so users can stake with Rainbow, Trust Wallet, Argent, etc.

**Screenshots (optional):**
![image](https://user-images.githubusercontent.com/555740/95608288-eada2080-0a2a-11eb-8778-852510234c5f.png)

2020-10-13 17:20 UTC, kyriediculous requested changes
Not an expert on wallet connect but the integration looks good to me, just a few minor comments.

2020-10-13 17:20 UTC, kyriediculous commented on packages/explorer-2.0/components/Approve/index.tsx
> +      try {
I assume this try/catch is lingering here from testing the integration?

2020-10-13 17:20 UTC, kyriediculous commented on packages/explorer-2.0/lib/connectors.tsx
> +export const walletLink = new WalletLinkConnector({
What do you think of in the future making fixups along the way a seperate PR so that feature improvements/additions diffs can be kept to the relevant changes?

2020-11-09 17:29 UTC, adamsoffer commented on packages/explorer-2.0/components/Approve/index.tsx
> +      try {
ah yes this was from testing the integration. I can remove 👍

2020-11-09 17:30 UTC, adamsoffer commented on packages/explorer-2.0/lib/connectors.tsx
> +export const walletLink = new WalletLinkConnector({
yeah this var name change is sort of unrelated to the PR. Agree in the future these types of fixups can be separated in another PR 👍

2020-11-09 17:32 UTC, adamsoffer commented
@kyriediculous thanks for the review. I'm testing this integration with Rainbow wallet and Trust wallet but noticed transactions are failing and the error message is not very helpful. I'll continue to test and see what I find.

2021-02-03 18:08 UTC, merged