convert subgraph values from `BigInt` to `BigDecimal`
livepeer/livepeer-monorepo pull request #854
Opened 2020-11-30 15:39 UTC by adamsoffer

**What does this pull request do? Explain your changes. (required)**
This PR converts values in the subgraph from `BigInt` to `BigDecimal` rather than `BigInt` so that values are easier to read without having to move the decimal 18 places. For example, previously when querying a delegator's `bondedAmount` the value returned was in WEI. It now gets returned in ETH (`81.551884481024178446` as opposed to `81551884481024178446`). This also makes the data easier to consume in client side application since it avoid the client having to convert the value from a BigInt to a float. This change was inspired by the new v2 uniswap subgraph.

**Specific updates (required)**
- Changed all instances of `BigInt` in `BigDecimal` in the subgraph
- Created a helper function to convert values to decimal format
- Updated the explorer to account for the change in values)

**How did you test each of these updates (required)**
I performed each staking action to ensure nothing broke and looked over all the affected pages and components.

_Note: this is a breaking change for users of the Livepeer subgraph and will require we reach out to developers we know are relying on it and make an announcement in the Discord #dev channel. I propose we keep this on our `livepeer-canary` subgraph for a 2-3 weeks to give developers a chance to update their applications.

2020-11-30 22:46 UTC, kyriediculous commented
I suppose this change (and the reason why the uniswap v2 subgraph also deos this) is suitable for time series data to avoid having to loop through an entire time series of i.e. ETH values and have to do `utils.fromWei()` for each of the values ?

2020-11-30 22:54 UTC, adamsoffer commented
> I suppose this change (and the reason why the uniswap v2 subgraph also deos this) is suitable for time series data to avoid having to loop through an entire time series of i.e. ETH values and have to do `utils.fromWei()` for each of the values ?

Yeah exactly...better performance when generating the charts client side. I forgot to mention that.

2020-12-01 01:32 UTC, kyriediculous requested changes
Overall looks good ! 

Just a bunch of nitpicky style / readability comments

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingView/index.tsx
> +                          (parseFloat(delegator.delegate.totalStake) /
Line 310-316 can be replaced using the unary plus operator as well. 

```suggestion
                          (+delegator.delegate.totalStake / totalActiveStake * 100).toPrecision(4)}
```

Javascript will not error on division by zero, instead the result will be NaN which might be even more accurate than returning 0.

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingView/index.tsx
> +  const unbonded = delegator.unbonded ? parseFloat(delegator.unbonded) : 0
Can use unary plus here, this is true for as good as all cases where we parseInt/parseFloat now because we no longer have to call `utils.fromWei`/ `utils.toWei`

```javascript
+undefined = NaN 
+"" = 0
```

```suggestion
  const unbonded = +delegator.unbonded
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingView/index.tsx
> +  const principal = parseFloat(delegator.principal)
```suggestion
  const principal = +delegator.principal
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingView/index.tsx
> +  const totalActiveStake = parseFloat(protocol.totalActiveStake)
```suggestion
  const totalActiveStake = +protocol.totalActiveStake
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingView/index.tsx
> +                      parseFloat(delegator.delegate.totalStake),
```suggestion
                      +delegator.delegate.totalStake,
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingView/index.tsx
> +                          parseFloat(delegator.delegate.totalStake) -
Seems like we re-use this value quite a bit in this code block.

What do you think of putting it on the heap after L49 and re-using it instead?

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingView/index.tsx
> +                            parseFloat(delegator.delegate.totalStake) -
See comment above about avoiding parsing this value multiple times

Should also be more memory efficient because I think what's happening now is 

1. Read delegator from heap
2. Read delegate from heap 
3. Read totalStake from heap 
4. Add totalStake to call stack
5. add parseFloat(totalStake) to callstack
6. Add result of (5) to callstack
...

compared to 

1. read totalStake from heap 
2. add totalStake to callstack
... 

In turn I believe the this would allow `delegator` to be GC'd earlier as well. 

Not sure on the JS compiler details here for nested objects but I think it's roughly accurate. 

Anyway don't mind my rambling here, just trying to practice thinking and being mindful about how code behaves on a low level a bit more.

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingWidget/Input.tsx
> +  const totalStaked = Number(protocol.totalActiveStake)
Can use unary plus 

```suggestion
  const totalSupply = +protocol.totalTokenSupply
  const totalStaked =  +protocol.totalActiveStake
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingWidget/Input.tsx
> +    : 0
```suggestion
       return Utils.fromWei((Math.round(+roi) || 0).toString()),
```

The compiler is smart enough to avoid scientific notation when converting to string 

i.e. 

```javascript
1e5.toString() = "500000"
```

```javascript
const roi = NaN
(Math.round(+roi) || 0).toString()
// result: "0"
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingWidget/InputBox.tsx
> +    delegator?.bondedAmount
I find `(delegator?.bondedAmount || '0') to be more legible , but I'll leave it up to you

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingWidget/InputBox.tsx
> +      : '0' >
I find `(delegator?.bondedAmount || '0')` to be more legible , but I'll leave it up to you 

```suggestion
   (delegator?.bondedAmount || '0') >
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingWidget/InputBox.tsx
> +        Utils.fromWei(delegator?.pendingStake ? delegator?.pendingStake : '0')
```suggestion
        Utils.fromWei(delegator?.pendingStake || '0')
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingWidget/InputBox.tsx
> +    stake = delegator?.bondedAmount ? delegator?.bondedAmount : '0'
We are already evaluating this expression at L20 , we can re-use it

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/Tokenholders/index.tsx
>            100
```suggestion
         +cell?.value / +protocol?.totalActiveStake * 100
```

We can use unary plus and the order of operations doesn't matter here ( the multiplication is evaluated first regardless) so no need for extra parenthesis.

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/VotingWidget/index.tsx
> +    data.poll?.tally?.no ? data.poll?.tally?.no : '0',
```suggestion
    data.poll?.tally?.no || '0',
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/VotingWidget/index.tsx
> +    data.poll?.tally?.yes ? data.poll?.tally?.yes : '0',
```suggestion
    data.poll?.tally?.yes || '0',
```

although I believe at this point this will always be defined because we impose similar checks here https://github.com/livepeer/livepeerjs/blob/3d41e72236a7359df16a0f85508acf08f2429f56/packages/explorer-2.0/lib/createSchema.tsx#L145

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/VotingWidget/index.tsx
> +  let totalNonVoteStake = parseFloat(data.poll.totalNonVoteStake)
Can use unary plus, sorry if I'm overdoing it just discovered this feature. 

Also just a good idea to have a ubiquitous method of parsing in here I find. 

```suggestion
  let totalNonVoteStake = +data?.poll?.totalNonVoteStake
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/components/StakingGuide/Step4.tsx
> +            parseFloat(dataMyAccount.account.ethBalance).toFixed(2)}
What do you think of using `abbreviateNumber` here as well and getting rid of the `AND` statement since we can use null propagation operator ? 

```suggestion
abbreviateNumber(+dataMyAccount?.account?.ethBalance, 2)
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/lib/createSchema.tsx
> +              _poll?.tally?.no ? _poll?.tally?.no : '0',
```suggestion
              let noVoteStake = +_poll?.tally?.no || 0
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/lib/createSchema.tsx
> +              _poll?.tally?.yes ? _poll?.tally?.yes : '0',
```suggestion
              let yesVoteStake = +_poll?.tally?.yes || 0
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/lib/utils.tsx
> +    parseFloat(delegator.bondedAmount) === 0
This whole expression (L46-L48) can be shortened I think

```suggestion
    !+delegator?.bondedAmount
```

```javascript
let a = {x:0}

!+a?.x
// true
!+a?.y
// true
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/lib/utils.tsx
> +    transcoders[index].totalStake = +transcoders[index].totalStake + +amount
```suggestion
    transcoders[index].totalStake += +amount
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/lib/utils.tsx
> +        +transcoders[oldDelegateIndex].totalStake - +amount
```suggestion
      transcoders[oldDelegateIndex].totalStake += +amount
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/lib/utils.tsx
> +    transcoders[index].totalStake = +transcoders[index].totalStake - +amount
```suggestion
    transcoders[index].totalStake -= +amount
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/pages/voting/[poll].tsx
> +  let noVoteStake = parseFloat(pollData?.tally?.no ? pollData?.tally?.no : '0')
```suggestion
  let noVoteStake = +pollData?.tally?.no || 0
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/pages/voting/[poll].tsx
> +    pollData?.tally?.yes ? pollData?.tally?.yes : '0',
let yesVoteStake = +pollData?.tally?.yes || 0

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/pages/voting/[poll].tsx
> +  let noVoteStake = parseFloat(poll?.tally?.no ? poll?.tally?.no : '0')
```suggestion
  let noVoteStake = +poll?.tally?.no || 0
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/pages/voting/[poll].tsx
> +  let yesVoteStake = parseFloat(poll?.tally?.yes ? poll?.tally?.yes : '0')
```suggestion
  let yesVoteStake = +poll?.tally?.yes || 0
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/pages/voting/[poll].tsx
> +  let totalVoteStake = parseFloat(poll.totalVoteStake)
```suggestion
  let totalVoteStake = +poll?.totalVoteStake
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/explorer-2.0/pages/voting/[poll].tsx
> +  let totalNonVoteStake = parseFloat(poll.totalNonVoteStake)
```suggestion
  let totalNonVoteStake = +poll?.totalNonVoteStake
```

Instead of using the null propagation operator on each of the values here we could also simply add a check at the beginning of the function; this will save us some operations. 

```
if (!poll) return;
```

2020-12-01 01:32 UTC, kyriediculous commented on packages/subgraph/src/mappings/bondingManager.ts
> +      oldTranscoder.totalStake = convertToDecimal(delegateData.value3)
Is it possible to used named accessors here instead of things like `value3` or is that not allowed ?

2020-12-09 19:46 UTC, adamsoffer commented on packages/subgraph/src/mappings/bondingManager.ts
> +      oldTranscoder.totalStake = convertToDecimal(delegateData.value3)
not allowed/available unfortunately :/

2020-12-21 23:00 UTC, merged