add usage chart (wip)
livepeer/livepeer-monorepo pull request #909
Opened 2021-01-20 21:23 UTC by adamsoffer

2021-02-02 14:58 UTC, yondonfu requested changes

2021-02-02 14:58 UTC, yondonfu commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +      const minutes =
Looks like averagePrice is 6000 wei converted to USD based on a specific fixed USD/ETH exchange rate.

Since the volumeUSD per day is calculated based on the DAI/ETH exchange rate on the day that the fees were generated, I think it could make sense to also determine the USD average price based on the DAI/ETH exchange rate on the day that the fees were generated. I think we should be able to derive the DAI/ETH exchange rate based on the volumeUSD and volumeETH fields included in the Day entity.

For example:

```javascript
// 6000 wei in ETH terms
const averagePrice = 0.000000000000006
...

dayData = dayData.map((item) => {
    ...

    const ethDaiRate = +item.volumeETH / +item.volumeUSD
    const usdAveragePrice = averagePrice * ethDaiRate
    const minutes =
        (found?.sourceSegmentsDuration ?? 0) / 60 +
        +item.volumeUSD / usdAveragePrice / pixelsPerMinute
    ...
})
```

2021-02-02 14:58 UTC, yondonfu commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +  const pixelsPerMinute = 2995488000;
Might be helpful to add a comment here for future reference indicating how this value is calculated i.e. the # of pixels in a minute of 240p30fps, 360p30fps, 480p30fps, 720p30fps transcoded renditions.

2021-02-02 14:58 UTC, yondonfu commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +    twoWeeksAgo.setDate(twoWeeksAgo.getDate() - 7);
Looks like we're setting twoWeeksAgo to the same value as oneWeekAgo here?

2021-02-02 14:58 UTC, yondonfu commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +      return x + y.sourceSegmentsDuration / 60;
I believe sourceSegmentsDuration will track source streams ingested by the .com API while transcodedSegmentsDuration will track transcoded streams for the .com API. Since the network's main responsibility is transcoding right now as opposed to ingest, I think using transcodedSegmentsDuration instead of sourceSegmentsDuration would make sense here.

2021-02-02 17:28 UTC, adamsoffer commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +    twoWeeksAgo.setDate(twoWeeksAgo.getDate() - 7);
Oops yeah that's supposed to be `twoWeeksAgo.getDate() - 14`

2021-02-03 02:31 UTC, adamsoffer commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +      const minutes =
Took a stab at this. Let me know if it looks right to you.

2021-02-03 02:32 UTC, adamsoffer commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +  const pixelsPerMinute = 2995488000;
Done.

2021-02-03 02:32 UTC, adamsoffer commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +    twoWeeksAgo.setDate(twoWeeksAgo.getDate() - 7);
Fixed.

2021-02-03 02:33 UTC, adamsoffer commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +      return x + y.sourceSegmentsDuration / 60;
Done.

2021-02-03 02:46 UTC, yondonfu commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +      let ethDaiRate = +item.volumeETH / +item.volumeUSD;
Could getTotalFeeDerivedMinutes be used here?

2021-02-03 02:46 UTC, yondonfu commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +    let [oneWeekVolumeETH, _weeklyVolumeChangeETH] = get2DayPercentChange(
Is _weeklyVolumeChangeETH used anywhere?

2021-02-03 02:46 UTC, yondonfu commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +    let [oneWeekVolumeUSD, weeklyVolumeChangeUSD] = get2DayPercentChange(
Just noting for clarification - get2DayPercentChange() does not necessarily need to accept param values that represent data between 24 hours ago and 48 hours ago right? Assuming so based on glancing at the implementation.

2021-02-03 03:27 UTC, adamsoffer commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +    let [oneWeekVolumeUSD, weeklyVolumeChangeUSD] = get2DayPercentChange(
yeah that's correct. I should rename that function...

2021-02-03 03:28 UTC, adamsoffer commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +      let ethDaiRate = +item.volumeETH / +item.volumeUSD;
yeah just realized that. Done. https://github.com/livepeer/livepeerjs/pull/909/commits/1bc07f9ca0da3574480d620ebda0f8d6d5de7cc7

2021-02-03 03:38 UTC, adamsoffer commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +    let [oneWeekVolumeETH, _weeklyVolumeChangeETH] = get2DayPercentChange(
It is not actually. Just removed 👍

2021-02-03 14:51 UTC, yondonfu commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +      return x + y.transcodedSegmentsDuration / 60;
Okay after thinking about this some more I now think my original suggestion to use transcodedSegmentsDuration might have been misplaced. transcodedSegmentsDuration will include the duration of each of the transcoded renditions for a source video segment. So, given let's say 4 transcoded renditions, the transcoded segments duration tracked for each source video segment will be the source duration multiplied by 4. I don't think it makes sense to track usage in this manner right now because:

- feeDerivedMinutes represents the # of minutes of source video given the # of pixels in an assumed set of transcoded renditions. So, if we use transcodedSegmentsDuration for the .com API usage, there would be a mismatch between what the .com API usage represents and what feeDerivedMinutes represents
- Focusing the definition of usage on the duration of source video that is transcoded as opposed to the combined duration of transcoded renditions feels simpler right now and easier to understand (i.e. one just needs to consider the amount of video that is being sent into the network)

2021-02-03 14:57 UTC, adamsoffer commented on packages/explorer-2.0/apollo/resolvers/Query.tsx
> +      return x + y.transcodedSegmentsDuration / 60;
This makes sense to me. This would also be consistent with how we're displaying usage back to Livepeer.com customers (using sourceSegmentsDuration).

2021-02-03 16:47 UTC, yondonfu approved these changes
LGTM after completing the banner text TODO

2021-02-03 18:24 UTC, merged