subgraph: fix active field for Transcoder entity
livepeer/livepeer-monorepo pull request #931
Opened 2021-02-20 01:08 UTC by adamsoffer

**What does this pull request do? Explain your changes. (required)**
This PR fixes the active field for the Transcoder entity.

- **How did you test each of these updates (required)**
Deployed the fix to the [livepeer-canary](https://thegraph.com/explorer/subgraph/livepeer/livepeer-canary) subgraph.

**Does this pull request close any open issues?**
Fixes #929

2021-02-22 19:58 UTC, yondonfu requested changes
Realized that looping through the on-chain pool in the newRound handler won't quite cover all cases because if a transcoder is pending deactivation in round N, it will be inactive in round N + 1 and will not be in the on-chain pool. So, when the newRound handler fires in round N + 1, we won't be able to set the active field for that transcoder to false when we loop through the on-chain pool. We need a way to set the active field for that transcoder to false when round N + 1 begins. 

Maybe one of the following?

- Iterate through all registered transcoders in the newRound handler
- Maintain a global pending activation map and pending deactivation map. Add to former for TranscoderActivated events and add to latter for TranscoderDeactivated events. In the newRound handler, for each pending activation entry set active = true for the transcoder and for each pending deactivation entry set active = false for the transcoder. Then, clear both maps.

2021-02-22 19:58 UTC, yondonfu commented on packages/subgraph/src/mappings/roundsManager.ts
> +      event.params.round.ge(transcoder.activationRound) &&
`ge` -> `gte`

2021-04-01 20:40 UTC, yondonfu approved these changes
LGTM!

2021-04-01 20:42 UTC, merged

2021-04-01 20:43 UTC, adamsoffer commented
@yondonfu Just remembered I'll need to update the subgraph API reference in the docs with these new fields. I'll create a new issues inside livepeerjs for that.

2021-04-01 20:45 UTC, yondonfu commented
> @yondonfu Just remembered I'll need to update the subgraph API reference in the docs with these new fields. I'll create a new issues inside livepeerjs for that.

Good call!